// Code generated by ent, DO NOT EDIT.

package drugndcmap

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the drugndcmap type in the database.
	Label = "drug_ndc_map"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNdc holds the string denoting the ndc field in the database.
	FieldNdc = "ndc"
	// FieldNdcStatus holds the string denoting the ndc_status field in the database.
	FieldNdcStatus = "ndc_status"
	// FieldManufacturer holds the string denoting the manufacturer field in the database.
	FieldManufacturer = "manufacturer"
	// FieldPackageDescription holds the string denoting the package_description field in the database.
	FieldPackageDescription = "package_description"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDrug holds the string denoting the drug edge name in mutations.
	EdgeDrug = "drug"
	// Table holds the table name of the drugndcmap in the database.
	Table = "drug_ndc_maps"
	// DrugTable is the table that holds the drug relation/edge.
	DrugTable = "drug_ndc_maps"
	// DrugInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugInverseTable = "drugs"
	// DrugColumn is the table column denoting the drug relation/edge.
	DrugColumn = "drug_ndc_mappings"
)

// Columns holds all SQL columns for drugndcmap fields.
var Columns = []string{
	FieldID,
	FieldNdc,
	FieldNdcStatus,
	FieldManufacturer,
	FieldPackageDescription,
	FieldStartDate,
	FieldEndDate,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "drug_ndc_maps"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"drug_ndc_mappings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NdcValidator is a validator for the "ndc" field. It is called by the builders before save.
	NdcValidator func(string) error
	// NdcStatusValidator is a validator for the "ndc_status" field. It is called by the builders before save.
	NdcStatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DrugNdcMap queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNdc orders the results by the ndc field.
func ByNdc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNdc, opts...).ToFunc()
}

// ByNdcStatus orders the results by the ndc_status field.
func ByNdcStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNdcStatus, opts...).ToFunc()
}

// ByManufacturer orders the results by the manufacturer field.
func ByManufacturer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManufacturer, opts...).ToFunc()
}

// ByPackageDescription orders the results by the package_description field.
func ByPackageDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageDescription, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDrugField orders the results by drug field.
func ByDrugField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDrugStep(), sql.OrderByField(field, opts...))
	}
}
func newDrugStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DrugInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DrugTable, DrugColumn),
	)
}
