// Code generated by ent, DO NOT EDIT.

package drugndcmap

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLTE(FieldID, id))
}

// Ndc applies equality check predicate on the "ndc" field. It's identical to NdcEQ.
func Ndc(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldNdc, v))
}

// NdcStatus applies equality check predicate on the "ndc_status" field. It's identical to NdcStatusEQ.
func NdcStatus(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldNdcStatus, v))
}

// Manufacturer applies equality check predicate on the "manufacturer" field. It's identical to ManufacturerEQ.
func Manufacturer(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldManufacturer, v))
}

// PackageDescription applies equality check predicate on the "package_description" field. It's identical to PackageDescriptionEQ.
func PackageDescription(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldPackageDescription, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldEndDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldCreatedAt, v))
}

// NdcEQ applies the EQ predicate on the "ndc" field.
func NdcEQ(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldNdc, v))
}

// NdcNEQ applies the NEQ predicate on the "ndc" field.
func NdcNEQ(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNEQ(FieldNdc, v))
}

// NdcIn applies the In predicate on the "ndc" field.
func NdcIn(vs ...string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIn(FieldNdc, vs...))
}

// NdcNotIn applies the NotIn predicate on the "ndc" field.
func NdcNotIn(vs ...string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotIn(FieldNdc, vs...))
}

// NdcGT applies the GT predicate on the "ndc" field.
func NdcGT(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGT(FieldNdc, v))
}

// NdcGTE applies the GTE predicate on the "ndc" field.
func NdcGTE(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGTE(FieldNdc, v))
}

// NdcLT applies the LT predicate on the "ndc" field.
func NdcLT(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLT(FieldNdc, v))
}

// NdcLTE applies the LTE predicate on the "ndc" field.
func NdcLTE(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLTE(FieldNdc, v))
}

// NdcContains applies the Contains predicate on the "ndc" field.
func NdcContains(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldContains(FieldNdc, v))
}

// NdcHasPrefix applies the HasPrefix predicate on the "ndc" field.
func NdcHasPrefix(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldHasPrefix(FieldNdc, v))
}

// NdcHasSuffix applies the HasSuffix predicate on the "ndc" field.
func NdcHasSuffix(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldHasSuffix(FieldNdc, v))
}

// NdcEqualFold applies the EqualFold predicate on the "ndc" field.
func NdcEqualFold(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEqualFold(FieldNdc, v))
}

// NdcContainsFold applies the ContainsFold predicate on the "ndc" field.
func NdcContainsFold(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldContainsFold(FieldNdc, v))
}

// NdcStatusEQ applies the EQ predicate on the "ndc_status" field.
func NdcStatusEQ(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldNdcStatus, v))
}

// NdcStatusNEQ applies the NEQ predicate on the "ndc_status" field.
func NdcStatusNEQ(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNEQ(FieldNdcStatus, v))
}

// NdcStatusIn applies the In predicate on the "ndc_status" field.
func NdcStatusIn(vs ...string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIn(FieldNdcStatus, vs...))
}

// NdcStatusNotIn applies the NotIn predicate on the "ndc_status" field.
func NdcStatusNotIn(vs ...string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotIn(FieldNdcStatus, vs...))
}

// NdcStatusGT applies the GT predicate on the "ndc_status" field.
func NdcStatusGT(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGT(FieldNdcStatus, v))
}

// NdcStatusGTE applies the GTE predicate on the "ndc_status" field.
func NdcStatusGTE(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGTE(FieldNdcStatus, v))
}

// NdcStatusLT applies the LT predicate on the "ndc_status" field.
func NdcStatusLT(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLT(FieldNdcStatus, v))
}

// NdcStatusLTE applies the LTE predicate on the "ndc_status" field.
func NdcStatusLTE(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLTE(FieldNdcStatus, v))
}

// NdcStatusContains applies the Contains predicate on the "ndc_status" field.
func NdcStatusContains(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldContains(FieldNdcStatus, v))
}

// NdcStatusHasPrefix applies the HasPrefix predicate on the "ndc_status" field.
func NdcStatusHasPrefix(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldHasPrefix(FieldNdcStatus, v))
}

// NdcStatusHasSuffix applies the HasSuffix predicate on the "ndc_status" field.
func NdcStatusHasSuffix(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldHasSuffix(FieldNdcStatus, v))
}

// NdcStatusEqualFold applies the EqualFold predicate on the "ndc_status" field.
func NdcStatusEqualFold(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEqualFold(FieldNdcStatus, v))
}

// NdcStatusContainsFold applies the ContainsFold predicate on the "ndc_status" field.
func NdcStatusContainsFold(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldContainsFold(FieldNdcStatus, v))
}

// ManufacturerEQ applies the EQ predicate on the "manufacturer" field.
func ManufacturerEQ(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldManufacturer, v))
}

// ManufacturerNEQ applies the NEQ predicate on the "manufacturer" field.
func ManufacturerNEQ(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNEQ(FieldManufacturer, v))
}

// ManufacturerIn applies the In predicate on the "manufacturer" field.
func ManufacturerIn(vs ...string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIn(FieldManufacturer, vs...))
}

// ManufacturerNotIn applies the NotIn predicate on the "manufacturer" field.
func ManufacturerNotIn(vs ...string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotIn(FieldManufacturer, vs...))
}

// ManufacturerGT applies the GT predicate on the "manufacturer" field.
func ManufacturerGT(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGT(FieldManufacturer, v))
}

// ManufacturerGTE applies the GTE predicate on the "manufacturer" field.
func ManufacturerGTE(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGTE(FieldManufacturer, v))
}

// ManufacturerLT applies the LT predicate on the "manufacturer" field.
func ManufacturerLT(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLT(FieldManufacturer, v))
}

// ManufacturerLTE applies the LTE predicate on the "manufacturer" field.
func ManufacturerLTE(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLTE(FieldManufacturer, v))
}

// ManufacturerContains applies the Contains predicate on the "manufacturer" field.
func ManufacturerContains(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldContains(FieldManufacturer, v))
}

// ManufacturerHasPrefix applies the HasPrefix predicate on the "manufacturer" field.
func ManufacturerHasPrefix(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldHasPrefix(FieldManufacturer, v))
}

// ManufacturerHasSuffix applies the HasSuffix predicate on the "manufacturer" field.
func ManufacturerHasSuffix(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldHasSuffix(FieldManufacturer, v))
}

// ManufacturerIsNil applies the IsNil predicate on the "manufacturer" field.
func ManufacturerIsNil() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIsNull(FieldManufacturer))
}

// ManufacturerNotNil applies the NotNil predicate on the "manufacturer" field.
func ManufacturerNotNil() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotNull(FieldManufacturer))
}

// ManufacturerEqualFold applies the EqualFold predicate on the "manufacturer" field.
func ManufacturerEqualFold(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEqualFold(FieldManufacturer, v))
}

// ManufacturerContainsFold applies the ContainsFold predicate on the "manufacturer" field.
func ManufacturerContainsFold(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldContainsFold(FieldManufacturer, v))
}

// PackageDescriptionEQ applies the EQ predicate on the "package_description" field.
func PackageDescriptionEQ(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldPackageDescription, v))
}

// PackageDescriptionNEQ applies the NEQ predicate on the "package_description" field.
func PackageDescriptionNEQ(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNEQ(FieldPackageDescription, v))
}

// PackageDescriptionIn applies the In predicate on the "package_description" field.
func PackageDescriptionIn(vs ...string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIn(FieldPackageDescription, vs...))
}

// PackageDescriptionNotIn applies the NotIn predicate on the "package_description" field.
func PackageDescriptionNotIn(vs ...string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotIn(FieldPackageDescription, vs...))
}

// PackageDescriptionGT applies the GT predicate on the "package_description" field.
func PackageDescriptionGT(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGT(FieldPackageDescription, v))
}

// PackageDescriptionGTE applies the GTE predicate on the "package_description" field.
func PackageDescriptionGTE(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGTE(FieldPackageDescription, v))
}

// PackageDescriptionLT applies the LT predicate on the "package_description" field.
func PackageDescriptionLT(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLT(FieldPackageDescription, v))
}

// PackageDescriptionLTE applies the LTE predicate on the "package_description" field.
func PackageDescriptionLTE(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLTE(FieldPackageDescription, v))
}

// PackageDescriptionContains applies the Contains predicate on the "package_description" field.
func PackageDescriptionContains(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldContains(FieldPackageDescription, v))
}

// PackageDescriptionHasPrefix applies the HasPrefix predicate on the "package_description" field.
func PackageDescriptionHasPrefix(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldHasPrefix(FieldPackageDescription, v))
}

// PackageDescriptionHasSuffix applies the HasSuffix predicate on the "package_description" field.
func PackageDescriptionHasSuffix(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldHasSuffix(FieldPackageDescription, v))
}

// PackageDescriptionIsNil applies the IsNil predicate on the "package_description" field.
func PackageDescriptionIsNil() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIsNull(FieldPackageDescription))
}

// PackageDescriptionNotNil applies the NotNil predicate on the "package_description" field.
func PackageDescriptionNotNil() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotNull(FieldPackageDescription))
}

// PackageDescriptionEqualFold applies the EqualFold predicate on the "package_description" field.
func PackageDescriptionEqualFold(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEqualFold(FieldPackageDescription, v))
}

// PackageDescriptionContainsFold applies the ContainsFold predicate on the "package_description" field.
func PackageDescriptionContainsFold(v string) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldContainsFold(FieldPackageDescription, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotNull(FieldStartDate))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotNull(FieldEndDate))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDrug applies the HasEdge predicate on the "drug" edge.
func HasDrug() predicate.DrugNdcMap {
	return predicate.DrugNdcMap(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DrugTable, DrugColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDrugWith applies the HasEdge predicate on the "drug" edge with a given conditions (other predicates).
func HasDrugWith(preds ...predicate.Drug) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(func(s *sql.Selector) {
		step := newDrugStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DrugNdcMap) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DrugNdcMap) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DrugNdcMap) predicate.DrugNdcMap {
	return predicate.DrugNdcMap(sql.NotPredicates(p))
}
