// Code generated by ent, DO NOT EDIT.

package drug

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the drug type in the database.
	Label = "drug"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRxcui holds the string denoting the rxcui field in the database.
	FieldRxcui = "rxcui"
	// FieldDrugName holds the string denoting the drug_name field in the database.
	FieldDrugName = "drug_name"
	// FieldGenericName holds the string denoting the generic_name field in the database.
	FieldGenericName = "generic_name"
	// FieldBrandNames holds the string denoting the brand_names field in the database.
	FieldBrandNames = "brand_names"
	// FieldDoseForm holds the string denoting the dose_form field in the database.
	FieldDoseForm = "dose_form"
	// FieldStrength holds the string denoting the strength field in the database.
	FieldStrength = "strength"
	// FieldRoute holds the string denoting the route field in the database.
	FieldRoute = "route"
	// FieldDrugClass holds the string denoting the drug_class field in the database.
	FieldDrugClass = "drug_class"
	// FieldIsSpecialty holds the string denoting the is_specialty field in the database.
	FieldIsSpecialty = "is_specialty"
	// FieldIsControlled holds the string denoting the is_controlled field in the database.
	FieldIsControlled = "is_controlled"
	// FieldDeaSchedule holds the string denoting the dea_schedule field in the database.
	FieldDeaSchedule = "dea_schedule"
	// FieldLastRxnormSync holds the string denoting the last_rxnorm_sync field in the database.
	FieldLastRxnormSync = "last_rxnorm_sync"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeNdcMappings holds the string denoting the ndc_mappings edge name in mutations.
	EdgeNdcMappings = "ndc_mappings"
	// EdgeFormularyEntries holds the string denoting the formulary_entries edge name in mutations.
	EdgeFormularyEntries = "formulary_entries"
	// Table holds the table name of the drug in the database.
	Table = "drugs"
	// NdcMappingsTable is the table that holds the ndc_mappings relation/edge.
	NdcMappingsTable = "drug_ndc_maps"
	// NdcMappingsInverseTable is the table name for the DrugNdcMap entity.
	// It exists in this package in order to avoid circular dependency with the "drugndcmap" package.
	NdcMappingsInverseTable = "drug_ndc_maps"
	// NdcMappingsColumn is the table column denoting the ndc_mappings relation/edge.
	NdcMappingsColumn = "drug_ndc_mappings"
	// FormularyEntriesTable is the table that holds the formulary_entries relation/edge.
	FormularyEntriesTable = "formulary_entries"
	// FormularyEntriesInverseTable is the table name for the FormularyEntry entity.
	// It exists in this package in order to avoid circular dependency with the "formularyentry" package.
	FormularyEntriesInverseTable = "formulary_entries"
	// FormularyEntriesColumn is the table column denoting the formulary_entries relation/edge.
	FormularyEntriesColumn = "drug_formulary_entries"
)

// Columns holds all SQL columns for drug fields.
var Columns = []string{
	FieldID,
	FieldRxcui,
	FieldDrugName,
	FieldGenericName,
	FieldBrandNames,
	FieldDoseForm,
	FieldStrength,
	FieldRoute,
	FieldDrugClass,
	FieldIsSpecialty,
	FieldIsControlled,
	FieldDeaSchedule,
	FieldLastRxnormSync,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RxcuiValidator is a validator for the "rxcui" field. It is called by the builders before save.
	RxcuiValidator func(string) error
	// DrugNameValidator is a validator for the "drug_name" field. It is called by the builders before save.
	DrugNameValidator func(string) error
	// DefaultIsSpecialty holds the default value on creation for the "is_specialty" field.
	DefaultIsSpecialty bool
	// DefaultIsControlled holds the default value on creation for the "is_controlled" field.
	DefaultIsControlled bool
	// DefaultLastRxnormSync holds the default value on creation for the "last_rxnorm_sync" field.
	DefaultLastRxnormSync func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Drug queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRxcui orders the results by the rxcui field.
func ByRxcui(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRxcui, opts...).ToFunc()
}

// ByDrugName orders the results by the drug_name field.
func ByDrugName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrugName, opts...).ToFunc()
}

// ByGenericName orders the results by the generic_name field.
func ByGenericName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenericName, opts...).ToFunc()
}

// ByDoseForm orders the results by the dose_form field.
func ByDoseForm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDoseForm, opts...).ToFunc()
}

// ByStrength orders the results by the strength field.
func ByStrength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrength, opts...).ToFunc()
}

// ByRoute orders the results by the route field.
func ByRoute(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoute, opts...).ToFunc()
}

// ByDrugClass orders the results by the drug_class field.
func ByDrugClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrugClass, opts...).ToFunc()
}

// ByIsSpecialty orders the results by the is_specialty field.
func ByIsSpecialty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSpecialty, opts...).ToFunc()
}

// ByIsControlled orders the results by the is_controlled field.
func ByIsControlled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsControlled, opts...).ToFunc()
}

// ByDeaSchedule orders the results by the dea_schedule field.
func ByDeaSchedule(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeaSchedule, opts...).ToFunc()
}

// ByLastRxnormSync orders the results by the last_rxnorm_sync field.
func ByLastRxnormSync(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRxnormSync, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNdcMappingsCount orders the results by ndc_mappings count.
func ByNdcMappingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNdcMappingsStep(), opts...)
	}
}

// ByNdcMappings orders the results by ndc_mappings terms.
func ByNdcMappings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNdcMappingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFormularyEntriesCount orders the results by formulary_entries count.
func ByFormularyEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFormularyEntriesStep(), opts...)
	}
}

// ByFormularyEntries orders the results by formulary_entries terms.
func ByFormularyEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFormularyEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNdcMappingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NdcMappingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NdcMappingsTable, NdcMappingsColumn),
	)
}
func newFormularyEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FormularyEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FormularyEntriesTable, FormularyEntriesColumn),
	)
}
