// Code generated by ent, DO NOT EDIT.

package drug

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldID, id))
}

// Rxcui applies equality check predicate on the "rxcui" field. It's identical to RxcuiEQ.
func Rxcui(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldRxcui, v))
}

// DrugName applies equality check predicate on the "drug_name" field. It's identical to DrugNameEQ.
func DrugName(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldDrugName, v))
}

// GenericName applies equality check predicate on the "generic_name" field. It's identical to GenericNameEQ.
func GenericName(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldGenericName, v))
}

// DoseForm applies equality check predicate on the "dose_form" field. It's identical to DoseFormEQ.
func DoseForm(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldDoseForm, v))
}

// Strength applies equality check predicate on the "strength" field. It's identical to StrengthEQ.
func Strength(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldStrength, v))
}

// Route applies equality check predicate on the "route" field. It's identical to RouteEQ.
func Route(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldRoute, v))
}

// DrugClass applies equality check predicate on the "drug_class" field. It's identical to DrugClassEQ.
func DrugClass(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldDrugClass, v))
}

// IsSpecialty applies equality check predicate on the "is_specialty" field. It's identical to IsSpecialtyEQ.
func IsSpecialty(v bool) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldIsSpecialty, v))
}

// IsControlled applies equality check predicate on the "is_controlled" field. It's identical to IsControlledEQ.
func IsControlled(v bool) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldIsControlled, v))
}

// DeaSchedule applies equality check predicate on the "dea_schedule" field. It's identical to DeaScheduleEQ.
func DeaSchedule(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldDeaSchedule, v))
}

// LastRxnormSync applies equality check predicate on the "last_rxnorm_sync" field. It's identical to LastRxnormSyncEQ.
func LastRxnormSync(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldLastRxnormSync, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldUpdatedAt, v))
}

// RxcuiEQ applies the EQ predicate on the "rxcui" field.
func RxcuiEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldRxcui, v))
}

// RxcuiNEQ applies the NEQ predicate on the "rxcui" field.
func RxcuiNEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldRxcui, v))
}

// RxcuiIn applies the In predicate on the "rxcui" field.
func RxcuiIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldRxcui, vs...))
}

// RxcuiNotIn applies the NotIn predicate on the "rxcui" field.
func RxcuiNotIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldRxcui, vs...))
}

// RxcuiGT applies the GT predicate on the "rxcui" field.
func RxcuiGT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldRxcui, v))
}

// RxcuiGTE applies the GTE predicate on the "rxcui" field.
func RxcuiGTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldRxcui, v))
}

// RxcuiLT applies the LT predicate on the "rxcui" field.
func RxcuiLT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldRxcui, v))
}

// RxcuiLTE applies the LTE predicate on the "rxcui" field.
func RxcuiLTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldRxcui, v))
}

// RxcuiContains applies the Contains predicate on the "rxcui" field.
func RxcuiContains(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContains(FieldRxcui, v))
}

// RxcuiHasPrefix applies the HasPrefix predicate on the "rxcui" field.
func RxcuiHasPrefix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasPrefix(FieldRxcui, v))
}

// RxcuiHasSuffix applies the HasSuffix predicate on the "rxcui" field.
func RxcuiHasSuffix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasSuffix(FieldRxcui, v))
}

// RxcuiEqualFold applies the EqualFold predicate on the "rxcui" field.
func RxcuiEqualFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEqualFold(FieldRxcui, v))
}

// RxcuiContainsFold applies the ContainsFold predicate on the "rxcui" field.
func RxcuiContainsFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContainsFold(FieldRxcui, v))
}

// DrugNameEQ applies the EQ predicate on the "drug_name" field.
func DrugNameEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldDrugName, v))
}

// DrugNameNEQ applies the NEQ predicate on the "drug_name" field.
func DrugNameNEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldDrugName, v))
}

// DrugNameIn applies the In predicate on the "drug_name" field.
func DrugNameIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldDrugName, vs...))
}

// DrugNameNotIn applies the NotIn predicate on the "drug_name" field.
func DrugNameNotIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldDrugName, vs...))
}

// DrugNameGT applies the GT predicate on the "drug_name" field.
func DrugNameGT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldDrugName, v))
}

// DrugNameGTE applies the GTE predicate on the "drug_name" field.
func DrugNameGTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldDrugName, v))
}

// DrugNameLT applies the LT predicate on the "drug_name" field.
func DrugNameLT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldDrugName, v))
}

// DrugNameLTE applies the LTE predicate on the "drug_name" field.
func DrugNameLTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldDrugName, v))
}

// DrugNameContains applies the Contains predicate on the "drug_name" field.
func DrugNameContains(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContains(FieldDrugName, v))
}

// DrugNameHasPrefix applies the HasPrefix predicate on the "drug_name" field.
func DrugNameHasPrefix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasPrefix(FieldDrugName, v))
}

// DrugNameHasSuffix applies the HasSuffix predicate on the "drug_name" field.
func DrugNameHasSuffix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasSuffix(FieldDrugName, v))
}

// DrugNameEqualFold applies the EqualFold predicate on the "drug_name" field.
func DrugNameEqualFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEqualFold(FieldDrugName, v))
}

// DrugNameContainsFold applies the ContainsFold predicate on the "drug_name" field.
func DrugNameContainsFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContainsFold(FieldDrugName, v))
}

// GenericNameEQ applies the EQ predicate on the "generic_name" field.
func GenericNameEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldGenericName, v))
}

// GenericNameNEQ applies the NEQ predicate on the "generic_name" field.
func GenericNameNEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldGenericName, v))
}

// GenericNameIn applies the In predicate on the "generic_name" field.
func GenericNameIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldGenericName, vs...))
}

// GenericNameNotIn applies the NotIn predicate on the "generic_name" field.
func GenericNameNotIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldGenericName, vs...))
}

// GenericNameGT applies the GT predicate on the "generic_name" field.
func GenericNameGT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldGenericName, v))
}

// GenericNameGTE applies the GTE predicate on the "generic_name" field.
func GenericNameGTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldGenericName, v))
}

// GenericNameLT applies the LT predicate on the "generic_name" field.
func GenericNameLT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldGenericName, v))
}

// GenericNameLTE applies the LTE predicate on the "generic_name" field.
func GenericNameLTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldGenericName, v))
}

// GenericNameContains applies the Contains predicate on the "generic_name" field.
func GenericNameContains(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContains(FieldGenericName, v))
}

// GenericNameHasPrefix applies the HasPrefix predicate on the "generic_name" field.
func GenericNameHasPrefix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasPrefix(FieldGenericName, v))
}

// GenericNameHasSuffix applies the HasSuffix predicate on the "generic_name" field.
func GenericNameHasSuffix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasSuffix(FieldGenericName, v))
}

// GenericNameIsNil applies the IsNil predicate on the "generic_name" field.
func GenericNameIsNil() predicate.Drug {
	return predicate.Drug(sql.FieldIsNull(FieldGenericName))
}

// GenericNameNotNil applies the NotNil predicate on the "generic_name" field.
func GenericNameNotNil() predicate.Drug {
	return predicate.Drug(sql.FieldNotNull(FieldGenericName))
}

// GenericNameEqualFold applies the EqualFold predicate on the "generic_name" field.
func GenericNameEqualFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEqualFold(FieldGenericName, v))
}

// GenericNameContainsFold applies the ContainsFold predicate on the "generic_name" field.
func GenericNameContainsFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContainsFold(FieldGenericName, v))
}

// BrandNamesIsNil applies the IsNil predicate on the "brand_names" field.
func BrandNamesIsNil() predicate.Drug {
	return predicate.Drug(sql.FieldIsNull(FieldBrandNames))
}

// BrandNamesNotNil applies the NotNil predicate on the "brand_names" field.
func BrandNamesNotNil() predicate.Drug {
	return predicate.Drug(sql.FieldNotNull(FieldBrandNames))
}

// DoseFormEQ applies the EQ predicate on the "dose_form" field.
func DoseFormEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldDoseForm, v))
}

// DoseFormNEQ applies the NEQ predicate on the "dose_form" field.
func DoseFormNEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldDoseForm, v))
}

// DoseFormIn applies the In predicate on the "dose_form" field.
func DoseFormIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldDoseForm, vs...))
}

// DoseFormNotIn applies the NotIn predicate on the "dose_form" field.
func DoseFormNotIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldDoseForm, vs...))
}

// DoseFormGT applies the GT predicate on the "dose_form" field.
func DoseFormGT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldDoseForm, v))
}

// DoseFormGTE applies the GTE predicate on the "dose_form" field.
func DoseFormGTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldDoseForm, v))
}

// DoseFormLT applies the LT predicate on the "dose_form" field.
func DoseFormLT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldDoseForm, v))
}

// DoseFormLTE applies the LTE predicate on the "dose_form" field.
func DoseFormLTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldDoseForm, v))
}

// DoseFormContains applies the Contains predicate on the "dose_form" field.
func DoseFormContains(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContains(FieldDoseForm, v))
}

// DoseFormHasPrefix applies the HasPrefix predicate on the "dose_form" field.
func DoseFormHasPrefix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasPrefix(FieldDoseForm, v))
}

// DoseFormHasSuffix applies the HasSuffix predicate on the "dose_form" field.
func DoseFormHasSuffix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasSuffix(FieldDoseForm, v))
}

// DoseFormIsNil applies the IsNil predicate on the "dose_form" field.
func DoseFormIsNil() predicate.Drug {
	return predicate.Drug(sql.FieldIsNull(FieldDoseForm))
}

// DoseFormNotNil applies the NotNil predicate on the "dose_form" field.
func DoseFormNotNil() predicate.Drug {
	return predicate.Drug(sql.FieldNotNull(FieldDoseForm))
}

// DoseFormEqualFold applies the EqualFold predicate on the "dose_form" field.
func DoseFormEqualFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEqualFold(FieldDoseForm, v))
}

// DoseFormContainsFold applies the ContainsFold predicate on the "dose_form" field.
func DoseFormContainsFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContainsFold(FieldDoseForm, v))
}

// StrengthEQ applies the EQ predicate on the "strength" field.
func StrengthEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldStrength, v))
}

// StrengthNEQ applies the NEQ predicate on the "strength" field.
func StrengthNEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldStrength, v))
}

// StrengthIn applies the In predicate on the "strength" field.
func StrengthIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldStrength, vs...))
}

// StrengthNotIn applies the NotIn predicate on the "strength" field.
func StrengthNotIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldStrength, vs...))
}

// StrengthGT applies the GT predicate on the "strength" field.
func StrengthGT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldStrength, v))
}

// StrengthGTE applies the GTE predicate on the "strength" field.
func StrengthGTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldStrength, v))
}

// StrengthLT applies the LT predicate on the "strength" field.
func StrengthLT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldStrength, v))
}

// StrengthLTE applies the LTE predicate on the "strength" field.
func StrengthLTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldStrength, v))
}

// StrengthContains applies the Contains predicate on the "strength" field.
func StrengthContains(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContains(FieldStrength, v))
}

// StrengthHasPrefix applies the HasPrefix predicate on the "strength" field.
func StrengthHasPrefix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasPrefix(FieldStrength, v))
}

// StrengthHasSuffix applies the HasSuffix predicate on the "strength" field.
func StrengthHasSuffix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasSuffix(FieldStrength, v))
}

// StrengthIsNil applies the IsNil predicate on the "strength" field.
func StrengthIsNil() predicate.Drug {
	return predicate.Drug(sql.FieldIsNull(FieldStrength))
}

// StrengthNotNil applies the NotNil predicate on the "strength" field.
func StrengthNotNil() predicate.Drug {
	return predicate.Drug(sql.FieldNotNull(FieldStrength))
}

// StrengthEqualFold applies the EqualFold predicate on the "strength" field.
func StrengthEqualFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEqualFold(FieldStrength, v))
}

// StrengthContainsFold applies the ContainsFold predicate on the "strength" field.
func StrengthContainsFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContainsFold(FieldStrength, v))
}

// RouteEQ applies the EQ predicate on the "route" field.
func RouteEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldRoute, v))
}

// RouteNEQ applies the NEQ predicate on the "route" field.
func RouteNEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldRoute, v))
}

// RouteIn applies the In predicate on the "route" field.
func RouteIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldRoute, vs...))
}

// RouteNotIn applies the NotIn predicate on the "route" field.
func RouteNotIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldRoute, vs...))
}

// RouteGT applies the GT predicate on the "route" field.
func RouteGT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldRoute, v))
}

// RouteGTE applies the GTE predicate on the "route" field.
func RouteGTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldRoute, v))
}

// RouteLT applies the LT predicate on the "route" field.
func RouteLT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldRoute, v))
}

// RouteLTE applies the LTE predicate on the "route" field.
func RouteLTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldRoute, v))
}

// RouteContains applies the Contains predicate on the "route" field.
func RouteContains(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContains(FieldRoute, v))
}

// RouteHasPrefix applies the HasPrefix predicate on the "route" field.
func RouteHasPrefix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasPrefix(FieldRoute, v))
}

// RouteHasSuffix applies the HasSuffix predicate on the "route" field.
func RouteHasSuffix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasSuffix(FieldRoute, v))
}

// RouteIsNil applies the IsNil predicate on the "route" field.
func RouteIsNil() predicate.Drug {
	return predicate.Drug(sql.FieldIsNull(FieldRoute))
}

// RouteNotNil applies the NotNil predicate on the "route" field.
func RouteNotNil() predicate.Drug {
	return predicate.Drug(sql.FieldNotNull(FieldRoute))
}

// RouteEqualFold applies the EqualFold predicate on the "route" field.
func RouteEqualFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEqualFold(FieldRoute, v))
}

// RouteContainsFold applies the ContainsFold predicate on the "route" field.
func RouteContainsFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContainsFold(FieldRoute, v))
}

// DrugClassEQ applies the EQ predicate on the "drug_class" field.
func DrugClassEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldDrugClass, v))
}

// DrugClassNEQ applies the NEQ predicate on the "drug_class" field.
func DrugClassNEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldDrugClass, v))
}

// DrugClassIn applies the In predicate on the "drug_class" field.
func DrugClassIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldDrugClass, vs...))
}

// DrugClassNotIn applies the NotIn predicate on the "drug_class" field.
func DrugClassNotIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldDrugClass, vs...))
}

// DrugClassGT applies the GT predicate on the "drug_class" field.
func DrugClassGT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldDrugClass, v))
}

// DrugClassGTE applies the GTE predicate on the "drug_class" field.
func DrugClassGTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldDrugClass, v))
}

// DrugClassLT applies the LT predicate on the "drug_class" field.
func DrugClassLT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldDrugClass, v))
}

// DrugClassLTE applies the LTE predicate on the "drug_class" field.
func DrugClassLTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldDrugClass, v))
}

// DrugClassContains applies the Contains predicate on the "drug_class" field.
func DrugClassContains(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContains(FieldDrugClass, v))
}

// DrugClassHasPrefix applies the HasPrefix predicate on the "drug_class" field.
func DrugClassHasPrefix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasPrefix(FieldDrugClass, v))
}

// DrugClassHasSuffix applies the HasSuffix predicate on the "drug_class" field.
func DrugClassHasSuffix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasSuffix(FieldDrugClass, v))
}

// DrugClassIsNil applies the IsNil predicate on the "drug_class" field.
func DrugClassIsNil() predicate.Drug {
	return predicate.Drug(sql.FieldIsNull(FieldDrugClass))
}

// DrugClassNotNil applies the NotNil predicate on the "drug_class" field.
func DrugClassNotNil() predicate.Drug {
	return predicate.Drug(sql.FieldNotNull(FieldDrugClass))
}

// DrugClassEqualFold applies the EqualFold predicate on the "drug_class" field.
func DrugClassEqualFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEqualFold(FieldDrugClass, v))
}

// DrugClassContainsFold applies the ContainsFold predicate on the "drug_class" field.
func DrugClassContainsFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContainsFold(FieldDrugClass, v))
}

// IsSpecialtyEQ applies the EQ predicate on the "is_specialty" field.
func IsSpecialtyEQ(v bool) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldIsSpecialty, v))
}

// IsSpecialtyNEQ applies the NEQ predicate on the "is_specialty" field.
func IsSpecialtyNEQ(v bool) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldIsSpecialty, v))
}

// IsControlledEQ applies the EQ predicate on the "is_controlled" field.
func IsControlledEQ(v bool) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldIsControlled, v))
}

// IsControlledNEQ applies the NEQ predicate on the "is_controlled" field.
func IsControlledNEQ(v bool) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldIsControlled, v))
}

// DeaScheduleEQ applies the EQ predicate on the "dea_schedule" field.
func DeaScheduleEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldDeaSchedule, v))
}

// DeaScheduleNEQ applies the NEQ predicate on the "dea_schedule" field.
func DeaScheduleNEQ(v string) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldDeaSchedule, v))
}

// DeaScheduleIn applies the In predicate on the "dea_schedule" field.
func DeaScheduleIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldDeaSchedule, vs...))
}

// DeaScheduleNotIn applies the NotIn predicate on the "dea_schedule" field.
func DeaScheduleNotIn(vs ...string) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldDeaSchedule, vs...))
}

// DeaScheduleGT applies the GT predicate on the "dea_schedule" field.
func DeaScheduleGT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldDeaSchedule, v))
}

// DeaScheduleGTE applies the GTE predicate on the "dea_schedule" field.
func DeaScheduleGTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldDeaSchedule, v))
}

// DeaScheduleLT applies the LT predicate on the "dea_schedule" field.
func DeaScheduleLT(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldDeaSchedule, v))
}

// DeaScheduleLTE applies the LTE predicate on the "dea_schedule" field.
func DeaScheduleLTE(v string) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldDeaSchedule, v))
}

// DeaScheduleContains applies the Contains predicate on the "dea_schedule" field.
func DeaScheduleContains(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContains(FieldDeaSchedule, v))
}

// DeaScheduleHasPrefix applies the HasPrefix predicate on the "dea_schedule" field.
func DeaScheduleHasPrefix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasPrefix(FieldDeaSchedule, v))
}

// DeaScheduleHasSuffix applies the HasSuffix predicate on the "dea_schedule" field.
func DeaScheduleHasSuffix(v string) predicate.Drug {
	return predicate.Drug(sql.FieldHasSuffix(FieldDeaSchedule, v))
}

// DeaScheduleIsNil applies the IsNil predicate on the "dea_schedule" field.
func DeaScheduleIsNil() predicate.Drug {
	return predicate.Drug(sql.FieldIsNull(FieldDeaSchedule))
}

// DeaScheduleNotNil applies the NotNil predicate on the "dea_schedule" field.
func DeaScheduleNotNil() predicate.Drug {
	return predicate.Drug(sql.FieldNotNull(FieldDeaSchedule))
}

// DeaScheduleEqualFold applies the EqualFold predicate on the "dea_schedule" field.
func DeaScheduleEqualFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldEqualFold(FieldDeaSchedule, v))
}

// DeaScheduleContainsFold applies the ContainsFold predicate on the "dea_schedule" field.
func DeaScheduleContainsFold(v string) predicate.Drug {
	return predicate.Drug(sql.FieldContainsFold(FieldDeaSchedule, v))
}

// LastRxnormSyncEQ applies the EQ predicate on the "last_rxnorm_sync" field.
func LastRxnormSyncEQ(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldLastRxnormSync, v))
}

// LastRxnormSyncNEQ applies the NEQ predicate on the "last_rxnorm_sync" field.
func LastRxnormSyncNEQ(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldLastRxnormSync, v))
}

// LastRxnormSyncIn applies the In predicate on the "last_rxnorm_sync" field.
func LastRxnormSyncIn(vs ...time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldLastRxnormSync, vs...))
}

// LastRxnormSyncNotIn applies the NotIn predicate on the "last_rxnorm_sync" field.
func LastRxnormSyncNotIn(vs ...time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldLastRxnormSync, vs...))
}

// LastRxnormSyncGT applies the GT predicate on the "last_rxnorm_sync" field.
func LastRxnormSyncGT(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldLastRxnormSync, v))
}

// LastRxnormSyncGTE applies the GTE predicate on the "last_rxnorm_sync" field.
func LastRxnormSyncGTE(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldLastRxnormSync, v))
}

// LastRxnormSyncLT applies the LT predicate on the "last_rxnorm_sync" field.
func LastRxnormSyncLT(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldLastRxnormSync, v))
}

// LastRxnormSyncLTE applies the LTE predicate on the "last_rxnorm_sync" field.
func LastRxnormSyncLTE(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldLastRxnormSync, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Drug {
	return predicate.Drug(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasNdcMappings applies the HasEdge predicate on the "ndc_mappings" edge.
func HasNdcMappings() predicate.Drug {
	return predicate.Drug(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NdcMappingsTable, NdcMappingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNdcMappingsWith applies the HasEdge predicate on the "ndc_mappings" edge with a given conditions (other predicates).
func HasNdcMappingsWith(preds ...predicate.DrugNdcMap) predicate.Drug {
	return predicate.Drug(func(s *sql.Selector) {
		step := newNdcMappingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFormularyEntries applies the HasEdge predicate on the "formulary_entries" edge.
func HasFormularyEntries() predicate.Drug {
	return predicate.Drug(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FormularyEntriesTable, FormularyEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFormularyEntriesWith applies the HasEdge predicate on the "formulary_entries" edge with a given conditions (other predicates).
func HasFormularyEntriesWith(preds ...predicate.FormularyEntry) predicate.Drug {
	return predicate.Drug(func(s *sql.Selector) {
		step := newFormularyEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Drug) predicate.Drug {
	return predicate.Drug(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Drug) predicate.Drug {
	return predicate.Drug(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Drug) predicate.Drug {
	return predicate.Drug(sql.NotPredicates(p))
}
