// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DrugsColumns holds the columns for the "drugs" table.
	DrugsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "rxcui", Type: field.TypeString, Unique: true},
		{Name: "drug_name", Type: field.TypeString},
		{Name: "generic_name", Type: field.TypeString, Nullable: true},
		{Name: "brand_names", Type: field.TypeJSON, Nullable: true},
		{Name: "dose_form", Type: field.TypeString, Nullable: true},
		{Name: "strength", Type: field.TypeString, Nullable: true},
		{Name: "route", Type: field.TypeString, Nullable: true},
		{Name: "drug_class", Type: field.TypeString, Nullable: true},
		{Name: "is_specialty", Type: field.TypeBool, Default: false},
		{Name: "is_controlled", Type: field.TypeBool, Default: false},
		{Name: "dea_schedule", Type: field.TypeString, Nullable: true},
		{Name: "last_rxnorm_sync", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DrugsTable holds the schema information for the "drugs" table.
	DrugsTable = &schema.Table{
		Name:       "drugs",
		Columns:    DrugsColumns,
		PrimaryKey: []*schema.Column{DrugsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "drug_rxcui",
				Unique:  false,
				Columns: []*schema.Column{DrugsColumns[1]},
			},
			{
				Name:    "drug_drug_name",
				Unique:  false,
				Columns: []*schema.Column{DrugsColumns[2]},
			},
		},
	}
	// DrugNdcMapsColumns holds the columns for the "drug_ndc_maps" table.
	DrugNdcMapsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ndc", Type: field.TypeString, Unique: true},
		{Name: "ndc_status", Type: field.TypeString},
		{Name: "manufacturer", Type: field.TypeString, Nullable: true},
		{Name: "package_description", Type: field.TypeString, Nullable: true},
		{Name: "start_date", Type: field.TypeTime, Nullable: true},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "drug_ndc_mappings", Type: field.TypeInt},
	}
	// DrugNdcMapsTable holds the schema information for the "drug_ndc_maps" table.
	DrugNdcMapsTable = &schema.Table{
		Name:       "drug_ndc_maps",
		Columns:    DrugNdcMapsColumns,
		PrimaryKey: []*schema.Column{DrugNdcMapsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "drug_ndc_maps_drugs_ndc_mappings",
				Columns:    []*schema.Column{DrugNdcMapsColumns[8]},
				RefColumns: []*schema.Column{DrugsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "drugndcmap_ndc",
				Unique:  false,
				Columns: []*schema.Column{DrugNdcMapsColumns[1]},
			},
		},
	}
	// FormularyEntriesColumns holds the columns for the "formulary_entries" table.
	FormularyEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tier_level", Type: field.TypeInt, Nullable: true},
		{Name: "tier_name", Type: field.TypeString, Nullable: true},
		{Name: "prior_auth_required", Type: field.TypeBool, Default: false},
		{Name: "step_therapy", Type: field.TypeBool, Default: false},
		{Name: "quantity_limit", Type: field.TypeBool, Default: false},
		{Name: "quantity_limit_amount", Type: field.TypeFloat64, Nullable: true},
		{Name: "quantity_limit_days", Type: field.TypeInt, Nullable: true},
		{Name: "copay_amount", Type: field.TypeFloat64, Nullable: true},
		{Name: "coinsurance_pct", Type: field.TypeFloat64, Nullable: true},
		{Name: "source_type", Type: field.TypeString},
		{Name: "source_date", Type: field.TypeTime},
		{Name: "is_current", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "drug_formulary_entries", Type: field.TypeInt},
		{Name: "plan_formulary_entries", Type: field.TypeInt},
	}
	// FormularyEntriesTable holds the schema information for the "formulary_entries" table.
	FormularyEntriesTable = &schema.Table{
		Name:       "formulary_entries",
		Columns:    FormularyEntriesColumns,
		PrimaryKey: []*schema.Column{FormularyEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "formulary_entries_drugs_formulary_entries",
				Columns:    []*schema.Column{FormularyEntriesColumns[14]},
				RefColumns: []*schema.Column{DrugsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "formulary_entries_plans_formulary_entries",
				Columns:    []*schema.Column{FormularyEntriesColumns[15]},
				RefColumns: []*schema.Column{PlansColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "formularyentry_is_current",
				Unique:  false,
				Columns: []*schema.Column{FormularyEntriesColumns[12]},
			},
			{
				Name:    "formularyentry_source_type",
				Unique:  false,
				Columns: []*schema.Column{FormularyEntriesColumns[10]},
			},
		},
	}
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "contract_id", Type: field.TypeString},
		{Name: "plan_id", Type: field.TypeString},
		{Name: "segment_id", Type: field.TypeString},
		{Name: "contract_name", Type: field.TypeString, Nullable: true},
		{Name: "plan_name", Type: field.TypeString, Nullable: true},
		{Name: "formulary_id", Type: field.TypeString},
		{Name: "plan_type", Type: field.TypeString, Nullable: true},
		{Name: "snp_type", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:       "plans",
		Columns:    PlansColumns,
		PrimaryKey: []*schema.Column{PlansColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "plan_contract_id_plan_id_segment_id",
				Unique:  true,
				Columns: []*schema.Column{PlansColumns[1], PlansColumns[2], PlansColumns[3]},
			},
			{
				Name:    "plan_formulary_id",
				Unique:  false,
				Columns: []*schema.Column{PlansColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DrugsTable,
		DrugNdcMapsTable,
		FormularyEntriesTable,
		PlansTable,
	}
)

func init() {
	DrugNdcMapsTable.ForeignKeys[0].RefTable = DrugsTable
	FormularyEntriesTable.ForeignKeys[0].RefTable = DrugsTable
	FormularyEntriesTable.ForeignKeys[1].RefTable = PlansTable
}
