// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/kyanaman/formularycheck/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/drugndcmap"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/plan"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Drug is the client for interacting with the Drug builders.
	Drug *DrugClient
	// DrugNdcMap is the client for interacting with the DrugNdcMap builders.
	DrugNdcMap *DrugNdcMapClient
	// FormularyEntry is the client for interacting with the FormularyEntry builders.
	FormularyEntry *FormularyEntryClient
	// Plan is the client for interacting with the Plan builders.
	Plan *PlanClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Drug = NewDrugClient(c.config)
	c.DrugNdcMap = NewDrugNdcMapClient(c.config)
	c.FormularyEntry = NewFormularyEntryClient(c.config)
	c.Plan = NewPlanClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Drug:           NewDrugClient(cfg),
		DrugNdcMap:     NewDrugNdcMapClient(cfg),
		FormularyEntry: NewFormularyEntryClient(cfg),
		Plan:           NewPlanClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Drug:           NewDrugClient(cfg),
		DrugNdcMap:     NewDrugNdcMapClient(cfg),
		FormularyEntry: NewFormularyEntryClient(cfg),
		Plan:           NewPlanClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Drug.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Drug.Use(hooks...)
	c.DrugNdcMap.Use(hooks...)
	c.FormularyEntry.Use(hooks...)
	c.Plan.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Drug.Intercept(interceptors...)
	c.DrugNdcMap.Intercept(interceptors...)
	c.FormularyEntry.Intercept(interceptors...)
	c.Plan.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DrugMutation:
		return c.Drug.mutate(ctx, m)
	case *DrugNdcMapMutation:
		return c.DrugNdcMap.mutate(ctx, m)
	case *FormularyEntryMutation:
		return c.FormularyEntry.mutate(ctx, m)
	case *PlanMutation:
		return c.Plan.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DrugClient is a client for the Drug schema.
type DrugClient struct {
	config
}

// NewDrugClient returns a client for the Drug from the given config.
func NewDrugClient(c config) *DrugClient {
	return &DrugClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `drug.Hooks(f(g(h())))`.
func (c *DrugClient) Use(hooks ...Hook) {
	c.hooks.Drug = append(c.hooks.Drug, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `drug.Intercept(f(g(h())))`.
func (c *DrugClient) Intercept(interceptors ...Interceptor) {
	c.inters.Drug = append(c.inters.Drug, interceptors...)
}

// Create returns a builder for creating a Drug entity.
func (c *DrugClient) Create() *DrugCreate {
	mutation := newDrugMutation(c.config, OpCreate)
	return &DrugCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Drug entities.
func (c *DrugClient) CreateBulk(builders ...*DrugCreate) *DrugCreateBulk {
	return &DrugCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DrugClient) MapCreateBulk(slice any, setFunc func(*DrugCreate, int)) *DrugCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DrugCreateBulk{err: fmt.Errorf("calling to DrugClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DrugCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DrugCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Drug.
func (c *DrugClient) Update() *DrugUpdate {
	mutation := newDrugMutation(c.config, OpUpdate)
	return &DrugUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DrugClient) UpdateOne(_m *Drug) *DrugUpdateOne {
	mutation := newDrugMutation(c.config, OpUpdateOne, withDrug(_m))
	return &DrugUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DrugClient) UpdateOneID(id int) *DrugUpdateOne {
	mutation := newDrugMutation(c.config, OpUpdateOne, withDrugID(id))
	return &DrugUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Drug.
func (c *DrugClient) Delete() *DrugDelete {
	mutation := newDrugMutation(c.config, OpDelete)
	return &DrugDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DrugClient) DeleteOne(_m *Drug) *DrugDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DrugClient) DeleteOneID(id int) *DrugDeleteOne {
	builder := c.Delete().Where(drug.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DrugDeleteOne{builder}
}

// Query returns a query builder for Drug.
func (c *DrugClient) Query() *DrugQuery {
	return &DrugQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDrug},
		inters: c.Interceptors(),
	}
}

// Get returns a Drug entity by its id.
func (c *DrugClient) Get(ctx context.Context, id int) (*Drug, error) {
	return c.Query().Where(drug.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DrugClient) GetX(ctx context.Context, id int) *Drug {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNdcMappings queries the ndc_mappings edge of a Drug.
func (c *DrugClient) QueryNdcMappings(_m *Drug) *DrugNdcMapQuery {
	query := (&DrugNdcMapClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(drug.Table, drug.FieldID, id),
			sqlgraph.To(drugndcmap.Table, drugndcmap.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, drug.NdcMappingsTable, drug.NdcMappingsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFormularyEntries queries the formulary_entries edge of a Drug.
func (c *DrugClient) QueryFormularyEntries(_m *Drug) *FormularyEntryQuery {
	query := (&FormularyEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(drug.Table, drug.FieldID, id),
			sqlgraph.To(formularyentry.Table, formularyentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, drug.FormularyEntriesTable, drug.FormularyEntriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DrugClient) Hooks() []Hook {
	return c.hooks.Drug
}

// Interceptors returns the client interceptors.
func (c *DrugClient) Interceptors() []Interceptor {
	return c.inters.Drug
}

func (c *DrugClient) mutate(ctx context.Context, m *DrugMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DrugCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DrugUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DrugUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DrugDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Drug mutation op: %q", m.Op())
	}
}

// DrugNdcMapClient is a client for the DrugNdcMap schema.
type DrugNdcMapClient struct {
	config
}

// NewDrugNdcMapClient returns a client for the DrugNdcMap from the given config.
func NewDrugNdcMapClient(c config) *DrugNdcMapClient {
	return &DrugNdcMapClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `drugndcmap.Hooks(f(g(h())))`.
func (c *DrugNdcMapClient) Use(hooks ...Hook) {
	c.hooks.DrugNdcMap = append(c.hooks.DrugNdcMap, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `drugndcmap.Intercept(f(g(h())))`.
func (c *DrugNdcMapClient) Intercept(interceptors ...Interceptor) {
	c.inters.DrugNdcMap = append(c.inters.DrugNdcMap, interceptors...)
}

// Create returns a builder for creating a DrugNdcMap entity.
func (c *DrugNdcMapClient) Create() *DrugNdcMapCreate {
	mutation := newDrugNdcMapMutation(c.config, OpCreate)
	return &DrugNdcMapCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DrugNdcMap entities.
func (c *DrugNdcMapClient) CreateBulk(builders ...*DrugNdcMapCreate) *DrugNdcMapCreateBulk {
	return &DrugNdcMapCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DrugNdcMapClient) MapCreateBulk(slice any, setFunc func(*DrugNdcMapCreate, int)) *DrugNdcMapCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DrugNdcMapCreateBulk{err: fmt.Errorf("calling to DrugNdcMapClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DrugNdcMapCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DrugNdcMapCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DrugNdcMap.
func (c *DrugNdcMapClient) Update() *DrugNdcMapUpdate {
	mutation := newDrugNdcMapMutation(c.config, OpUpdate)
	return &DrugNdcMapUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DrugNdcMapClient) UpdateOne(_m *DrugNdcMap) *DrugNdcMapUpdateOne {
	mutation := newDrugNdcMapMutation(c.config, OpUpdateOne, withDrugNdcMap(_m))
	return &DrugNdcMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DrugNdcMapClient) UpdateOneID(id int) *DrugNdcMapUpdateOne {
	mutation := newDrugNdcMapMutation(c.config, OpUpdateOne, withDrugNdcMapID(id))
	return &DrugNdcMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DrugNdcMap.
func (c *DrugNdcMapClient) Delete() *DrugNdcMapDelete {
	mutation := newDrugNdcMapMutation(c.config, OpDelete)
	return &DrugNdcMapDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DrugNdcMapClient) DeleteOne(_m *DrugNdcMap) *DrugNdcMapDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DrugNdcMapClient) DeleteOneID(id int) *DrugNdcMapDeleteOne {
	builder := c.Delete().Where(drugndcmap.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DrugNdcMapDeleteOne{builder}
}

// Query returns a query builder for DrugNdcMap.
func (c *DrugNdcMapClient) Query() *DrugNdcMapQuery {
	return &DrugNdcMapQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDrugNdcMap},
		inters: c.Interceptors(),
	}
}

// Get returns a DrugNdcMap entity by its id.
func (c *DrugNdcMapClient) Get(ctx context.Context, id int) (*DrugNdcMap, error) {
	return c.Query().Where(drugndcmap.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DrugNdcMapClient) GetX(ctx context.Context, id int) *DrugNdcMap {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDrug queries the drug edge of a DrugNdcMap.
func (c *DrugNdcMapClient) QueryDrug(_m *DrugNdcMap) *DrugQuery {
	query := (&DrugClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(drugndcmap.Table, drugndcmap.FieldID, id),
			sqlgraph.To(drug.Table, drug.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, drugndcmap.DrugTable, drugndcmap.DrugColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DrugNdcMapClient) Hooks() []Hook {
	return c.hooks.DrugNdcMap
}

// Interceptors returns the client interceptors.
func (c *DrugNdcMapClient) Interceptors() []Interceptor {
	return c.inters.DrugNdcMap
}

func (c *DrugNdcMapClient) mutate(ctx context.Context, m *DrugNdcMapMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DrugNdcMapCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DrugNdcMapUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DrugNdcMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DrugNdcMapDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DrugNdcMap mutation op: %q", m.Op())
	}
}

// FormularyEntryClient is a client for the FormularyEntry schema.
type FormularyEntryClient struct {
	config
}

// NewFormularyEntryClient returns a client for the FormularyEntry from the given config.
func NewFormularyEntryClient(c config) *FormularyEntryClient {
	return &FormularyEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `formularyentry.Hooks(f(g(h())))`.
func (c *FormularyEntryClient) Use(hooks ...Hook) {
	c.hooks.FormularyEntry = append(c.hooks.FormularyEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `formularyentry.Intercept(f(g(h())))`.
func (c *FormularyEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.FormularyEntry = append(c.inters.FormularyEntry, interceptors...)
}

// Create returns a builder for creating a FormularyEntry entity.
func (c *FormularyEntryClient) Create() *FormularyEntryCreate {
	mutation := newFormularyEntryMutation(c.config, OpCreate)
	return &FormularyEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FormularyEntry entities.
func (c *FormularyEntryClient) CreateBulk(builders ...*FormularyEntryCreate) *FormularyEntryCreateBulk {
	return &FormularyEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FormularyEntryClient) MapCreateBulk(slice any, setFunc func(*FormularyEntryCreate, int)) *FormularyEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FormularyEntryCreateBulk{err: fmt.Errorf("calling to FormularyEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FormularyEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FormularyEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FormularyEntry.
func (c *FormularyEntryClient) Update() *FormularyEntryUpdate {
	mutation := newFormularyEntryMutation(c.config, OpUpdate)
	return &FormularyEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FormularyEntryClient) UpdateOne(_m *FormularyEntry) *FormularyEntryUpdateOne {
	mutation := newFormularyEntryMutation(c.config, OpUpdateOne, withFormularyEntry(_m))
	return &FormularyEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FormularyEntryClient) UpdateOneID(id int) *FormularyEntryUpdateOne {
	mutation := newFormularyEntryMutation(c.config, OpUpdateOne, withFormularyEntryID(id))
	return &FormularyEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FormularyEntry.
func (c *FormularyEntryClient) Delete() *FormularyEntryDelete {
	mutation := newFormularyEntryMutation(c.config, OpDelete)
	return &FormularyEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FormularyEntryClient) DeleteOne(_m *FormularyEntry) *FormularyEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FormularyEntryClient) DeleteOneID(id int) *FormularyEntryDeleteOne {
	builder := c.Delete().Where(formularyentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FormularyEntryDeleteOne{builder}
}

// Query returns a query builder for FormularyEntry.
func (c *FormularyEntryClient) Query() *FormularyEntryQuery {
	return &FormularyEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFormularyEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a FormularyEntry entity by its id.
func (c *FormularyEntryClient) Get(ctx context.Context, id int) (*FormularyEntry, error) {
	return c.Query().Where(formularyentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FormularyEntryClient) GetX(ctx context.Context, id int) *FormularyEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPlan queries the plan edge of a FormularyEntry.
func (c *FormularyEntryClient) QueryPlan(_m *FormularyEntry) *PlanQuery {
	query := (&PlanClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(formularyentry.Table, formularyentry.FieldID, id),
			sqlgraph.To(plan.Table, plan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, formularyentry.PlanTable, formularyentry.PlanColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDrug queries the drug edge of a FormularyEntry.
func (c *FormularyEntryClient) QueryDrug(_m *FormularyEntry) *DrugQuery {
	query := (&DrugClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(formularyentry.Table, formularyentry.FieldID, id),
			sqlgraph.To(drug.Table, drug.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, formularyentry.DrugTable, formularyentry.DrugColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FormularyEntryClient) Hooks() []Hook {
	return c.hooks.FormularyEntry
}

// Interceptors returns the client interceptors.
func (c *FormularyEntryClient) Interceptors() []Interceptor {
	return c.inters.FormularyEntry
}

func (c *FormularyEntryClient) mutate(ctx context.Context, m *FormularyEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FormularyEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FormularyEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FormularyEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FormularyEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FormularyEntry mutation op: %q", m.Op())
	}
}

// PlanClient is a client for the Plan schema.
type PlanClient struct {
	config
}

// NewPlanClient returns a client for the Plan from the given config.
func NewPlanClient(c config) *PlanClient {
	return &PlanClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `plan.Hooks(f(g(h())))`.
func (c *PlanClient) Use(hooks ...Hook) {
	c.hooks.Plan = append(c.hooks.Plan, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `plan.Intercept(f(g(h())))`.
func (c *PlanClient) Intercept(interceptors ...Interceptor) {
	c.inters.Plan = append(c.inters.Plan, interceptors...)
}

// Create returns a builder for creating a Plan entity.
func (c *PlanClient) Create() *PlanCreate {
	mutation := newPlanMutation(c.config, OpCreate)
	return &PlanCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Plan entities.
func (c *PlanClient) CreateBulk(builders ...*PlanCreate) *PlanCreateBulk {
	return &PlanCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PlanClient) MapCreateBulk(slice any, setFunc func(*PlanCreate, int)) *PlanCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PlanCreateBulk{err: fmt.Errorf("calling to PlanClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PlanCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PlanCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Plan.
func (c *PlanClient) Update() *PlanUpdate {
	mutation := newPlanMutation(c.config, OpUpdate)
	return &PlanUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PlanClient) UpdateOne(_m *Plan) *PlanUpdateOne {
	mutation := newPlanMutation(c.config, OpUpdateOne, withPlan(_m))
	return &PlanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PlanClient) UpdateOneID(id int) *PlanUpdateOne {
	mutation := newPlanMutation(c.config, OpUpdateOne, withPlanID(id))
	return &PlanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Plan.
func (c *PlanClient) Delete() *PlanDelete {
	mutation := newPlanMutation(c.config, OpDelete)
	return &PlanDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PlanClient) DeleteOne(_m *Plan) *PlanDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PlanClient) DeleteOneID(id int) *PlanDeleteOne {
	builder := c.Delete().Where(plan.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PlanDeleteOne{builder}
}

// Query returns a query builder for Plan.
func (c *PlanClient) Query() *PlanQuery {
	return &PlanQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePlan},
		inters: c.Interceptors(),
	}
}

// Get returns a Plan entity by its id.
func (c *PlanClient) Get(ctx context.Context, id int) (*Plan, error) {
	return c.Query().Where(plan.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PlanClient) GetX(ctx context.Context, id int) *Plan {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFormularyEntries queries the formulary_entries edge of a Plan.
func (c *PlanClient) QueryFormularyEntries(_m *Plan) *FormularyEntryQuery {
	query := (&FormularyEntryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(plan.Table, plan.FieldID, id),
			sqlgraph.To(formularyentry.Table, formularyentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, plan.FormularyEntriesTable, plan.FormularyEntriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PlanClient) Hooks() []Hook {
	return c.hooks.Plan
}

// Interceptors returns the client interceptors.
func (c *PlanClient) Interceptors() []Interceptor {
	return c.inters.Plan
}

func (c *PlanClient) mutate(ctx context.Context, m *PlanMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PlanCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PlanUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PlanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PlanDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Plan mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Drug, DrugNdcMap, FormularyEntry, Plan []ent.Hook
	}
	inters struct {
		Drug, DrugNdcMap, FormularyEntry, Plan []ent.Interceptor
	}
)
