// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/drugndcmap"
)

// DrugNdcMap is the model entity for the DrugNdcMap schema.
type DrugNdcMap struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Ndc holds the value of the "ndc" field.
	Ndc string `json:"ndc,omitempty"`
	// NdcStatus holds the value of the "ndc_status" field.
	NdcStatus string `json:"ndc_status,omitempty"`
	// Manufacturer holds the value of the "manufacturer" field.
	Manufacturer string `json:"manufacturer,omitempty"`
	// PackageDescription holds the value of the "package_description" field.
	PackageDescription string `json:"package_description,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate *time.Time `json:"end_date,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DrugNdcMapQuery when eager-loading is set.
	Edges             DrugNdcMapEdges `json:"edges"`
	drug_ndc_mappings *int
	selectValues      sql.SelectValues
}

// DrugNdcMapEdges holds the relations/edges for other nodes in the graph.
type DrugNdcMapEdges struct {
	// Drug holds the value of the drug edge.
	Drug *Drug `json:"drug,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DrugOrErr returns the Drug value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DrugNdcMapEdges) DrugOrErr() (*Drug, error) {
	if e.Drug != nil {
		return e.Drug, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: drug.Label}
	}
	return nil, &NotLoadedError{edge: "drug"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DrugNdcMap) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case drugndcmap.FieldID:
			values[i] = new(sql.NullInt64)
		case drugndcmap.FieldNdc, drugndcmap.FieldNdcStatus, drugndcmap.FieldManufacturer, drugndcmap.FieldPackageDescription:
			values[i] = new(sql.NullString)
		case drugndcmap.FieldStartDate, drugndcmap.FieldEndDate, drugndcmap.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case drugndcmap.ForeignKeys[0]: // drug_ndc_mappings
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DrugNdcMap fields.
func (_m *DrugNdcMap) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case drugndcmap.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case drugndcmap.FieldNdc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ndc", values[i])
			} else if value.Valid {
				_m.Ndc = value.String
			}
		case drugndcmap.FieldNdcStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ndc_status", values[i])
			} else if value.Valid {
				_m.NdcStatus = value.String
			}
		case drugndcmap.FieldManufacturer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manufacturer", values[i])
			} else if value.Valid {
				_m.Manufacturer = value.String
			}
		case drugndcmap.FieldPackageDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field package_description", values[i])
			} else if value.Valid {
				_m.PackageDescription = value.String
			}
		case drugndcmap.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case drugndcmap.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = new(time.Time)
				*_m.EndDate = value.Time
			}
		case drugndcmap.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case drugndcmap.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field drug_ndc_mappings", value)
			} else if value.Valid {
				_m.drug_ndc_mappings = new(int)
				*_m.drug_ndc_mappings = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DrugNdcMap.
// This includes values selected through modifiers, order, etc.
func (_m *DrugNdcMap) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDrug queries the "drug" edge of the DrugNdcMap entity.
func (_m *DrugNdcMap) QueryDrug() *DrugQuery {
	return NewDrugNdcMapClient(_m.config).QueryDrug(_m)
}

// Update returns a builder for updating this DrugNdcMap.
// Note that you need to call DrugNdcMap.Unwrap() before calling this method if this DrugNdcMap
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DrugNdcMap) Update() *DrugNdcMapUpdateOne {
	return NewDrugNdcMapClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DrugNdcMap entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DrugNdcMap) Unwrap() *DrugNdcMap {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DrugNdcMap is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DrugNdcMap) String() string {
	var builder strings.Builder
	builder.WriteString("DrugNdcMap(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ndc=")
	builder.WriteString(_m.Ndc)
	builder.WriteString(", ")
	builder.WriteString("ndc_status=")
	builder.WriteString(_m.NdcStatus)
	builder.WriteString(", ")
	builder.WriteString("manufacturer=")
	builder.WriteString(_m.Manufacturer)
	builder.WriteString(", ")
	builder.WriteString("package_description=")
	builder.WriteString(_m.PackageDescription)
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DrugNdcMaps is a parsable slice of DrugNdcMap.
type DrugNdcMaps []*DrugNdcMap
