// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kyanaman/formularycheck/ent/drug"
)

// Drug is the model entity for the Drug schema.
type Drug struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Rxcui holds the value of the "rxcui" field.
	Rxcui string `json:"rxcui,omitempty"`
	// DrugName holds the value of the "drug_name" field.
	DrugName string `json:"drug_name,omitempty"`
	// GenericName holds the value of the "generic_name" field.
	GenericName string `json:"generic_name,omitempty"`
	// BrandNames holds the value of the "brand_names" field.
	BrandNames []string `json:"brand_names,omitempty"`
	// DoseForm holds the value of the "dose_form" field.
	DoseForm string `json:"dose_form,omitempty"`
	// Strength holds the value of the "strength" field.
	Strength string `json:"strength,omitempty"`
	// Route holds the value of the "route" field.
	Route string `json:"route,omitempty"`
	// DrugClass holds the value of the "drug_class" field.
	DrugClass string `json:"drug_class,omitempty"`
	// IsSpecialty holds the value of the "is_specialty" field.
	IsSpecialty bool `json:"is_specialty,omitempty"`
	// IsControlled holds the value of the "is_controlled" field.
	IsControlled bool `json:"is_controlled,omitempty"`
	// DeaSchedule holds the value of the "dea_schedule" field.
	DeaSchedule string `json:"dea_schedule,omitempty"`
	// LastRxnormSync holds the value of the "last_rxnorm_sync" field.
	LastRxnormSync time.Time `json:"last_rxnorm_sync,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DrugQuery when eager-loading is set.
	Edges        DrugEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DrugEdges holds the relations/edges for other nodes in the graph.
type DrugEdges struct {
	// NdcMappings holds the value of the ndc_mappings edge.
	NdcMappings []*DrugNdcMap `json:"ndc_mappings,omitempty"`
	// FormularyEntries holds the value of the formulary_entries edge.
	FormularyEntries []*FormularyEntry `json:"formulary_entries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// NdcMappingsOrErr returns the NdcMappings value or an error if the edge
// was not loaded in eager-loading.
func (e DrugEdges) NdcMappingsOrErr() ([]*DrugNdcMap, error) {
	if e.loadedTypes[0] {
		return e.NdcMappings, nil
	}
	return nil, &NotLoadedError{edge: "ndc_mappings"}
}

// FormularyEntriesOrErr returns the FormularyEntries value or an error if the edge
// was not loaded in eager-loading.
func (e DrugEdges) FormularyEntriesOrErr() ([]*FormularyEntry, error) {
	if e.loadedTypes[1] {
		return e.FormularyEntries, nil
	}
	return nil, &NotLoadedError{edge: "formulary_entries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Drug) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case drug.FieldBrandNames:
			values[i] = new([]byte)
		case drug.FieldIsSpecialty, drug.FieldIsControlled:
			values[i] = new(sql.NullBool)
		case drug.FieldID:
			values[i] = new(sql.NullInt64)
		case drug.FieldRxcui, drug.FieldDrugName, drug.FieldGenericName, drug.FieldDoseForm, drug.FieldStrength, drug.FieldRoute, drug.FieldDrugClass, drug.FieldDeaSchedule:
			values[i] = new(sql.NullString)
		case drug.FieldLastRxnormSync, drug.FieldCreatedAt, drug.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Drug fields.
func (_m *Drug) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case drug.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case drug.FieldRxcui:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rxcui", values[i])
			} else if value.Valid {
				_m.Rxcui = value.String
			}
		case drug.FieldDrugName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field drug_name", values[i])
			} else if value.Valid {
				_m.DrugName = value.String
			}
		case drug.FieldGenericName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generic_name", values[i])
			} else if value.Valid {
				_m.GenericName = value.String
			}
		case drug.FieldBrandNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field brand_names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BrandNames); err != nil {
					return fmt.Errorf("unmarshal field brand_names: %w", err)
				}
			}
		case drug.FieldDoseForm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dose_form", values[i])
			} else if value.Valid {
				_m.DoseForm = value.String
			}
		case drug.FieldStrength:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strength", values[i])
			} else if value.Valid {
				_m.Strength = value.String
			}
		case drug.FieldRoute:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route", values[i])
			} else if value.Valid {
				_m.Route = value.String
			}
		case drug.FieldDrugClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field drug_class", values[i])
			} else if value.Valid {
				_m.DrugClass = value.String
			}
		case drug.FieldIsSpecialty:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_specialty", values[i])
			} else if value.Valid {
				_m.IsSpecialty = value.Bool
			}
		case drug.FieldIsControlled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_controlled", values[i])
			} else if value.Valid {
				_m.IsControlled = value.Bool
			}
		case drug.FieldDeaSchedule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dea_schedule", values[i])
			} else if value.Valid {
				_m.DeaSchedule = value.String
			}
		case drug.FieldLastRxnormSync:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_rxnorm_sync", values[i])
			} else if value.Valid {
				_m.LastRxnormSync = value.Time
			}
		case drug.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case drug.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Drug.
// This includes values selected through modifiers, order, etc.
func (_m *Drug) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNdcMappings queries the "ndc_mappings" edge of the Drug entity.
func (_m *Drug) QueryNdcMappings() *DrugNdcMapQuery {
	return NewDrugClient(_m.config).QueryNdcMappings(_m)
}

// QueryFormularyEntries queries the "formulary_entries" edge of the Drug entity.
func (_m *Drug) QueryFormularyEntries() *FormularyEntryQuery {
	return NewDrugClient(_m.config).QueryFormularyEntries(_m)
}

// Update returns a builder for updating this Drug.
// Note that you need to call Drug.Unwrap() before calling this method if this Drug
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Drug) Update() *DrugUpdateOne {
	return NewDrugClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Drug entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Drug) Unwrap() *Drug {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Drug is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Drug) String() string {
	var builder strings.Builder
	builder.WriteString("Drug(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("rxcui=")
	builder.WriteString(_m.Rxcui)
	builder.WriteString(", ")
	builder.WriteString("drug_name=")
	builder.WriteString(_m.DrugName)
	builder.WriteString(", ")
	builder.WriteString("generic_name=")
	builder.WriteString(_m.GenericName)
	builder.WriteString(", ")
	builder.WriteString("brand_names=")
	builder.WriteString(fmt.Sprintf("%v", _m.BrandNames))
	builder.WriteString(", ")
	builder.WriteString("dose_form=")
	builder.WriteString(_m.DoseForm)
	builder.WriteString(", ")
	builder.WriteString("strength=")
	builder.WriteString(_m.Strength)
	builder.WriteString(", ")
	builder.WriteString("route=")
	builder.WriteString(_m.Route)
	builder.WriteString(", ")
	builder.WriteString("drug_class=")
	builder.WriteString(_m.DrugClass)
	builder.WriteString(", ")
	builder.WriteString("is_specialty=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSpecialty))
	builder.WriteString(", ")
	builder.WriteString("is_controlled=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsControlled))
	builder.WriteString(", ")
	builder.WriteString("dea_schedule=")
	builder.WriteString(_m.DeaSchedule)
	builder.WriteString(", ")
	builder.WriteString("last_rxnorm_sync=")
	builder.WriteString(_m.LastRxnormSync.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Drugs is a parsable slice of Drug.
type Drugs []*Drug
