// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/drugndcmap"
)

// DrugNdcMapCreate is the builder for creating a DrugNdcMap entity.
type DrugNdcMapCreate struct {
	config
	mutation *DrugNdcMapMutation
	hooks    []Hook
}

// SetNdc sets the "ndc" field.
func (_c *DrugNdcMapCreate) SetNdc(v string) *DrugNdcMapCreate {
	_c.mutation.SetNdc(v)
	return _c
}

// SetNdcStatus sets the "ndc_status" field.
func (_c *DrugNdcMapCreate) SetNdcStatus(v string) *DrugNdcMapCreate {
	_c.mutation.SetNdcStatus(v)
	return _c
}

// SetManufacturer sets the "manufacturer" field.
func (_c *DrugNdcMapCreate) SetManufacturer(v string) *DrugNdcMapCreate {
	_c.mutation.SetManufacturer(v)
	return _c
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_c *DrugNdcMapCreate) SetNillableManufacturer(v *string) *DrugNdcMapCreate {
	if v != nil {
		_c.SetManufacturer(*v)
	}
	return _c
}

// SetPackageDescription sets the "package_description" field.
func (_c *DrugNdcMapCreate) SetPackageDescription(v string) *DrugNdcMapCreate {
	_c.mutation.SetPackageDescription(v)
	return _c
}

// SetNillablePackageDescription sets the "package_description" field if the given value is not nil.
func (_c *DrugNdcMapCreate) SetNillablePackageDescription(v *string) *DrugNdcMapCreate {
	if v != nil {
		_c.SetPackageDescription(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *DrugNdcMapCreate) SetStartDate(v time.Time) *DrugNdcMapCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *DrugNdcMapCreate) SetNillableStartDate(v *time.Time) *DrugNdcMapCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *DrugNdcMapCreate) SetEndDate(v time.Time) *DrugNdcMapCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *DrugNdcMapCreate) SetNillableEndDate(v *time.Time) *DrugNdcMapCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DrugNdcMapCreate) SetCreatedAt(v time.Time) *DrugNdcMapCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DrugNdcMapCreate) SetNillableCreatedAt(v *time.Time) *DrugNdcMapCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDrugID sets the "drug" edge to the Drug entity by ID.
func (_c *DrugNdcMapCreate) SetDrugID(id int) *DrugNdcMapCreate {
	_c.mutation.SetDrugID(id)
	return _c
}

// SetDrug sets the "drug" edge to the Drug entity.
func (_c *DrugNdcMapCreate) SetDrug(v *Drug) *DrugNdcMapCreate {
	return _c.SetDrugID(v.ID)
}

// Mutation returns the DrugNdcMapMutation object of the builder.
func (_c *DrugNdcMapCreate) Mutation() *DrugNdcMapMutation {
	return _c.mutation
}

// Save creates the DrugNdcMap in the database.
func (_c *DrugNdcMapCreate) Save(ctx context.Context) (*DrugNdcMap, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DrugNdcMapCreate) SaveX(ctx context.Context) *DrugNdcMap {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DrugNdcMapCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DrugNdcMapCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DrugNdcMapCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := drugndcmap.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DrugNdcMapCreate) check() error {
	if _, ok := _c.mutation.Ndc(); !ok {
		return &ValidationError{Name: "ndc", err: errors.New(`ent: missing required field "DrugNdcMap.ndc"`)}
	}
	if v, ok := _c.mutation.Ndc(); ok {
		if err := drugndcmap.NdcValidator(v); err != nil {
			return &ValidationError{Name: "ndc", err: fmt.Errorf(`ent: validator failed for field "DrugNdcMap.ndc": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NdcStatus(); !ok {
		return &ValidationError{Name: "ndc_status", err: errors.New(`ent: missing required field "DrugNdcMap.ndc_status"`)}
	}
	if v, ok := _c.mutation.NdcStatus(); ok {
		if err := drugndcmap.NdcStatusValidator(v); err != nil {
			return &ValidationError{Name: "ndc_status", err: fmt.Errorf(`ent: validator failed for field "DrugNdcMap.ndc_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DrugNdcMap.created_at"`)}
	}
	if len(_c.mutation.DrugIDs()) == 0 {
		return &ValidationError{Name: "drug", err: errors.New(`ent: missing required edge "DrugNdcMap.drug"`)}
	}
	return nil
}

func (_c *DrugNdcMapCreate) sqlSave(ctx context.Context) (*DrugNdcMap, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DrugNdcMapCreate) createSpec() (*DrugNdcMap, *sqlgraph.CreateSpec) {
	var (
		_node = &DrugNdcMap{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(drugndcmap.Table, sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Ndc(); ok {
		_spec.SetField(drugndcmap.FieldNdc, field.TypeString, value)
		_node.Ndc = value
	}
	if value, ok := _c.mutation.NdcStatus(); ok {
		_spec.SetField(drugndcmap.FieldNdcStatus, field.TypeString, value)
		_node.NdcStatus = value
	}
	if value, ok := _c.mutation.Manufacturer(); ok {
		_spec.SetField(drugndcmap.FieldManufacturer, field.TypeString, value)
		_node.Manufacturer = value
	}
	if value, ok := _c.mutation.PackageDescription(); ok {
		_spec.SetField(drugndcmap.FieldPackageDescription, field.TypeString, value)
		_node.PackageDescription = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(drugndcmap.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(drugndcmap.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(drugndcmap.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugndcmap.DrugTable,
			Columns: []string{drugndcmap.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.drug_ndc_mappings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DrugNdcMapCreateBulk is the builder for creating many DrugNdcMap entities in bulk.
type DrugNdcMapCreateBulk struct {
	config
	err      error
	builders []*DrugNdcMapCreate
}

// Save creates the DrugNdcMap entities in the database.
func (_c *DrugNdcMapCreateBulk) Save(ctx context.Context) ([]*DrugNdcMap, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DrugNdcMap, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DrugNdcMapMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DrugNdcMapCreateBulk) SaveX(ctx context.Context) []*DrugNdcMap {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DrugNdcMapCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DrugNdcMapCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
