// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/drugndcmap"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
)

// DrugCreate is the builder for creating a Drug entity.
type DrugCreate struct {
	config
	mutation *DrugMutation
	hooks    []Hook
}

// SetRxcui sets the "rxcui" field.
func (_c *DrugCreate) SetRxcui(v string) *DrugCreate {
	_c.mutation.SetRxcui(v)
	return _c
}

// SetDrugName sets the "drug_name" field.
func (_c *DrugCreate) SetDrugName(v string) *DrugCreate {
	_c.mutation.SetDrugName(v)
	return _c
}

// SetGenericName sets the "generic_name" field.
func (_c *DrugCreate) SetGenericName(v string) *DrugCreate {
	_c.mutation.SetGenericName(v)
	return _c
}

// SetNillableGenericName sets the "generic_name" field if the given value is not nil.
func (_c *DrugCreate) SetNillableGenericName(v *string) *DrugCreate {
	if v != nil {
		_c.SetGenericName(*v)
	}
	return _c
}

// SetBrandNames sets the "brand_names" field.
func (_c *DrugCreate) SetBrandNames(v []string) *DrugCreate {
	_c.mutation.SetBrandNames(v)
	return _c
}

// SetDoseForm sets the "dose_form" field.
func (_c *DrugCreate) SetDoseForm(v string) *DrugCreate {
	_c.mutation.SetDoseForm(v)
	return _c
}

// SetNillableDoseForm sets the "dose_form" field if the given value is not nil.
func (_c *DrugCreate) SetNillableDoseForm(v *string) *DrugCreate {
	if v != nil {
		_c.SetDoseForm(*v)
	}
	return _c
}

// SetStrength sets the "strength" field.
func (_c *DrugCreate) SetStrength(v string) *DrugCreate {
	_c.mutation.SetStrength(v)
	return _c
}

// SetNillableStrength sets the "strength" field if the given value is not nil.
func (_c *DrugCreate) SetNillableStrength(v *string) *DrugCreate {
	if v != nil {
		_c.SetStrength(*v)
	}
	return _c
}

// SetRoute sets the "route" field.
func (_c *DrugCreate) SetRoute(v string) *DrugCreate {
	_c.mutation.SetRoute(v)
	return _c
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (_c *DrugCreate) SetNillableRoute(v *string) *DrugCreate {
	if v != nil {
		_c.SetRoute(*v)
	}
	return _c
}

// SetDrugClass sets the "drug_class" field.
func (_c *DrugCreate) SetDrugClass(v string) *DrugCreate {
	_c.mutation.SetDrugClass(v)
	return _c
}

// SetNillableDrugClass sets the "drug_class" field if the given value is not nil.
func (_c *DrugCreate) SetNillableDrugClass(v *string) *DrugCreate {
	if v != nil {
		_c.SetDrugClass(*v)
	}
	return _c
}

// SetIsSpecialty sets the "is_specialty" field.
func (_c *DrugCreate) SetIsSpecialty(v bool) *DrugCreate {
	_c.mutation.SetIsSpecialty(v)
	return _c
}

// SetNillableIsSpecialty sets the "is_specialty" field if the given value is not nil.
func (_c *DrugCreate) SetNillableIsSpecialty(v *bool) *DrugCreate {
	if v != nil {
		_c.SetIsSpecialty(*v)
	}
	return _c
}

// SetIsControlled sets the "is_controlled" field.
func (_c *DrugCreate) SetIsControlled(v bool) *DrugCreate {
	_c.mutation.SetIsControlled(v)
	return _c
}

// SetNillableIsControlled sets the "is_controlled" field if the given value is not nil.
func (_c *DrugCreate) SetNillableIsControlled(v *bool) *DrugCreate {
	if v != nil {
		_c.SetIsControlled(*v)
	}
	return _c
}

// SetDeaSchedule sets the "dea_schedule" field.
func (_c *DrugCreate) SetDeaSchedule(v string) *DrugCreate {
	_c.mutation.SetDeaSchedule(v)
	return _c
}

// SetNillableDeaSchedule sets the "dea_schedule" field if the given value is not nil.
func (_c *DrugCreate) SetNillableDeaSchedule(v *string) *DrugCreate {
	if v != nil {
		_c.SetDeaSchedule(*v)
	}
	return _c
}

// SetLastRxnormSync sets the "last_rxnorm_sync" field.
func (_c *DrugCreate) SetLastRxnormSync(v time.Time) *DrugCreate {
	_c.mutation.SetLastRxnormSync(v)
	return _c
}

// SetNillableLastRxnormSync sets the "last_rxnorm_sync" field if the given value is not nil.
func (_c *DrugCreate) SetNillableLastRxnormSync(v *time.Time) *DrugCreate {
	if v != nil {
		_c.SetLastRxnormSync(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DrugCreate) SetCreatedAt(v time.Time) *DrugCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DrugCreate) SetNillableCreatedAt(v *time.Time) *DrugCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DrugCreate) SetUpdatedAt(v time.Time) *DrugCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DrugCreate) SetNillableUpdatedAt(v *time.Time) *DrugCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddNdcMappingIDs adds the "ndc_mappings" edge to the DrugNdcMap entity by IDs.
func (_c *DrugCreate) AddNdcMappingIDs(ids ...int) *DrugCreate {
	_c.mutation.AddNdcMappingIDs(ids...)
	return _c
}

// AddNdcMappings adds the "ndc_mappings" edges to the DrugNdcMap entity.
func (_c *DrugCreate) AddNdcMappings(v ...*DrugNdcMap) *DrugCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNdcMappingIDs(ids...)
}

// AddFormularyEntryIDs adds the "formulary_entries" edge to the FormularyEntry entity by IDs.
func (_c *DrugCreate) AddFormularyEntryIDs(ids ...int) *DrugCreate {
	_c.mutation.AddFormularyEntryIDs(ids...)
	return _c
}

// AddFormularyEntries adds the "formulary_entries" edges to the FormularyEntry entity.
func (_c *DrugCreate) AddFormularyEntries(v ...*FormularyEntry) *DrugCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFormularyEntryIDs(ids...)
}

// Mutation returns the DrugMutation object of the builder.
func (_c *DrugCreate) Mutation() *DrugMutation {
	return _c.mutation
}

// Save creates the Drug in the database.
func (_c *DrugCreate) Save(ctx context.Context) (*Drug, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DrugCreate) SaveX(ctx context.Context) *Drug {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DrugCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DrugCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DrugCreate) defaults() {
	if _, ok := _c.mutation.IsSpecialty(); !ok {
		v := drug.DefaultIsSpecialty
		_c.mutation.SetIsSpecialty(v)
	}
	if _, ok := _c.mutation.IsControlled(); !ok {
		v := drug.DefaultIsControlled
		_c.mutation.SetIsControlled(v)
	}
	if _, ok := _c.mutation.LastRxnormSync(); !ok {
		v := drug.DefaultLastRxnormSync()
		_c.mutation.SetLastRxnormSync(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := drug.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := drug.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DrugCreate) check() error {
	if _, ok := _c.mutation.Rxcui(); !ok {
		return &ValidationError{Name: "rxcui", err: errors.New(`ent: missing required field "Drug.rxcui"`)}
	}
	if v, ok := _c.mutation.Rxcui(); ok {
		if err := drug.RxcuiValidator(v); err != nil {
			return &ValidationError{Name: "rxcui", err: fmt.Errorf(`ent: validator failed for field "Drug.rxcui": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DrugName(); !ok {
		return &ValidationError{Name: "drug_name", err: errors.New(`ent: missing required field "Drug.drug_name"`)}
	}
	if v, ok := _c.mutation.DrugName(); ok {
		if err := drug.DrugNameValidator(v); err != nil {
			return &ValidationError{Name: "drug_name", err: fmt.Errorf(`ent: validator failed for field "Drug.drug_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSpecialty(); !ok {
		return &ValidationError{Name: "is_specialty", err: errors.New(`ent: missing required field "Drug.is_specialty"`)}
	}
	if _, ok := _c.mutation.IsControlled(); !ok {
		return &ValidationError{Name: "is_controlled", err: errors.New(`ent: missing required field "Drug.is_controlled"`)}
	}
	if _, ok := _c.mutation.LastRxnormSync(); !ok {
		return &ValidationError{Name: "last_rxnorm_sync", err: errors.New(`ent: missing required field "Drug.last_rxnorm_sync"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Drug.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Drug.updated_at"`)}
	}
	return nil
}

func (_c *DrugCreate) sqlSave(ctx context.Context) (*Drug, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DrugCreate) createSpec() (*Drug, *sqlgraph.CreateSpec) {
	var (
		_node = &Drug{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(drug.Table, sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Rxcui(); ok {
		_spec.SetField(drug.FieldRxcui, field.TypeString, value)
		_node.Rxcui = value
	}
	if value, ok := _c.mutation.DrugName(); ok {
		_spec.SetField(drug.FieldDrugName, field.TypeString, value)
		_node.DrugName = value
	}
	if value, ok := _c.mutation.GenericName(); ok {
		_spec.SetField(drug.FieldGenericName, field.TypeString, value)
		_node.GenericName = value
	}
	if value, ok := _c.mutation.BrandNames(); ok {
		_spec.SetField(drug.FieldBrandNames, field.TypeJSON, value)
		_node.BrandNames = value
	}
	if value, ok := _c.mutation.DoseForm(); ok {
		_spec.SetField(drug.FieldDoseForm, field.TypeString, value)
		_node.DoseForm = value
	}
	if value, ok := _c.mutation.Strength(); ok {
		_spec.SetField(drug.FieldStrength, field.TypeString, value)
		_node.Strength = value
	}
	if value, ok := _c.mutation.Route(); ok {
		_spec.SetField(drug.FieldRoute, field.TypeString, value)
		_node.Route = value
	}
	if value, ok := _c.mutation.DrugClass(); ok {
		_spec.SetField(drug.FieldDrugClass, field.TypeString, value)
		_node.DrugClass = value
	}
	if value, ok := _c.mutation.IsSpecialty(); ok {
		_spec.SetField(drug.FieldIsSpecialty, field.TypeBool, value)
		_node.IsSpecialty = value
	}
	if value, ok := _c.mutation.IsControlled(); ok {
		_spec.SetField(drug.FieldIsControlled, field.TypeBool, value)
		_node.IsControlled = value
	}
	if value, ok := _c.mutation.DeaSchedule(); ok {
		_spec.SetField(drug.FieldDeaSchedule, field.TypeString, value)
		_node.DeaSchedule = value
	}
	if value, ok := _c.mutation.LastRxnormSync(); ok {
		_spec.SetField(drug.FieldLastRxnormSync, field.TypeTime, value)
		_node.LastRxnormSync = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(drug.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(drug.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.NdcMappingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.NdcMappingsTable,
			Columns: []string{drug.NdcMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FormularyEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.FormularyEntriesTable,
			Columns: []string{drug.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DrugCreateBulk is the builder for creating many Drug entities in bulk.
type DrugCreateBulk struct {
	config
	err      error
	builders []*DrugCreate
}

// Save creates the Drug entities in the database.
func (_c *DrugCreateBulk) Save(ctx context.Context) ([]*Drug, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Drug, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DrugMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DrugCreateBulk) SaveX(ctx context.Context) []*Drug {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DrugCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DrugCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
