// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/drugndcmap"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// DrugQuery is the builder for querying Drug entities.
type DrugQuery struct {
	config
	ctx                  *QueryContext
	order                []drug.OrderOption
	inters               []Interceptor
	predicates           []predicate.Drug
	withNdcMappings      *DrugNdcMapQuery
	withFormularyEntries *FormularyEntryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DrugQuery builder.
func (_q *DrugQuery) Where(ps ...predicate.Drug) *DrugQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DrugQuery) Limit(limit int) *DrugQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DrugQuery) Offset(offset int) *DrugQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DrugQuery) Unique(unique bool) *DrugQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DrugQuery) Order(o ...drug.OrderOption) *DrugQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryNdcMappings chains the current query on the "ndc_mappings" edge.
func (_q *DrugQuery) QueryNdcMappings() *DrugNdcMapQuery {
	query := (&DrugNdcMapClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(drug.Table, drug.FieldID, selector),
			sqlgraph.To(drugndcmap.Table, drugndcmap.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, drug.NdcMappingsTable, drug.NdcMappingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFormularyEntries chains the current query on the "formulary_entries" edge.
func (_q *DrugQuery) QueryFormularyEntries() *FormularyEntryQuery {
	query := (&FormularyEntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(drug.Table, drug.FieldID, selector),
			sqlgraph.To(formularyentry.Table, formularyentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, drug.FormularyEntriesTable, drug.FormularyEntriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Drug entity from the query.
// Returns a *NotFoundError when no Drug was found.
func (_q *DrugQuery) First(ctx context.Context) (*Drug, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{drug.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DrugQuery) FirstX(ctx context.Context) *Drug {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Drug ID from the query.
// Returns a *NotFoundError when no Drug ID was found.
func (_q *DrugQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{drug.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DrugQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Drug entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Drug entity is found.
// Returns a *NotFoundError when no Drug entities are found.
func (_q *DrugQuery) Only(ctx context.Context) (*Drug, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{drug.Label}
	default:
		return nil, &NotSingularError{drug.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DrugQuery) OnlyX(ctx context.Context) *Drug {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Drug ID in the query.
// Returns a *NotSingularError when more than one Drug ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DrugQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{drug.Label}
	default:
		err = &NotSingularError{drug.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DrugQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Drugs.
func (_q *DrugQuery) All(ctx context.Context) ([]*Drug, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Drug, *DrugQuery]()
	return withInterceptors[[]*Drug](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DrugQuery) AllX(ctx context.Context) []*Drug {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Drug IDs.
func (_q *DrugQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(drug.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DrugQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DrugQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DrugQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DrugQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DrugQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DrugQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DrugQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DrugQuery) Clone() *DrugQuery {
	if _q == nil {
		return nil
	}
	return &DrugQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]drug.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.Drug{}, _q.predicates...),
		withNdcMappings:      _q.withNdcMappings.Clone(),
		withFormularyEntries: _q.withFormularyEntries.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithNdcMappings tells the query-builder to eager-load the nodes that are connected to
// the "ndc_mappings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DrugQuery) WithNdcMappings(opts ...func(*DrugNdcMapQuery)) *DrugQuery {
	query := (&DrugNdcMapClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNdcMappings = query
	return _q
}

// WithFormularyEntries tells the query-builder to eager-load the nodes that are connected to
// the "formulary_entries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DrugQuery) WithFormularyEntries(opts ...func(*FormularyEntryQuery)) *DrugQuery {
	query := (&FormularyEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFormularyEntries = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Rxcui string `json:"rxcui,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Drug.Query().
//		GroupBy(drug.FieldRxcui).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DrugQuery) GroupBy(field string, fields ...string) *DrugGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DrugGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = drug.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Rxcui string `json:"rxcui,omitempty"`
//	}
//
//	client.Drug.Query().
//		Select(drug.FieldRxcui).
//		Scan(ctx, &v)
func (_q *DrugQuery) Select(fields ...string) *DrugSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DrugSelect{DrugQuery: _q}
	sbuild.label = drug.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DrugSelect configured with the given aggregations.
func (_q *DrugQuery) Aggregate(fns ...AggregateFunc) *DrugSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DrugQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !drug.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DrugQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Drug, error) {
	var (
		nodes       = []*Drug{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withNdcMappings != nil,
			_q.withFormularyEntries != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Drug).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Drug{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withNdcMappings; query != nil {
		if err := _q.loadNdcMappings(ctx, query, nodes,
			func(n *Drug) { n.Edges.NdcMappings = []*DrugNdcMap{} },
			func(n *Drug, e *DrugNdcMap) { n.Edges.NdcMappings = append(n.Edges.NdcMappings, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFormularyEntries; query != nil {
		if err := _q.loadFormularyEntries(ctx, query, nodes,
			func(n *Drug) { n.Edges.FormularyEntries = []*FormularyEntry{} },
			func(n *Drug, e *FormularyEntry) { n.Edges.FormularyEntries = append(n.Edges.FormularyEntries, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DrugQuery) loadNdcMappings(ctx context.Context, query *DrugNdcMapQuery, nodes []*Drug, init func(*Drug), assign func(*Drug, *DrugNdcMap)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Drug)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DrugNdcMap(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(drug.NdcMappingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.drug_ndc_mappings
		if fk == nil {
			return fmt.Errorf(`foreign-key "drug_ndc_mappings" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "drug_ndc_mappings" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DrugQuery) loadFormularyEntries(ctx context.Context, query *FormularyEntryQuery, nodes []*Drug, init func(*Drug), assign func(*Drug, *FormularyEntry)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Drug)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.FormularyEntry(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(drug.FormularyEntriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.drug_formulary_entries
		if fk == nil {
			return fmt.Errorf(`foreign-key "drug_formulary_entries" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "drug_formulary_entries" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DrugQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DrugQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(drug.Table, drug.Columns, sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drug.FieldID)
		for i := range fields {
			if fields[i] != drug.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DrugQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(drug.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = drug.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DrugGroupBy is the group-by builder for Drug entities.
type DrugGroupBy struct {
	selector
	build *DrugQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DrugGroupBy) Aggregate(fns ...AggregateFunc) *DrugGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DrugGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DrugQuery, *DrugGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DrugGroupBy) sqlScan(ctx context.Context, root *DrugQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DrugSelect is the builder for selecting fields of Drug entities.
type DrugSelect struct {
	*DrugQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DrugSelect) Aggregate(fns ...AggregateFunc) *DrugSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DrugSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DrugQuery, *DrugSelect](ctx, _s.DrugQuery, _s, _s.inters, v)
}

func (_s *DrugSelect) sqlScan(ctx context.Context, root *DrugQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
