// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/drugndcmap"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// DrugNdcMapUpdate is the builder for updating DrugNdcMap entities.
type DrugNdcMapUpdate struct {
	config
	hooks    []Hook
	mutation *DrugNdcMapMutation
}

// Where appends a list predicates to the DrugNdcMapUpdate builder.
func (_u *DrugNdcMapUpdate) Where(ps ...predicate.DrugNdcMap) *DrugNdcMapUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNdc sets the "ndc" field.
func (_u *DrugNdcMapUpdate) SetNdc(v string) *DrugNdcMapUpdate {
	_u.mutation.SetNdc(v)
	return _u
}

// SetNillableNdc sets the "ndc" field if the given value is not nil.
func (_u *DrugNdcMapUpdate) SetNillableNdc(v *string) *DrugNdcMapUpdate {
	if v != nil {
		_u.SetNdc(*v)
	}
	return _u
}

// SetNdcStatus sets the "ndc_status" field.
func (_u *DrugNdcMapUpdate) SetNdcStatus(v string) *DrugNdcMapUpdate {
	_u.mutation.SetNdcStatus(v)
	return _u
}

// SetNillableNdcStatus sets the "ndc_status" field if the given value is not nil.
func (_u *DrugNdcMapUpdate) SetNillableNdcStatus(v *string) *DrugNdcMapUpdate {
	if v != nil {
		_u.SetNdcStatus(*v)
	}
	return _u
}

// SetManufacturer sets the "manufacturer" field.
func (_u *DrugNdcMapUpdate) SetManufacturer(v string) *DrugNdcMapUpdate {
	_u.mutation.SetManufacturer(v)
	return _u
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_u *DrugNdcMapUpdate) SetNillableManufacturer(v *string) *DrugNdcMapUpdate {
	if v != nil {
		_u.SetManufacturer(*v)
	}
	return _u
}

// ClearManufacturer clears the value of the "manufacturer" field.
func (_u *DrugNdcMapUpdate) ClearManufacturer() *DrugNdcMapUpdate {
	_u.mutation.ClearManufacturer()
	return _u
}

// SetPackageDescription sets the "package_description" field.
func (_u *DrugNdcMapUpdate) SetPackageDescription(v string) *DrugNdcMapUpdate {
	_u.mutation.SetPackageDescription(v)
	return _u
}

// SetNillablePackageDescription sets the "package_description" field if the given value is not nil.
func (_u *DrugNdcMapUpdate) SetNillablePackageDescription(v *string) *DrugNdcMapUpdate {
	if v != nil {
		_u.SetPackageDescription(*v)
	}
	return _u
}

// ClearPackageDescription clears the value of the "package_description" field.
func (_u *DrugNdcMapUpdate) ClearPackageDescription() *DrugNdcMapUpdate {
	_u.mutation.ClearPackageDescription()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *DrugNdcMapUpdate) SetStartDate(v time.Time) *DrugNdcMapUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *DrugNdcMapUpdate) SetNillableStartDate(v *time.Time) *DrugNdcMapUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *DrugNdcMapUpdate) ClearStartDate() *DrugNdcMapUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *DrugNdcMapUpdate) SetEndDate(v time.Time) *DrugNdcMapUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *DrugNdcMapUpdate) SetNillableEndDate(v *time.Time) *DrugNdcMapUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *DrugNdcMapUpdate) ClearEndDate() *DrugNdcMapUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetDrugID sets the "drug" edge to the Drug entity by ID.
func (_u *DrugNdcMapUpdate) SetDrugID(id int) *DrugNdcMapUpdate {
	_u.mutation.SetDrugID(id)
	return _u
}

// SetDrug sets the "drug" edge to the Drug entity.
func (_u *DrugNdcMapUpdate) SetDrug(v *Drug) *DrugNdcMapUpdate {
	return _u.SetDrugID(v.ID)
}

// Mutation returns the DrugNdcMapMutation object of the builder.
func (_u *DrugNdcMapUpdate) Mutation() *DrugNdcMapMutation {
	return _u.mutation
}

// ClearDrug clears the "drug" edge to the Drug entity.
func (_u *DrugNdcMapUpdate) ClearDrug() *DrugNdcMapUpdate {
	_u.mutation.ClearDrug()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DrugNdcMapUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DrugNdcMapUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DrugNdcMapUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DrugNdcMapUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DrugNdcMapUpdate) check() error {
	if v, ok := _u.mutation.Ndc(); ok {
		if err := drugndcmap.NdcValidator(v); err != nil {
			return &ValidationError{Name: "ndc", err: fmt.Errorf(`ent: validator failed for field "DrugNdcMap.ndc": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NdcStatus(); ok {
		if err := drugndcmap.NdcStatusValidator(v); err != nil {
			return &ValidationError{Name: "ndc_status", err: fmt.Errorf(`ent: validator failed for field "DrugNdcMap.ndc_status": %w`, err)}
		}
	}
	if _u.mutation.DrugCleared() && len(_u.mutation.DrugIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DrugNdcMap.drug"`)
	}
	return nil
}

func (_u *DrugNdcMapUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drugndcmap.Table, drugndcmap.Columns, sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ndc(); ok {
		_spec.SetField(drugndcmap.FieldNdc, field.TypeString, value)
	}
	if value, ok := _u.mutation.NdcStatus(); ok {
		_spec.SetField(drugndcmap.FieldNdcStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Manufacturer(); ok {
		_spec.SetField(drugndcmap.FieldManufacturer, field.TypeString, value)
	}
	if _u.mutation.ManufacturerCleared() {
		_spec.ClearField(drugndcmap.FieldManufacturer, field.TypeString)
	}
	if value, ok := _u.mutation.PackageDescription(); ok {
		_spec.SetField(drugndcmap.FieldPackageDescription, field.TypeString, value)
	}
	if _u.mutation.PackageDescriptionCleared() {
		_spec.ClearField(drugndcmap.FieldPackageDescription, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(drugndcmap.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(drugndcmap.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(drugndcmap.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(drugndcmap.FieldEndDate, field.TypeTime)
	}
	if _u.mutation.DrugCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugndcmap.DrugTable,
			Columns: []string{drugndcmap.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugndcmap.DrugTable,
			Columns: []string{drugndcmap.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drugndcmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DrugNdcMapUpdateOne is the builder for updating a single DrugNdcMap entity.
type DrugNdcMapUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DrugNdcMapMutation
}

// SetNdc sets the "ndc" field.
func (_u *DrugNdcMapUpdateOne) SetNdc(v string) *DrugNdcMapUpdateOne {
	_u.mutation.SetNdc(v)
	return _u
}

// SetNillableNdc sets the "ndc" field if the given value is not nil.
func (_u *DrugNdcMapUpdateOne) SetNillableNdc(v *string) *DrugNdcMapUpdateOne {
	if v != nil {
		_u.SetNdc(*v)
	}
	return _u
}

// SetNdcStatus sets the "ndc_status" field.
func (_u *DrugNdcMapUpdateOne) SetNdcStatus(v string) *DrugNdcMapUpdateOne {
	_u.mutation.SetNdcStatus(v)
	return _u
}

// SetNillableNdcStatus sets the "ndc_status" field if the given value is not nil.
func (_u *DrugNdcMapUpdateOne) SetNillableNdcStatus(v *string) *DrugNdcMapUpdateOne {
	if v != nil {
		_u.SetNdcStatus(*v)
	}
	return _u
}

// SetManufacturer sets the "manufacturer" field.
func (_u *DrugNdcMapUpdateOne) SetManufacturer(v string) *DrugNdcMapUpdateOne {
	_u.mutation.SetManufacturer(v)
	return _u
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_u *DrugNdcMapUpdateOne) SetNillableManufacturer(v *string) *DrugNdcMapUpdateOne {
	if v != nil {
		_u.SetManufacturer(*v)
	}
	return _u
}

// ClearManufacturer clears the value of the "manufacturer" field.
func (_u *DrugNdcMapUpdateOne) ClearManufacturer() *DrugNdcMapUpdateOne {
	_u.mutation.ClearManufacturer()
	return _u
}

// SetPackageDescription sets the "package_description" field.
func (_u *DrugNdcMapUpdateOne) SetPackageDescription(v string) *DrugNdcMapUpdateOne {
	_u.mutation.SetPackageDescription(v)
	return _u
}

// SetNillablePackageDescription sets the "package_description" field if the given value is not nil.
func (_u *DrugNdcMapUpdateOne) SetNillablePackageDescription(v *string) *DrugNdcMapUpdateOne {
	if v != nil {
		_u.SetPackageDescription(*v)
	}
	return _u
}

// ClearPackageDescription clears the value of the "package_description" field.
func (_u *DrugNdcMapUpdateOne) ClearPackageDescription() *DrugNdcMapUpdateOne {
	_u.mutation.ClearPackageDescription()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *DrugNdcMapUpdateOne) SetStartDate(v time.Time) *DrugNdcMapUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *DrugNdcMapUpdateOne) SetNillableStartDate(v *time.Time) *DrugNdcMapUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *DrugNdcMapUpdateOne) ClearStartDate() *DrugNdcMapUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *DrugNdcMapUpdateOne) SetEndDate(v time.Time) *DrugNdcMapUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *DrugNdcMapUpdateOne) SetNillableEndDate(v *time.Time) *DrugNdcMapUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *DrugNdcMapUpdateOne) ClearEndDate() *DrugNdcMapUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetDrugID sets the "drug" edge to the Drug entity by ID.
func (_u *DrugNdcMapUpdateOne) SetDrugID(id int) *DrugNdcMapUpdateOne {
	_u.mutation.SetDrugID(id)
	return _u
}

// SetDrug sets the "drug" edge to the Drug entity.
func (_u *DrugNdcMapUpdateOne) SetDrug(v *Drug) *DrugNdcMapUpdateOne {
	return _u.SetDrugID(v.ID)
}

// Mutation returns the DrugNdcMapMutation object of the builder.
func (_u *DrugNdcMapUpdateOne) Mutation() *DrugNdcMapMutation {
	return _u.mutation
}

// ClearDrug clears the "drug" edge to the Drug entity.
func (_u *DrugNdcMapUpdateOne) ClearDrug() *DrugNdcMapUpdateOne {
	_u.mutation.ClearDrug()
	return _u
}

// Where appends a list predicates to the DrugNdcMapUpdate builder.
func (_u *DrugNdcMapUpdateOne) Where(ps ...predicate.DrugNdcMap) *DrugNdcMapUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DrugNdcMapUpdateOne) Select(field string, fields ...string) *DrugNdcMapUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DrugNdcMap entity.
func (_u *DrugNdcMapUpdateOne) Save(ctx context.Context) (*DrugNdcMap, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DrugNdcMapUpdateOne) SaveX(ctx context.Context) *DrugNdcMap {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DrugNdcMapUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DrugNdcMapUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DrugNdcMapUpdateOne) check() error {
	if v, ok := _u.mutation.Ndc(); ok {
		if err := drugndcmap.NdcValidator(v); err != nil {
			return &ValidationError{Name: "ndc", err: fmt.Errorf(`ent: validator failed for field "DrugNdcMap.ndc": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NdcStatus(); ok {
		if err := drugndcmap.NdcStatusValidator(v); err != nil {
			return &ValidationError{Name: "ndc_status", err: fmt.Errorf(`ent: validator failed for field "DrugNdcMap.ndc_status": %w`, err)}
		}
	}
	if _u.mutation.DrugCleared() && len(_u.mutation.DrugIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DrugNdcMap.drug"`)
	}
	return nil
}

func (_u *DrugNdcMapUpdateOne) sqlSave(ctx context.Context) (_node *DrugNdcMap, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drugndcmap.Table, drugndcmap.Columns, sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DrugNdcMap.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drugndcmap.FieldID)
		for _, f := range fields {
			if !drugndcmap.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != drugndcmap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ndc(); ok {
		_spec.SetField(drugndcmap.FieldNdc, field.TypeString, value)
	}
	if value, ok := _u.mutation.NdcStatus(); ok {
		_spec.SetField(drugndcmap.FieldNdcStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Manufacturer(); ok {
		_spec.SetField(drugndcmap.FieldManufacturer, field.TypeString, value)
	}
	if _u.mutation.ManufacturerCleared() {
		_spec.ClearField(drugndcmap.FieldManufacturer, field.TypeString)
	}
	if value, ok := _u.mutation.PackageDescription(); ok {
		_spec.SetField(drugndcmap.FieldPackageDescription, field.TypeString, value)
	}
	if _u.mutation.PackageDescriptionCleared() {
		_spec.ClearField(drugndcmap.FieldPackageDescription, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(drugndcmap.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(drugndcmap.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(drugndcmap.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(drugndcmap.FieldEndDate, field.TypeTime)
	}
	if _u.mutation.DrugCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugndcmap.DrugTable,
			Columns: []string{drugndcmap.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drugndcmap.DrugTable,
			Columns: []string{drugndcmap.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DrugNdcMap{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drugndcmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
