// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/drugndcmap"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// DrugUpdate is the builder for updating Drug entities.
type DrugUpdate struct {
	config
	hooks    []Hook
	mutation *DrugMutation
}

// Where appends a list predicates to the DrugUpdate builder.
func (_u *DrugUpdate) Where(ps ...predicate.Drug) *DrugUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRxcui sets the "rxcui" field.
func (_u *DrugUpdate) SetRxcui(v string) *DrugUpdate {
	_u.mutation.SetRxcui(v)
	return _u
}

// SetNillableRxcui sets the "rxcui" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableRxcui(v *string) *DrugUpdate {
	if v != nil {
		_u.SetRxcui(*v)
	}
	return _u
}

// SetDrugName sets the "drug_name" field.
func (_u *DrugUpdate) SetDrugName(v string) *DrugUpdate {
	_u.mutation.SetDrugName(v)
	return _u
}

// SetNillableDrugName sets the "drug_name" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableDrugName(v *string) *DrugUpdate {
	if v != nil {
		_u.SetDrugName(*v)
	}
	return _u
}

// SetGenericName sets the "generic_name" field.
func (_u *DrugUpdate) SetGenericName(v string) *DrugUpdate {
	_u.mutation.SetGenericName(v)
	return _u
}

// SetNillableGenericName sets the "generic_name" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableGenericName(v *string) *DrugUpdate {
	if v != nil {
		_u.SetGenericName(*v)
	}
	return _u
}

// ClearGenericName clears the value of the "generic_name" field.
func (_u *DrugUpdate) ClearGenericName() *DrugUpdate {
	_u.mutation.ClearGenericName()
	return _u
}

// SetBrandNames sets the "brand_names" field.
func (_u *DrugUpdate) SetBrandNames(v []string) *DrugUpdate {
	_u.mutation.SetBrandNames(v)
	return _u
}

// AppendBrandNames appends value to the "brand_names" field.
func (_u *DrugUpdate) AppendBrandNames(v []string) *DrugUpdate {
	_u.mutation.AppendBrandNames(v)
	return _u
}

// ClearBrandNames clears the value of the "brand_names" field.
func (_u *DrugUpdate) ClearBrandNames() *DrugUpdate {
	_u.mutation.ClearBrandNames()
	return _u
}

// SetDoseForm sets the "dose_form" field.
func (_u *DrugUpdate) SetDoseForm(v string) *DrugUpdate {
	_u.mutation.SetDoseForm(v)
	return _u
}

// SetNillableDoseForm sets the "dose_form" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableDoseForm(v *string) *DrugUpdate {
	if v != nil {
		_u.SetDoseForm(*v)
	}
	return _u
}

// ClearDoseForm clears the value of the "dose_form" field.
func (_u *DrugUpdate) ClearDoseForm() *DrugUpdate {
	_u.mutation.ClearDoseForm()
	return _u
}

// SetStrength sets the "strength" field.
func (_u *DrugUpdate) SetStrength(v string) *DrugUpdate {
	_u.mutation.SetStrength(v)
	return _u
}

// SetNillableStrength sets the "strength" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableStrength(v *string) *DrugUpdate {
	if v != nil {
		_u.SetStrength(*v)
	}
	return _u
}

// ClearStrength clears the value of the "strength" field.
func (_u *DrugUpdate) ClearStrength() *DrugUpdate {
	_u.mutation.ClearStrength()
	return _u
}

// SetRoute sets the "route" field.
func (_u *DrugUpdate) SetRoute(v string) *DrugUpdate {
	_u.mutation.SetRoute(v)
	return _u
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableRoute(v *string) *DrugUpdate {
	if v != nil {
		_u.SetRoute(*v)
	}
	return _u
}

// ClearRoute clears the value of the "route" field.
func (_u *DrugUpdate) ClearRoute() *DrugUpdate {
	_u.mutation.ClearRoute()
	return _u
}

// SetDrugClass sets the "drug_class" field.
func (_u *DrugUpdate) SetDrugClass(v string) *DrugUpdate {
	_u.mutation.SetDrugClass(v)
	return _u
}

// SetNillableDrugClass sets the "drug_class" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableDrugClass(v *string) *DrugUpdate {
	if v != nil {
		_u.SetDrugClass(*v)
	}
	return _u
}

// ClearDrugClass clears the value of the "drug_class" field.
func (_u *DrugUpdate) ClearDrugClass() *DrugUpdate {
	_u.mutation.ClearDrugClass()
	return _u
}

// SetIsSpecialty sets the "is_specialty" field.
func (_u *DrugUpdate) SetIsSpecialty(v bool) *DrugUpdate {
	_u.mutation.SetIsSpecialty(v)
	return _u
}

// SetNillableIsSpecialty sets the "is_specialty" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableIsSpecialty(v *bool) *DrugUpdate {
	if v != nil {
		_u.SetIsSpecialty(*v)
	}
	return _u
}

// SetIsControlled sets the "is_controlled" field.
func (_u *DrugUpdate) SetIsControlled(v bool) *DrugUpdate {
	_u.mutation.SetIsControlled(v)
	return _u
}

// SetNillableIsControlled sets the "is_controlled" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableIsControlled(v *bool) *DrugUpdate {
	if v != nil {
		_u.SetIsControlled(*v)
	}
	return _u
}

// SetDeaSchedule sets the "dea_schedule" field.
func (_u *DrugUpdate) SetDeaSchedule(v string) *DrugUpdate {
	_u.mutation.SetDeaSchedule(v)
	return _u
}

// SetNillableDeaSchedule sets the "dea_schedule" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableDeaSchedule(v *string) *DrugUpdate {
	if v != nil {
		_u.SetDeaSchedule(*v)
	}
	return _u
}

// ClearDeaSchedule clears the value of the "dea_schedule" field.
func (_u *DrugUpdate) ClearDeaSchedule() *DrugUpdate {
	_u.mutation.ClearDeaSchedule()
	return _u
}

// SetLastRxnormSync sets the "last_rxnorm_sync" field.
func (_u *DrugUpdate) SetLastRxnormSync(v time.Time) *DrugUpdate {
	_u.mutation.SetLastRxnormSync(v)
	return _u
}

// SetNillableLastRxnormSync sets the "last_rxnorm_sync" field if the given value is not nil.
func (_u *DrugUpdate) SetNillableLastRxnormSync(v *time.Time) *DrugUpdate {
	if v != nil {
		_u.SetLastRxnormSync(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DrugUpdate) SetUpdatedAt(v time.Time) *DrugUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddNdcMappingIDs adds the "ndc_mappings" edge to the DrugNdcMap entity by IDs.
func (_u *DrugUpdate) AddNdcMappingIDs(ids ...int) *DrugUpdate {
	_u.mutation.AddNdcMappingIDs(ids...)
	return _u
}

// AddNdcMappings adds the "ndc_mappings" edges to the DrugNdcMap entity.
func (_u *DrugUpdate) AddNdcMappings(v ...*DrugNdcMap) *DrugUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNdcMappingIDs(ids...)
}

// AddFormularyEntryIDs adds the "formulary_entries" edge to the FormularyEntry entity by IDs.
func (_u *DrugUpdate) AddFormularyEntryIDs(ids ...int) *DrugUpdate {
	_u.mutation.AddFormularyEntryIDs(ids...)
	return _u
}

// AddFormularyEntries adds the "formulary_entries" edges to the FormularyEntry entity.
func (_u *DrugUpdate) AddFormularyEntries(v ...*FormularyEntry) *DrugUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFormularyEntryIDs(ids...)
}

// Mutation returns the DrugMutation object of the builder.
func (_u *DrugUpdate) Mutation() *DrugMutation {
	return _u.mutation
}

// ClearNdcMappings clears all "ndc_mappings" edges to the DrugNdcMap entity.
func (_u *DrugUpdate) ClearNdcMappings() *DrugUpdate {
	_u.mutation.ClearNdcMappings()
	return _u
}

// RemoveNdcMappingIDs removes the "ndc_mappings" edge to DrugNdcMap entities by IDs.
func (_u *DrugUpdate) RemoveNdcMappingIDs(ids ...int) *DrugUpdate {
	_u.mutation.RemoveNdcMappingIDs(ids...)
	return _u
}

// RemoveNdcMappings removes "ndc_mappings" edges to DrugNdcMap entities.
func (_u *DrugUpdate) RemoveNdcMappings(v ...*DrugNdcMap) *DrugUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNdcMappingIDs(ids...)
}

// ClearFormularyEntries clears all "formulary_entries" edges to the FormularyEntry entity.
func (_u *DrugUpdate) ClearFormularyEntries() *DrugUpdate {
	_u.mutation.ClearFormularyEntries()
	return _u
}

// RemoveFormularyEntryIDs removes the "formulary_entries" edge to FormularyEntry entities by IDs.
func (_u *DrugUpdate) RemoveFormularyEntryIDs(ids ...int) *DrugUpdate {
	_u.mutation.RemoveFormularyEntryIDs(ids...)
	return _u
}

// RemoveFormularyEntries removes "formulary_entries" edges to FormularyEntry entities.
func (_u *DrugUpdate) RemoveFormularyEntries(v ...*FormularyEntry) *DrugUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFormularyEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DrugUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DrugUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DrugUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DrugUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DrugUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := drug.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DrugUpdate) check() error {
	if v, ok := _u.mutation.Rxcui(); ok {
		if err := drug.RxcuiValidator(v); err != nil {
			return &ValidationError{Name: "rxcui", err: fmt.Errorf(`ent: validator failed for field "Drug.rxcui": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DrugName(); ok {
		if err := drug.DrugNameValidator(v); err != nil {
			return &ValidationError{Name: "drug_name", err: fmt.Errorf(`ent: validator failed for field "Drug.drug_name": %w`, err)}
		}
	}
	return nil
}

func (_u *DrugUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drug.Table, drug.Columns, sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Rxcui(); ok {
		_spec.SetField(drug.FieldRxcui, field.TypeString, value)
	}
	if value, ok := _u.mutation.DrugName(); ok {
		_spec.SetField(drug.FieldDrugName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GenericName(); ok {
		_spec.SetField(drug.FieldGenericName, field.TypeString, value)
	}
	if _u.mutation.GenericNameCleared() {
		_spec.ClearField(drug.FieldGenericName, field.TypeString)
	}
	if value, ok := _u.mutation.BrandNames(); ok {
		_spec.SetField(drug.FieldBrandNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBrandNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, drug.FieldBrandNames, value)
		})
	}
	if _u.mutation.BrandNamesCleared() {
		_spec.ClearField(drug.FieldBrandNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.DoseForm(); ok {
		_spec.SetField(drug.FieldDoseForm, field.TypeString, value)
	}
	if _u.mutation.DoseFormCleared() {
		_spec.ClearField(drug.FieldDoseForm, field.TypeString)
	}
	if value, ok := _u.mutation.Strength(); ok {
		_spec.SetField(drug.FieldStrength, field.TypeString, value)
	}
	if _u.mutation.StrengthCleared() {
		_spec.ClearField(drug.FieldStrength, field.TypeString)
	}
	if value, ok := _u.mutation.Route(); ok {
		_spec.SetField(drug.FieldRoute, field.TypeString, value)
	}
	if _u.mutation.RouteCleared() {
		_spec.ClearField(drug.FieldRoute, field.TypeString)
	}
	if value, ok := _u.mutation.DrugClass(); ok {
		_spec.SetField(drug.FieldDrugClass, field.TypeString, value)
	}
	if _u.mutation.DrugClassCleared() {
		_spec.ClearField(drug.FieldDrugClass, field.TypeString)
	}
	if value, ok := _u.mutation.IsSpecialty(); ok {
		_spec.SetField(drug.FieldIsSpecialty, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsControlled(); ok {
		_spec.SetField(drug.FieldIsControlled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeaSchedule(); ok {
		_spec.SetField(drug.FieldDeaSchedule, field.TypeString, value)
	}
	if _u.mutation.DeaScheduleCleared() {
		_spec.ClearField(drug.FieldDeaSchedule, field.TypeString)
	}
	if value, ok := _u.mutation.LastRxnormSync(); ok {
		_spec.SetField(drug.FieldLastRxnormSync, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(drug.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NdcMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.NdcMappingsTable,
			Columns: []string{drug.NdcMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNdcMappingsIDs(); len(nodes) > 0 && !_u.mutation.NdcMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.NdcMappingsTable,
			Columns: []string{drug.NdcMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NdcMappingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.NdcMappingsTable,
			Columns: []string{drug.NdcMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FormularyEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.FormularyEntriesTable,
			Columns: []string{drug.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFormularyEntriesIDs(); len(nodes) > 0 && !_u.mutation.FormularyEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.FormularyEntriesTable,
			Columns: []string{drug.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FormularyEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.FormularyEntriesTable,
			Columns: []string{drug.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drug.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DrugUpdateOne is the builder for updating a single Drug entity.
type DrugUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DrugMutation
}

// SetRxcui sets the "rxcui" field.
func (_u *DrugUpdateOne) SetRxcui(v string) *DrugUpdateOne {
	_u.mutation.SetRxcui(v)
	return _u
}

// SetNillableRxcui sets the "rxcui" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableRxcui(v *string) *DrugUpdateOne {
	if v != nil {
		_u.SetRxcui(*v)
	}
	return _u
}

// SetDrugName sets the "drug_name" field.
func (_u *DrugUpdateOne) SetDrugName(v string) *DrugUpdateOne {
	_u.mutation.SetDrugName(v)
	return _u
}

// SetNillableDrugName sets the "drug_name" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableDrugName(v *string) *DrugUpdateOne {
	if v != nil {
		_u.SetDrugName(*v)
	}
	return _u
}

// SetGenericName sets the "generic_name" field.
func (_u *DrugUpdateOne) SetGenericName(v string) *DrugUpdateOne {
	_u.mutation.SetGenericName(v)
	return _u
}

// SetNillableGenericName sets the "generic_name" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableGenericName(v *string) *DrugUpdateOne {
	if v != nil {
		_u.SetGenericName(*v)
	}
	return _u
}

// ClearGenericName clears the value of the "generic_name" field.
func (_u *DrugUpdateOne) ClearGenericName() *DrugUpdateOne {
	_u.mutation.ClearGenericName()
	return _u
}

// SetBrandNames sets the "brand_names" field.
func (_u *DrugUpdateOne) SetBrandNames(v []string) *DrugUpdateOne {
	_u.mutation.SetBrandNames(v)
	return _u
}

// AppendBrandNames appends value to the "brand_names" field.
func (_u *DrugUpdateOne) AppendBrandNames(v []string) *DrugUpdateOne {
	_u.mutation.AppendBrandNames(v)
	return _u
}

// ClearBrandNames clears the value of the "brand_names" field.
func (_u *DrugUpdateOne) ClearBrandNames() *DrugUpdateOne {
	_u.mutation.ClearBrandNames()
	return _u
}

// SetDoseForm sets the "dose_form" field.
func (_u *DrugUpdateOne) SetDoseForm(v string) *DrugUpdateOne {
	_u.mutation.SetDoseForm(v)
	return _u
}

// SetNillableDoseForm sets the "dose_form" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableDoseForm(v *string) *DrugUpdateOne {
	if v != nil {
		_u.SetDoseForm(*v)
	}
	return _u
}

// ClearDoseForm clears the value of the "dose_form" field.
func (_u *DrugUpdateOne) ClearDoseForm() *DrugUpdateOne {
	_u.mutation.ClearDoseForm()
	return _u
}

// SetStrength sets the "strength" field.
func (_u *DrugUpdateOne) SetStrength(v string) *DrugUpdateOne {
	_u.mutation.SetStrength(v)
	return _u
}

// SetNillableStrength sets the "strength" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableStrength(v *string) *DrugUpdateOne {
	if v != nil {
		_u.SetStrength(*v)
	}
	return _u
}

// ClearStrength clears the value of the "strength" field.
func (_u *DrugUpdateOne) ClearStrength() *DrugUpdateOne {
	_u.mutation.ClearStrength()
	return _u
}

// SetRoute sets the "route" field.
func (_u *DrugUpdateOne) SetRoute(v string) *DrugUpdateOne {
	_u.mutation.SetRoute(v)
	return _u
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableRoute(v *string) *DrugUpdateOne {
	if v != nil {
		_u.SetRoute(*v)
	}
	return _u
}

// ClearRoute clears the value of the "route" field.
func (_u *DrugUpdateOne) ClearRoute() *DrugUpdateOne {
	_u.mutation.ClearRoute()
	return _u
}

// SetDrugClass sets the "drug_class" field.
func (_u *DrugUpdateOne) SetDrugClass(v string) *DrugUpdateOne {
	_u.mutation.SetDrugClass(v)
	return _u
}

// SetNillableDrugClass sets the "drug_class" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableDrugClass(v *string) *DrugUpdateOne {
	if v != nil {
		_u.SetDrugClass(*v)
	}
	return _u
}

// ClearDrugClass clears the value of the "drug_class" field.
func (_u *DrugUpdateOne) ClearDrugClass() *DrugUpdateOne {
	_u.mutation.ClearDrugClass()
	return _u
}

// SetIsSpecialty sets the "is_specialty" field.
func (_u *DrugUpdateOne) SetIsSpecialty(v bool) *DrugUpdateOne {
	_u.mutation.SetIsSpecialty(v)
	return _u
}

// SetNillableIsSpecialty sets the "is_specialty" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableIsSpecialty(v *bool) *DrugUpdateOne {
	if v != nil {
		_u.SetIsSpecialty(*v)
	}
	return _u
}

// SetIsControlled sets the "is_controlled" field.
func (_u *DrugUpdateOne) SetIsControlled(v bool) *DrugUpdateOne {
	_u.mutation.SetIsControlled(v)
	return _u
}

// SetNillableIsControlled sets the "is_controlled" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableIsControlled(v *bool) *DrugUpdateOne {
	if v != nil {
		_u.SetIsControlled(*v)
	}
	return _u
}

// SetDeaSchedule sets the "dea_schedule" field.
func (_u *DrugUpdateOne) SetDeaSchedule(v string) *DrugUpdateOne {
	_u.mutation.SetDeaSchedule(v)
	return _u
}

// SetNillableDeaSchedule sets the "dea_schedule" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableDeaSchedule(v *string) *DrugUpdateOne {
	if v != nil {
		_u.SetDeaSchedule(*v)
	}
	return _u
}

// ClearDeaSchedule clears the value of the "dea_schedule" field.
func (_u *DrugUpdateOne) ClearDeaSchedule() *DrugUpdateOne {
	_u.mutation.ClearDeaSchedule()
	return _u
}

// SetLastRxnormSync sets the "last_rxnorm_sync" field.
func (_u *DrugUpdateOne) SetLastRxnormSync(v time.Time) *DrugUpdateOne {
	_u.mutation.SetLastRxnormSync(v)
	return _u
}

// SetNillableLastRxnormSync sets the "last_rxnorm_sync" field if the given value is not nil.
func (_u *DrugUpdateOne) SetNillableLastRxnormSync(v *time.Time) *DrugUpdateOne {
	if v != nil {
		_u.SetLastRxnormSync(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DrugUpdateOne) SetUpdatedAt(v time.Time) *DrugUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddNdcMappingIDs adds the "ndc_mappings" edge to the DrugNdcMap entity by IDs.
func (_u *DrugUpdateOne) AddNdcMappingIDs(ids ...int) *DrugUpdateOne {
	_u.mutation.AddNdcMappingIDs(ids...)
	return _u
}

// AddNdcMappings adds the "ndc_mappings" edges to the DrugNdcMap entity.
func (_u *DrugUpdateOne) AddNdcMappings(v ...*DrugNdcMap) *DrugUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNdcMappingIDs(ids...)
}

// AddFormularyEntryIDs adds the "formulary_entries" edge to the FormularyEntry entity by IDs.
func (_u *DrugUpdateOne) AddFormularyEntryIDs(ids ...int) *DrugUpdateOne {
	_u.mutation.AddFormularyEntryIDs(ids...)
	return _u
}

// AddFormularyEntries adds the "formulary_entries" edges to the FormularyEntry entity.
func (_u *DrugUpdateOne) AddFormularyEntries(v ...*FormularyEntry) *DrugUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFormularyEntryIDs(ids...)
}

// Mutation returns the DrugMutation object of the builder.
func (_u *DrugUpdateOne) Mutation() *DrugMutation {
	return _u.mutation
}

// ClearNdcMappings clears all "ndc_mappings" edges to the DrugNdcMap entity.
func (_u *DrugUpdateOne) ClearNdcMappings() *DrugUpdateOne {
	_u.mutation.ClearNdcMappings()
	return _u
}

// RemoveNdcMappingIDs removes the "ndc_mappings" edge to DrugNdcMap entities by IDs.
func (_u *DrugUpdateOne) RemoveNdcMappingIDs(ids ...int) *DrugUpdateOne {
	_u.mutation.RemoveNdcMappingIDs(ids...)
	return _u
}

// RemoveNdcMappings removes "ndc_mappings" edges to DrugNdcMap entities.
func (_u *DrugUpdateOne) RemoveNdcMappings(v ...*DrugNdcMap) *DrugUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNdcMappingIDs(ids...)
}

// ClearFormularyEntries clears all "formulary_entries" edges to the FormularyEntry entity.
func (_u *DrugUpdateOne) ClearFormularyEntries() *DrugUpdateOne {
	_u.mutation.ClearFormularyEntries()
	return _u
}

// RemoveFormularyEntryIDs removes the "formulary_entries" edge to FormularyEntry entities by IDs.
func (_u *DrugUpdateOne) RemoveFormularyEntryIDs(ids ...int) *DrugUpdateOne {
	_u.mutation.RemoveFormularyEntryIDs(ids...)
	return _u
}

// RemoveFormularyEntries removes "formulary_entries" edges to FormularyEntry entities.
func (_u *DrugUpdateOne) RemoveFormularyEntries(v ...*FormularyEntry) *DrugUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFormularyEntryIDs(ids...)
}

// Where appends a list predicates to the DrugUpdate builder.
func (_u *DrugUpdateOne) Where(ps ...predicate.Drug) *DrugUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DrugUpdateOne) Select(field string, fields ...string) *DrugUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Drug entity.
func (_u *DrugUpdateOne) Save(ctx context.Context) (*Drug, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DrugUpdateOne) SaveX(ctx context.Context) *Drug {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DrugUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DrugUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DrugUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := drug.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DrugUpdateOne) check() error {
	if v, ok := _u.mutation.Rxcui(); ok {
		if err := drug.RxcuiValidator(v); err != nil {
			return &ValidationError{Name: "rxcui", err: fmt.Errorf(`ent: validator failed for field "Drug.rxcui": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DrugName(); ok {
		if err := drug.DrugNameValidator(v); err != nil {
			return &ValidationError{Name: "drug_name", err: fmt.Errorf(`ent: validator failed for field "Drug.drug_name": %w`, err)}
		}
	}
	return nil
}

func (_u *DrugUpdateOne) sqlSave(ctx context.Context) (_node *Drug, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drug.Table, drug.Columns, sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Drug.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drug.FieldID)
		for _, f := range fields {
			if !drug.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != drug.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Rxcui(); ok {
		_spec.SetField(drug.FieldRxcui, field.TypeString, value)
	}
	if value, ok := _u.mutation.DrugName(); ok {
		_spec.SetField(drug.FieldDrugName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GenericName(); ok {
		_spec.SetField(drug.FieldGenericName, field.TypeString, value)
	}
	if _u.mutation.GenericNameCleared() {
		_spec.ClearField(drug.FieldGenericName, field.TypeString)
	}
	if value, ok := _u.mutation.BrandNames(); ok {
		_spec.SetField(drug.FieldBrandNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBrandNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, drug.FieldBrandNames, value)
		})
	}
	if _u.mutation.BrandNamesCleared() {
		_spec.ClearField(drug.FieldBrandNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.DoseForm(); ok {
		_spec.SetField(drug.FieldDoseForm, field.TypeString, value)
	}
	if _u.mutation.DoseFormCleared() {
		_spec.ClearField(drug.FieldDoseForm, field.TypeString)
	}
	if value, ok := _u.mutation.Strength(); ok {
		_spec.SetField(drug.FieldStrength, field.TypeString, value)
	}
	if _u.mutation.StrengthCleared() {
		_spec.ClearField(drug.FieldStrength, field.TypeString)
	}
	if value, ok := _u.mutation.Route(); ok {
		_spec.SetField(drug.FieldRoute, field.TypeString, value)
	}
	if _u.mutation.RouteCleared() {
		_spec.ClearField(drug.FieldRoute, field.TypeString)
	}
	if value, ok := _u.mutation.DrugClass(); ok {
		_spec.SetField(drug.FieldDrugClass, field.TypeString, value)
	}
	if _u.mutation.DrugClassCleared() {
		_spec.ClearField(drug.FieldDrugClass, field.TypeString)
	}
	if value, ok := _u.mutation.IsSpecialty(); ok {
		_spec.SetField(drug.FieldIsSpecialty, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsControlled(); ok {
		_spec.SetField(drug.FieldIsControlled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeaSchedule(); ok {
		_spec.SetField(drug.FieldDeaSchedule, field.TypeString, value)
	}
	if _u.mutation.DeaScheduleCleared() {
		_spec.ClearField(drug.FieldDeaSchedule, field.TypeString)
	}
	if value, ok := _u.mutation.LastRxnormSync(); ok {
		_spec.SetField(drug.FieldLastRxnormSync, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(drug.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.NdcMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.NdcMappingsTable,
			Columns: []string{drug.NdcMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNdcMappingsIDs(); len(nodes) > 0 && !_u.mutation.NdcMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.NdcMappingsTable,
			Columns: []string{drug.NdcMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NdcMappingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.NdcMappingsTable,
			Columns: []string{drug.NdcMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drugndcmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FormularyEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.FormularyEntriesTable,
			Columns: []string{drug.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFormularyEntriesIDs(); len(nodes) > 0 && !_u.mutation.FormularyEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.FormularyEntriesTable,
			Columns: []string{drug.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FormularyEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drug.FormularyEntriesTable,
			Columns: []string{drug.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Drug{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drug.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
