// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/plan"
)

// FormularyEntryCreate is the builder for creating a FormularyEntry entity.
type FormularyEntryCreate struct {
	config
	mutation *FormularyEntryMutation
	hooks    []Hook
}

// SetTierLevel sets the "tier_level" field.
func (_c *FormularyEntryCreate) SetTierLevel(v int) *FormularyEntryCreate {
	_c.mutation.SetTierLevel(v)
	return _c
}

// SetNillableTierLevel sets the "tier_level" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableTierLevel(v *int) *FormularyEntryCreate {
	if v != nil {
		_c.SetTierLevel(*v)
	}
	return _c
}

// SetTierName sets the "tier_name" field.
func (_c *FormularyEntryCreate) SetTierName(v string) *FormularyEntryCreate {
	_c.mutation.SetTierName(v)
	return _c
}

// SetNillableTierName sets the "tier_name" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableTierName(v *string) *FormularyEntryCreate {
	if v != nil {
		_c.SetTierName(*v)
	}
	return _c
}

// SetPriorAuthRequired sets the "prior_auth_required" field.
func (_c *FormularyEntryCreate) SetPriorAuthRequired(v bool) *FormularyEntryCreate {
	_c.mutation.SetPriorAuthRequired(v)
	return _c
}

// SetNillablePriorAuthRequired sets the "prior_auth_required" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillablePriorAuthRequired(v *bool) *FormularyEntryCreate {
	if v != nil {
		_c.SetPriorAuthRequired(*v)
	}
	return _c
}

// SetStepTherapy sets the "step_therapy" field.
func (_c *FormularyEntryCreate) SetStepTherapy(v bool) *FormularyEntryCreate {
	_c.mutation.SetStepTherapy(v)
	return _c
}

// SetNillableStepTherapy sets the "step_therapy" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableStepTherapy(v *bool) *FormularyEntryCreate {
	if v != nil {
		_c.SetStepTherapy(*v)
	}
	return _c
}

// SetQuantityLimit sets the "quantity_limit" field.
func (_c *FormularyEntryCreate) SetQuantityLimit(v bool) *FormularyEntryCreate {
	_c.mutation.SetQuantityLimit(v)
	return _c
}

// SetNillableQuantityLimit sets the "quantity_limit" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableQuantityLimit(v *bool) *FormularyEntryCreate {
	if v != nil {
		_c.SetQuantityLimit(*v)
	}
	return _c
}

// SetQuantityLimitAmount sets the "quantity_limit_amount" field.
func (_c *FormularyEntryCreate) SetQuantityLimitAmount(v float64) *FormularyEntryCreate {
	_c.mutation.SetQuantityLimitAmount(v)
	return _c
}

// SetNillableQuantityLimitAmount sets the "quantity_limit_amount" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableQuantityLimitAmount(v *float64) *FormularyEntryCreate {
	if v != nil {
		_c.SetQuantityLimitAmount(*v)
	}
	return _c
}

// SetQuantityLimitDays sets the "quantity_limit_days" field.
func (_c *FormularyEntryCreate) SetQuantityLimitDays(v int) *FormularyEntryCreate {
	_c.mutation.SetQuantityLimitDays(v)
	return _c
}

// SetNillableQuantityLimitDays sets the "quantity_limit_days" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableQuantityLimitDays(v *int) *FormularyEntryCreate {
	if v != nil {
		_c.SetQuantityLimitDays(*v)
	}
	return _c
}

// SetCopayAmount sets the "copay_amount" field.
func (_c *FormularyEntryCreate) SetCopayAmount(v float64) *FormularyEntryCreate {
	_c.mutation.SetCopayAmount(v)
	return _c
}

// SetNillableCopayAmount sets the "copay_amount" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableCopayAmount(v *float64) *FormularyEntryCreate {
	if v != nil {
		_c.SetCopayAmount(*v)
	}
	return _c
}

// SetCoinsurancePct sets the "coinsurance_pct" field.
func (_c *FormularyEntryCreate) SetCoinsurancePct(v float64) *FormularyEntryCreate {
	_c.mutation.SetCoinsurancePct(v)
	return _c
}

// SetNillableCoinsurancePct sets the "coinsurance_pct" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableCoinsurancePct(v *float64) *FormularyEntryCreate {
	if v != nil {
		_c.SetCoinsurancePct(*v)
	}
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *FormularyEntryCreate) SetSourceType(v string) *FormularyEntryCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceDate sets the "source_date" field.
func (_c *FormularyEntryCreate) SetSourceDate(v time.Time) *FormularyEntryCreate {
	_c.mutation.SetSourceDate(v)
	return _c
}

// SetIsCurrent sets the "is_current" field.
func (_c *FormularyEntryCreate) SetIsCurrent(v bool) *FormularyEntryCreate {
	_c.mutation.SetIsCurrent(v)
	return _c
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableIsCurrent(v *bool) *FormularyEntryCreate {
	if v != nil {
		_c.SetIsCurrent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FormularyEntryCreate) SetCreatedAt(v time.Time) *FormularyEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FormularyEntryCreate) SetNillableCreatedAt(v *time.Time) *FormularyEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_c *FormularyEntryCreate) SetPlanID(id int) *FormularyEntryCreate {
	_c.mutation.SetPlanID(id)
	return _c
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_c *FormularyEntryCreate) SetPlan(v *Plan) *FormularyEntryCreate {
	return _c.SetPlanID(v.ID)
}

// SetDrugID sets the "drug" edge to the Drug entity by ID.
func (_c *FormularyEntryCreate) SetDrugID(id int) *FormularyEntryCreate {
	_c.mutation.SetDrugID(id)
	return _c
}

// SetDrug sets the "drug" edge to the Drug entity.
func (_c *FormularyEntryCreate) SetDrug(v *Drug) *FormularyEntryCreate {
	return _c.SetDrugID(v.ID)
}

// Mutation returns the FormularyEntryMutation object of the builder.
func (_c *FormularyEntryCreate) Mutation() *FormularyEntryMutation {
	return _c.mutation
}

// Save creates the FormularyEntry in the database.
func (_c *FormularyEntryCreate) Save(ctx context.Context) (*FormularyEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FormularyEntryCreate) SaveX(ctx context.Context) *FormularyEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FormularyEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FormularyEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FormularyEntryCreate) defaults() {
	if _, ok := _c.mutation.PriorAuthRequired(); !ok {
		v := formularyentry.DefaultPriorAuthRequired
		_c.mutation.SetPriorAuthRequired(v)
	}
	if _, ok := _c.mutation.StepTherapy(); !ok {
		v := formularyentry.DefaultStepTherapy
		_c.mutation.SetStepTherapy(v)
	}
	if _, ok := _c.mutation.QuantityLimit(); !ok {
		v := formularyentry.DefaultQuantityLimit
		_c.mutation.SetQuantityLimit(v)
	}
	if _, ok := _c.mutation.IsCurrent(); !ok {
		v := formularyentry.DefaultIsCurrent
		_c.mutation.SetIsCurrent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := formularyentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FormularyEntryCreate) check() error {
	if _, ok := _c.mutation.PriorAuthRequired(); !ok {
		return &ValidationError{Name: "prior_auth_required", err: errors.New(`ent: missing required field "FormularyEntry.prior_auth_required"`)}
	}
	if _, ok := _c.mutation.StepTherapy(); !ok {
		return &ValidationError{Name: "step_therapy", err: errors.New(`ent: missing required field "FormularyEntry.step_therapy"`)}
	}
	if _, ok := _c.mutation.QuantityLimit(); !ok {
		return &ValidationError{Name: "quantity_limit", err: errors.New(`ent: missing required field "FormularyEntry.quantity_limit"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "FormularyEntry.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := formularyentry.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "FormularyEntry.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceDate(); !ok {
		return &ValidationError{Name: "source_date", err: errors.New(`ent: missing required field "FormularyEntry.source_date"`)}
	}
	if _, ok := _c.mutation.IsCurrent(); !ok {
		return &ValidationError{Name: "is_current", err: errors.New(`ent: missing required field "FormularyEntry.is_current"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FormularyEntry.created_at"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "FormularyEntry.plan"`)}
	}
	if len(_c.mutation.DrugIDs()) == 0 {
		return &ValidationError{Name: "drug", err: errors.New(`ent: missing required edge "FormularyEntry.drug"`)}
	}
	return nil
}

func (_c *FormularyEntryCreate) sqlSave(ctx context.Context) (*FormularyEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FormularyEntryCreate) createSpec() (*FormularyEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &FormularyEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(formularyentry.Table, sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TierLevel(); ok {
		_spec.SetField(formularyentry.FieldTierLevel, field.TypeInt, value)
		_node.TierLevel = value
	}
	if value, ok := _c.mutation.TierName(); ok {
		_spec.SetField(formularyentry.FieldTierName, field.TypeString, value)
		_node.TierName = value
	}
	if value, ok := _c.mutation.PriorAuthRequired(); ok {
		_spec.SetField(formularyentry.FieldPriorAuthRequired, field.TypeBool, value)
		_node.PriorAuthRequired = value
	}
	if value, ok := _c.mutation.StepTherapy(); ok {
		_spec.SetField(formularyentry.FieldStepTherapy, field.TypeBool, value)
		_node.StepTherapy = value
	}
	if value, ok := _c.mutation.QuantityLimit(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimit, field.TypeBool, value)
		_node.QuantityLimit = value
	}
	if value, ok := _c.mutation.QuantityLimitAmount(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimitAmount, field.TypeFloat64, value)
		_node.QuantityLimitAmount = &value
	}
	if value, ok := _c.mutation.QuantityLimitDays(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimitDays, field.TypeInt, value)
		_node.QuantityLimitDays = &value
	}
	if value, ok := _c.mutation.CopayAmount(); ok {
		_spec.SetField(formularyentry.FieldCopayAmount, field.TypeFloat64, value)
		_node.CopayAmount = &value
	}
	if value, ok := _c.mutation.CoinsurancePct(); ok {
		_spec.SetField(formularyentry.FieldCoinsurancePct, field.TypeFloat64, value)
		_node.CoinsurancePct = &value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(formularyentry.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceDate(); ok {
		_spec.SetField(formularyentry.FieldSourceDate, field.TypeTime, value)
		_node.SourceDate = value
	}
	if value, ok := _c.mutation.IsCurrent(); ok {
		_spec.SetField(formularyentry.FieldIsCurrent, field.TypeBool, value)
		_node.IsCurrent = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(formularyentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.PlanTable,
			Columns: []string{formularyentry.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.plan_formulary_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.DrugTable,
			Columns: []string{formularyentry.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.drug_formulary_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FormularyEntryCreateBulk is the builder for creating many FormularyEntry entities in bulk.
type FormularyEntryCreateBulk struct {
	config
	err      error
	builders []*FormularyEntryCreate
}

// Save creates the FormularyEntry entities in the database.
func (_c *FormularyEntryCreateBulk) Save(ctx context.Context) ([]*FormularyEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FormularyEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FormularyEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FormularyEntryCreateBulk) SaveX(ctx context.Context) []*FormularyEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FormularyEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FormularyEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
