// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/plan"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// FormularyEntryQuery is the builder for querying FormularyEntry entities.
type FormularyEntryQuery struct {
	config
	ctx        *QueryContext
	order      []formularyentry.OrderOption
	inters     []Interceptor
	predicates []predicate.FormularyEntry
	withPlan   *PlanQuery
	withDrug   *DrugQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FormularyEntryQuery builder.
func (_q *FormularyEntryQuery) Where(ps ...predicate.FormularyEntry) *FormularyEntryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FormularyEntryQuery) Limit(limit int) *FormularyEntryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FormularyEntryQuery) Offset(offset int) *FormularyEntryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FormularyEntryQuery) Unique(unique bool) *FormularyEntryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FormularyEntryQuery) Order(o ...formularyentry.OrderOption) *FormularyEntryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPlan chains the current query on the "plan" edge.
func (_q *FormularyEntryQuery) QueryPlan() *PlanQuery {
	query := (&PlanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(formularyentry.Table, formularyentry.FieldID, selector),
			sqlgraph.To(plan.Table, plan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, formularyentry.PlanTable, formularyentry.PlanColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDrug chains the current query on the "drug" edge.
func (_q *FormularyEntryQuery) QueryDrug() *DrugQuery {
	query := (&DrugClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(formularyentry.Table, formularyentry.FieldID, selector),
			sqlgraph.To(drug.Table, drug.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, formularyentry.DrugTable, formularyentry.DrugColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FormularyEntry entity from the query.
// Returns a *NotFoundError when no FormularyEntry was found.
func (_q *FormularyEntryQuery) First(ctx context.Context) (*FormularyEntry, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{formularyentry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FormularyEntryQuery) FirstX(ctx context.Context) *FormularyEntry {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FormularyEntry ID from the query.
// Returns a *NotFoundError when no FormularyEntry ID was found.
func (_q *FormularyEntryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{formularyentry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FormularyEntryQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FormularyEntry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FormularyEntry entity is found.
// Returns a *NotFoundError when no FormularyEntry entities are found.
func (_q *FormularyEntryQuery) Only(ctx context.Context) (*FormularyEntry, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{formularyentry.Label}
	default:
		return nil, &NotSingularError{formularyentry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FormularyEntryQuery) OnlyX(ctx context.Context) *FormularyEntry {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FormularyEntry ID in the query.
// Returns a *NotSingularError when more than one FormularyEntry ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FormularyEntryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{formularyentry.Label}
	default:
		err = &NotSingularError{formularyentry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FormularyEntryQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FormularyEntries.
func (_q *FormularyEntryQuery) All(ctx context.Context) ([]*FormularyEntry, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FormularyEntry, *FormularyEntryQuery]()
	return withInterceptors[[]*FormularyEntry](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FormularyEntryQuery) AllX(ctx context.Context) []*FormularyEntry {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FormularyEntry IDs.
func (_q *FormularyEntryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(formularyentry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FormularyEntryQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FormularyEntryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FormularyEntryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FormularyEntryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FormularyEntryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FormularyEntryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FormularyEntryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FormularyEntryQuery) Clone() *FormularyEntryQuery {
	if _q == nil {
		return nil
	}
	return &FormularyEntryQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]formularyentry.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.FormularyEntry{}, _q.predicates...),
		withPlan:   _q.withPlan.Clone(),
		withDrug:   _q.withDrug.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPlan tells the query-builder to eager-load the nodes that are connected to
// the "plan" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FormularyEntryQuery) WithPlan(opts ...func(*PlanQuery)) *FormularyEntryQuery {
	query := (&PlanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlan = query
	return _q
}

// WithDrug tells the query-builder to eager-load the nodes that are connected to
// the "drug" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FormularyEntryQuery) WithDrug(opts ...func(*DrugQuery)) *FormularyEntryQuery {
	query := (&DrugClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDrug = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TierLevel int `json:"tier_level,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FormularyEntry.Query().
//		GroupBy(formularyentry.FieldTierLevel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FormularyEntryQuery) GroupBy(field string, fields ...string) *FormularyEntryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FormularyEntryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = formularyentry.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TierLevel int `json:"tier_level,omitempty"`
//	}
//
//	client.FormularyEntry.Query().
//		Select(formularyentry.FieldTierLevel).
//		Scan(ctx, &v)
func (_q *FormularyEntryQuery) Select(fields ...string) *FormularyEntrySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FormularyEntrySelect{FormularyEntryQuery: _q}
	sbuild.label = formularyentry.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FormularyEntrySelect configured with the given aggregations.
func (_q *FormularyEntryQuery) Aggregate(fns ...AggregateFunc) *FormularyEntrySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FormularyEntryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !formularyentry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FormularyEntryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FormularyEntry, error) {
	var (
		nodes       = []*FormularyEntry{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPlan != nil,
			_q.withDrug != nil,
		}
	)
	if _q.withPlan != nil || _q.withDrug != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, formularyentry.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FormularyEntry).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FormularyEntry{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPlan; query != nil {
		if err := _q.loadPlan(ctx, query, nodes, nil,
			func(n *FormularyEntry, e *Plan) { n.Edges.Plan = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDrug; query != nil {
		if err := _q.loadDrug(ctx, query, nodes, nil,
			func(n *FormularyEntry, e *Drug) { n.Edges.Drug = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FormularyEntryQuery) loadPlan(ctx context.Context, query *PlanQuery, nodes []*FormularyEntry, init func(*FormularyEntry), assign func(*FormularyEntry, *Plan)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FormularyEntry)
	for i := range nodes {
		if nodes[i].plan_formulary_entries == nil {
			continue
		}
		fk := *nodes[i].plan_formulary_entries
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(plan.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "plan_formulary_entries" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FormularyEntryQuery) loadDrug(ctx context.Context, query *DrugQuery, nodes []*FormularyEntry, init func(*FormularyEntry), assign func(*FormularyEntry, *Drug)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FormularyEntry)
	for i := range nodes {
		if nodes[i].drug_formulary_entries == nil {
			continue
		}
		fk := *nodes[i].drug_formulary_entries
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(drug.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "drug_formulary_entries" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *FormularyEntryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FormularyEntryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(formularyentry.Table, formularyentry.Columns, sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, formularyentry.FieldID)
		for i := range fields {
			if fields[i] != formularyentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FormularyEntryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(formularyentry.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = formularyentry.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FormularyEntryGroupBy is the group-by builder for FormularyEntry entities.
type FormularyEntryGroupBy struct {
	selector
	build *FormularyEntryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FormularyEntryGroupBy) Aggregate(fns ...AggregateFunc) *FormularyEntryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FormularyEntryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormularyEntryQuery, *FormularyEntryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FormularyEntryGroupBy) sqlScan(ctx context.Context, root *FormularyEntryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FormularyEntrySelect is the builder for selecting fields of FormularyEntry entities.
type FormularyEntrySelect struct {
	*FormularyEntryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FormularyEntrySelect) Aggregate(fns ...AggregateFunc) *FormularyEntrySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FormularyEntrySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormularyEntryQuery, *FormularyEntrySelect](ctx, _s.FormularyEntryQuery, _s, _s.inters, v)
}

func (_s *FormularyEntrySelect) sqlScan(ctx context.Context, root *FormularyEntryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
