// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/plan"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// FormularyEntryUpdate is the builder for updating FormularyEntry entities.
type FormularyEntryUpdate struct {
	config
	hooks    []Hook
	mutation *FormularyEntryMutation
}

// Where appends a list predicates to the FormularyEntryUpdate builder.
func (_u *FormularyEntryUpdate) Where(ps ...predicate.FormularyEntry) *FormularyEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTierLevel sets the "tier_level" field.
func (_u *FormularyEntryUpdate) SetTierLevel(v int) *FormularyEntryUpdate {
	_u.mutation.ResetTierLevel()
	_u.mutation.SetTierLevel(v)
	return _u
}

// SetNillableTierLevel sets the "tier_level" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableTierLevel(v *int) *FormularyEntryUpdate {
	if v != nil {
		_u.SetTierLevel(*v)
	}
	return _u
}

// AddTierLevel adds value to the "tier_level" field.
func (_u *FormularyEntryUpdate) AddTierLevel(v int) *FormularyEntryUpdate {
	_u.mutation.AddTierLevel(v)
	return _u
}

// ClearTierLevel clears the value of the "tier_level" field.
func (_u *FormularyEntryUpdate) ClearTierLevel() *FormularyEntryUpdate {
	_u.mutation.ClearTierLevel()
	return _u
}

// SetTierName sets the "tier_name" field.
func (_u *FormularyEntryUpdate) SetTierName(v string) *FormularyEntryUpdate {
	_u.mutation.SetTierName(v)
	return _u
}

// SetNillableTierName sets the "tier_name" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableTierName(v *string) *FormularyEntryUpdate {
	if v != nil {
		_u.SetTierName(*v)
	}
	return _u
}

// ClearTierName clears the value of the "tier_name" field.
func (_u *FormularyEntryUpdate) ClearTierName() *FormularyEntryUpdate {
	_u.mutation.ClearTierName()
	return _u
}

// SetPriorAuthRequired sets the "prior_auth_required" field.
func (_u *FormularyEntryUpdate) SetPriorAuthRequired(v bool) *FormularyEntryUpdate {
	_u.mutation.SetPriorAuthRequired(v)
	return _u
}

// SetNillablePriorAuthRequired sets the "prior_auth_required" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillablePriorAuthRequired(v *bool) *FormularyEntryUpdate {
	if v != nil {
		_u.SetPriorAuthRequired(*v)
	}
	return _u
}

// SetStepTherapy sets the "step_therapy" field.
func (_u *FormularyEntryUpdate) SetStepTherapy(v bool) *FormularyEntryUpdate {
	_u.mutation.SetStepTherapy(v)
	return _u
}

// SetNillableStepTherapy sets the "step_therapy" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableStepTherapy(v *bool) *FormularyEntryUpdate {
	if v != nil {
		_u.SetStepTherapy(*v)
	}
	return _u
}

// SetQuantityLimit sets the "quantity_limit" field.
func (_u *FormularyEntryUpdate) SetQuantityLimit(v bool) *FormularyEntryUpdate {
	_u.mutation.SetQuantityLimit(v)
	return _u
}

// SetNillableQuantityLimit sets the "quantity_limit" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableQuantityLimit(v *bool) *FormularyEntryUpdate {
	if v != nil {
		_u.SetQuantityLimit(*v)
	}
	return _u
}

// SetQuantityLimitAmount sets the "quantity_limit_amount" field.
func (_u *FormularyEntryUpdate) SetQuantityLimitAmount(v float64) *FormularyEntryUpdate {
	_u.mutation.ResetQuantityLimitAmount()
	_u.mutation.SetQuantityLimitAmount(v)
	return _u
}

// SetNillableQuantityLimitAmount sets the "quantity_limit_amount" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableQuantityLimitAmount(v *float64) *FormularyEntryUpdate {
	if v != nil {
		_u.SetQuantityLimitAmount(*v)
	}
	return _u
}

// AddQuantityLimitAmount adds value to the "quantity_limit_amount" field.
func (_u *FormularyEntryUpdate) AddQuantityLimitAmount(v float64) *FormularyEntryUpdate {
	_u.mutation.AddQuantityLimitAmount(v)
	return _u
}

// ClearQuantityLimitAmount clears the value of the "quantity_limit_amount" field.
func (_u *FormularyEntryUpdate) ClearQuantityLimitAmount() *FormularyEntryUpdate {
	_u.mutation.ClearQuantityLimitAmount()
	return _u
}

// SetQuantityLimitDays sets the "quantity_limit_days" field.
func (_u *FormularyEntryUpdate) SetQuantityLimitDays(v int) *FormularyEntryUpdate {
	_u.mutation.ResetQuantityLimitDays()
	_u.mutation.SetQuantityLimitDays(v)
	return _u
}

// SetNillableQuantityLimitDays sets the "quantity_limit_days" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableQuantityLimitDays(v *int) *FormularyEntryUpdate {
	if v != nil {
		_u.SetQuantityLimitDays(*v)
	}
	return _u
}

// AddQuantityLimitDays adds value to the "quantity_limit_days" field.
func (_u *FormularyEntryUpdate) AddQuantityLimitDays(v int) *FormularyEntryUpdate {
	_u.mutation.AddQuantityLimitDays(v)
	return _u
}

// ClearQuantityLimitDays clears the value of the "quantity_limit_days" field.
func (_u *FormularyEntryUpdate) ClearQuantityLimitDays() *FormularyEntryUpdate {
	_u.mutation.ClearQuantityLimitDays()
	return _u
}

// SetCopayAmount sets the "copay_amount" field.
func (_u *FormularyEntryUpdate) SetCopayAmount(v float64) *FormularyEntryUpdate {
	_u.mutation.ResetCopayAmount()
	_u.mutation.SetCopayAmount(v)
	return _u
}

// SetNillableCopayAmount sets the "copay_amount" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableCopayAmount(v *float64) *FormularyEntryUpdate {
	if v != nil {
		_u.SetCopayAmount(*v)
	}
	return _u
}

// AddCopayAmount adds value to the "copay_amount" field.
func (_u *FormularyEntryUpdate) AddCopayAmount(v float64) *FormularyEntryUpdate {
	_u.mutation.AddCopayAmount(v)
	return _u
}

// ClearCopayAmount clears the value of the "copay_amount" field.
func (_u *FormularyEntryUpdate) ClearCopayAmount() *FormularyEntryUpdate {
	_u.mutation.ClearCopayAmount()
	return _u
}

// SetCoinsurancePct sets the "coinsurance_pct" field.
func (_u *FormularyEntryUpdate) SetCoinsurancePct(v float64) *FormularyEntryUpdate {
	_u.mutation.ResetCoinsurancePct()
	_u.mutation.SetCoinsurancePct(v)
	return _u
}

// SetNillableCoinsurancePct sets the "coinsurance_pct" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableCoinsurancePct(v *float64) *FormularyEntryUpdate {
	if v != nil {
		_u.SetCoinsurancePct(*v)
	}
	return _u
}

// AddCoinsurancePct adds value to the "coinsurance_pct" field.
func (_u *FormularyEntryUpdate) AddCoinsurancePct(v float64) *FormularyEntryUpdate {
	_u.mutation.AddCoinsurancePct(v)
	return _u
}

// ClearCoinsurancePct clears the value of the "coinsurance_pct" field.
func (_u *FormularyEntryUpdate) ClearCoinsurancePct() *FormularyEntryUpdate {
	_u.mutation.ClearCoinsurancePct()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *FormularyEntryUpdate) SetSourceType(v string) *FormularyEntryUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableSourceType(v *string) *FormularyEntryUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceDate sets the "source_date" field.
func (_u *FormularyEntryUpdate) SetSourceDate(v time.Time) *FormularyEntryUpdate {
	_u.mutation.SetSourceDate(v)
	return _u
}

// SetNillableSourceDate sets the "source_date" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableSourceDate(v *time.Time) *FormularyEntryUpdate {
	if v != nil {
		_u.SetSourceDate(*v)
	}
	return _u
}

// SetIsCurrent sets the "is_current" field.
func (_u *FormularyEntryUpdate) SetIsCurrent(v bool) *FormularyEntryUpdate {
	_u.mutation.SetIsCurrent(v)
	return _u
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_u *FormularyEntryUpdate) SetNillableIsCurrent(v *bool) *FormularyEntryUpdate {
	if v != nil {
		_u.SetIsCurrent(*v)
	}
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *FormularyEntryUpdate) SetPlanID(id int) *FormularyEntryUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *FormularyEntryUpdate) SetPlan(v *Plan) *FormularyEntryUpdate {
	return _u.SetPlanID(v.ID)
}

// SetDrugID sets the "drug" edge to the Drug entity by ID.
func (_u *FormularyEntryUpdate) SetDrugID(id int) *FormularyEntryUpdate {
	_u.mutation.SetDrugID(id)
	return _u
}

// SetDrug sets the "drug" edge to the Drug entity.
func (_u *FormularyEntryUpdate) SetDrug(v *Drug) *FormularyEntryUpdate {
	return _u.SetDrugID(v.ID)
}

// Mutation returns the FormularyEntryMutation object of the builder.
func (_u *FormularyEntryUpdate) Mutation() *FormularyEntryMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *FormularyEntryUpdate) ClearPlan() *FormularyEntryUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearDrug clears the "drug" edge to the Drug entity.
func (_u *FormularyEntryUpdate) ClearDrug() *FormularyEntryUpdate {
	_u.mutation.ClearDrug()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FormularyEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FormularyEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FormularyEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FormularyEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FormularyEntryUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := formularyentry.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "FormularyEntry.source_type": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FormularyEntry.plan"`)
	}
	if _u.mutation.DrugCleared() && len(_u.mutation.DrugIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FormularyEntry.drug"`)
	}
	return nil
}

func (_u *FormularyEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(formularyentry.Table, formularyentry.Columns, sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TierLevel(); ok {
		_spec.SetField(formularyentry.FieldTierLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTierLevel(); ok {
		_spec.AddField(formularyentry.FieldTierLevel, field.TypeInt, value)
	}
	if _u.mutation.TierLevelCleared() {
		_spec.ClearField(formularyentry.FieldTierLevel, field.TypeInt)
	}
	if value, ok := _u.mutation.TierName(); ok {
		_spec.SetField(formularyentry.FieldTierName, field.TypeString, value)
	}
	if _u.mutation.TierNameCleared() {
		_spec.ClearField(formularyentry.FieldTierName, field.TypeString)
	}
	if value, ok := _u.mutation.PriorAuthRequired(); ok {
		_spec.SetField(formularyentry.FieldPriorAuthRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StepTherapy(); ok {
		_spec.SetField(formularyentry.FieldStepTherapy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuantityLimit(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuantityLimitAmount(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantityLimitAmount(); ok {
		_spec.AddField(formularyentry.FieldQuantityLimitAmount, field.TypeFloat64, value)
	}
	if _u.mutation.QuantityLimitAmountCleared() {
		_spec.ClearField(formularyentry.FieldQuantityLimitAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QuantityLimitDays(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimitDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantityLimitDays(); ok {
		_spec.AddField(formularyentry.FieldQuantityLimitDays, field.TypeInt, value)
	}
	if _u.mutation.QuantityLimitDaysCleared() {
		_spec.ClearField(formularyentry.FieldQuantityLimitDays, field.TypeInt)
	}
	if value, ok := _u.mutation.CopayAmount(); ok {
		_spec.SetField(formularyentry.FieldCopayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCopayAmount(); ok {
		_spec.AddField(formularyentry.FieldCopayAmount, field.TypeFloat64, value)
	}
	if _u.mutation.CopayAmountCleared() {
		_spec.ClearField(formularyentry.FieldCopayAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CoinsurancePct(); ok {
		_spec.SetField(formularyentry.FieldCoinsurancePct, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCoinsurancePct(); ok {
		_spec.AddField(formularyentry.FieldCoinsurancePct, field.TypeFloat64, value)
	}
	if _u.mutation.CoinsurancePctCleared() {
		_spec.ClearField(formularyentry.FieldCoinsurancePct, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(formularyentry.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceDate(); ok {
		_spec.SetField(formularyentry.FieldSourceDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsCurrent(); ok {
		_spec.SetField(formularyentry.FieldIsCurrent, field.TypeBool, value)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.PlanTable,
			Columns: []string{formularyentry.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.PlanTable,
			Columns: []string{formularyentry.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DrugCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.DrugTable,
			Columns: []string{formularyentry.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.DrugTable,
			Columns: []string{formularyentry.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{formularyentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FormularyEntryUpdateOne is the builder for updating a single FormularyEntry entity.
type FormularyEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FormularyEntryMutation
}

// SetTierLevel sets the "tier_level" field.
func (_u *FormularyEntryUpdateOne) SetTierLevel(v int) *FormularyEntryUpdateOne {
	_u.mutation.ResetTierLevel()
	_u.mutation.SetTierLevel(v)
	return _u
}

// SetNillableTierLevel sets the "tier_level" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableTierLevel(v *int) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetTierLevel(*v)
	}
	return _u
}

// AddTierLevel adds value to the "tier_level" field.
func (_u *FormularyEntryUpdateOne) AddTierLevel(v int) *FormularyEntryUpdateOne {
	_u.mutation.AddTierLevel(v)
	return _u
}

// ClearTierLevel clears the value of the "tier_level" field.
func (_u *FormularyEntryUpdateOne) ClearTierLevel() *FormularyEntryUpdateOne {
	_u.mutation.ClearTierLevel()
	return _u
}

// SetTierName sets the "tier_name" field.
func (_u *FormularyEntryUpdateOne) SetTierName(v string) *FormularyEntryUpdateOne {
	_u.mutation.SetTierName(v)
	return _u
}

// SetNillableTierName sets the "tier_name" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableTierName(v *string) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetTierName(*v)
	}
	return _u
}

// ClearTierName clears the value of the "tier_name" field.
func (_u *FormularyEntryUpdateOne) ClearTierName() *FormularyEntryUpdateOne {
	_u.mutation.ClearTierName()
	return _u
}

// SetPriorAuthRequired sets the "prior_auth_required" field.
func (_u *FormularyEntryUpdateOne) SetPriorAuthRequired(v bool) *FormularyEntryUpdateOne {
	_u.mutation.SetPriorAuthRequired(v)
	return _u
}

// SetNillablePriorAuthRequired sets the "prior_auth_required" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillablePriorAuthRequired(v *bool) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetPriorAuthRequired(*v)
	}
	return _u
}

// SetStepTherapy sets the "step_therapy" field.
func (_u *FormularyEntryUpdateOne) SetStepTherapy(v bool) *FormularyEntryUpdateOne {
	_u.mutation.SetStepTherapy(v)
	return _u
}

// SetNillableStepTherapy sets the "step_therapy" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableStepTherapy(v *bool) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetStepTherapy(*v)
	}
	return _u
}

// SetQuantityLimit sets the "quantity_limit" field.
func (_u *FormularyEntryUpdateOne) SetQuantityLimit(v bool) *FormularyEntryUpdateOne {
	_u.mutation.SetQuantityLimit(v)
	return _u
}

// SetNillableQuantityLimit sets the "quantity_limit" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableQuantityLimit(v *bool) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetQuantityLimit(*v)
	}
	return _u
}

// SetQuantityLimitAmount sets the "quantity_limit_amount" field.
func (_u *FormularyEntryUpdateOne) SetQuantityLimitAmount(v float64) *FormularyEntryUpdateOne {
	_u.mutation.ResetQuantityLimitAmount()
	_u.mutation.SetQuantityLimitAmount(v)
	return _u
}

// SetNillableQuantityLimitAmount sets the "quantity_limit_amount" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableQuantityLimitAmount(v *float64) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetQuantityLimitAmount(*v)
	}
	return _u
}

// AddQuantityLimitAmount adds value to the "quantity_limit_amount" field.
func (_u *FormularyEntryUpdateOne) AddQuantityLimitAmount(v float64) *FormularyEntryUpdateOne {
	_u.mutation.AddQuantityLimitAmount(v)
	return _u
}

// ClearQuantityLimitAmount clears the value of the "quantity_limit_amount" field.
func (_u *FormularyEntryUpdateOne) ClearQuantityLimitAmount() *FormularyEntryUpdateOne {
	_u.mutation.ClearQuantityLimitAmount()
	return _u
}

// SetQuantityLimitDays sets the "quantity_limit_days" field.
func (_u *FormularyEntryUpdateOne) SetQuantityLimitDays(v int) *FormularyEntryUpdateOne {
	_u.mutation.ResetQuantityLimitDays()
	_u.mutation.SetQuantityLimitDays(v)
	return _u
}

// SetNillableQuantityLimitDays sets the "quantity_limit_days" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableQuantityLimitDays(v *int) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetQuantityLimitDays(*v)
	}
	return _u
}

// AddQuantityLimitDays adds value to the "quantity_limit_days" field.
func (_u *FormularyEntryUpdateOne) AddQuantityLimitDays(v int) *FormularyEntryUpdateOne {
	_u.mutation.AddQuantityLimitDays(v)
	return _u
}

// ClearQuantityLimitDays clears the value of the "quantity_limit_days" field.
func (_u *FormularyEntryUpdateOne) ClearQuantityLimitDays() *FormularyEntryUpdateOne {
	_u.mutation.ClearQuantityLimitDays()
	return _u
}

// SetCopayAmount sets the "copay_amount" field.
func (_u *FormularyEntryUpdateOne) SetCopayAmount(v float64) *FormularyEntryUpdateOne {
	_u.mutation.ResetCopayAmount()
	_u.mutation.SetCopayAmount(v)
	return _u
}

// SetNillableCopayAmount sets the "copay_amount" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableCopayAmount(v *float64) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetCopayAmount(*v)
	}
	return _u
}

// AddCopayAmount adds value to the "copay_amount" field.
func (_u *FormularyEntryUpdateOne) AddCopayAmount(v float64) *FormularyEntryUpdateOne {
	_u.mutation.AddCopayAmount(v)
	return _u
}

// ClearCopayAmount clears the value of the "copay_amount" field.
func (_u *FormularyEntryUpdateOne) ClearCopayAmount() *FormularyEntryUpdateOne {
	_u.mutation.ClearCopayAmount()
	return _u
}

// SetCoinsurancePct sets the "coinsurance_pct" field.
func (_u *FormularyEntryUpdateOne) SetCoinsurancePct(v float64) *FormularyEntryUpdateOne {
	_u.mutation.ResetCoinsurancePct()
	_u.mutation.SetCoinsurancePct(v)
	return _u
}

// SetNillableCoinsurancePct sets the "coinsurance_pct" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableCoinsurancePct(v *float64) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetCoinsurancePct(*v)
	}
	return _u
}

// AddCoinsurancePct adds value to the "coinsurance_pct" field.
func (_u *FormularyEntryUpdateOne) AddCoinsurancePct(v float64) *FormularyEntryUpdateOne {
	_u.mutation.AddCoinsurancePct(v)
	return _u
}

// ClearCoinsurancePct clears the value of the "coinsurance_pct" field.
func (_u *FormularyEntryUpdateOne) ClearCoinsurancePct() *FormularyEntryUpdateOne {
	_u.mutation.ClearCoinsurancePct()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *FormularyEntryUpdateOne) SetSourceType(v string) *FormularyEntryUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableSourceType(v *string) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceDate sets the "source_date" field.
func (_u *FormularyEntryUpdateOne) SetSourceDate(v time.Time) *FormularyEntryUpdateOne {
	_u.mutation.SetSourceDate(v)
	return _u
}

// SetNillableSourceDate sets the "source_date" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableSourceDate(v *time.Time) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetSourceDate(*v)
	}
	return _u
}

// SetIsCurrent sets the "is_current" field.
func (_u *FormularyEntryUpdateOne) SetIsCurrent(v bool) *FormularyEntryUpdateOne {
	_u.mutation.SetIsCurrent(v)
	return _u
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_u *FormularyEntryUpdateOne) SetNillableIsCurrent(v *bool) *FormularyEntryUpdateOne {
	if v != nil {
		_u.SetIsCurrent(*v)
	}
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *FormularyEntryUpdateOne) SetPlanID(id int) *FormularyEntryUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *FormularyEntryUpdateOne) SetPlan(v *Plan) *FormularyEntryUpdateOne {
	return _u.SetPlanID(v.ID)
}

// SetDrugID sets the "drug" edge to the Drug entity by ID.
func (_u *FormularyEntryUpdateOne) SetDrugID(id int) *FormularyEntryUpdateOne {
	_u.mutation.SetDrugID(id)
	return _u
}

// SetDrug sets the "drug" edge to the Drug entity.
func (_u *FormularyEntryUpdateOne) SetDrug(v *Drug) *FormularyEntryUpdateOne {
	return _u.SetDrugID(v.ID)
}

// Mutation returns the FormularyEntryMutation object of the builder.
func (_u *FormularyEntryUpdateOne) Mutation() *FormularyEntryMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *FormularyEntryUpdateOne) ClearPlan() *FormularyEntryUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearDrug clears the "drug" edge to the Drug entity.
func (_u *FormularyEntryUpdateOne) ClearDrug() *FormularyEntryUpdateOne {
	_u.mutation.ClearDrug()
	return _u
}

// Where appends a list predicates to the FormularyEntryUpdate builder.
func (_u *FormularyEntryUpdateOne) Where(ps ...predicate.FormularyEntry) *FormularyEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FormularyEntryUpdateOne) Select(field string, fields ...string) *FormularyEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FormularyEntry entity.
func (_u *FormularyEntryUpdateOne) Save(ctx context.Context) (*FormularyEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FormularyEntryUpdateOne) SaveX(ctx context.Context) *FormularyEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FormularyEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FormularyEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FormularyEntryUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := formularyentry.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "FormularyEntry.source_type": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FormularyEntry.plan"`)
	}
	if _u.mutation.DrugCleared() && len(_u.mutation.DrugIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FormularyEntry.drug"`)
	}
	return nil
}

func (_u *FormularyEntryUpdateOne) sqlSave(ctx context.Context) (_node *FormularyEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(formularyentry.Table, formularyentry.Columns, sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FormularyEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, formularyentry.FieldID)
		for _, f := range fields {
			if !formularyentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != formularyentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TierLevel(); ok {
		_spec.SetField(formularyentry.FieldTierLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTierLevel(); ok {
		_spec.AddField(formularyentry.FieldTierLevel, field.TypeInt, value)
	}
	if _u.mutation.TierLevelCleared() {
		_spec.ClearField(formularyentry.FieldTierLevel, field.TypeInt)
	}
	if value, ok := _u.mutation.TierName(); ok {
		_spec.SetField(formularyentry.FieldTierName, field.TypeString, value)
	}
	if _u.mutation.TierNameCleared() {
		_spec.ClearField(formularyentry.FieldTierName, field.TypeString)
	}
	if value, ok := _u.mutation.PriorAuthRequired(); ok {
		_spec.SetField(formularyentry.FieldPriorAuthRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StepTherapy(); ok {
		_spec.SetField(formularyentry.FieldStepTherapy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuantityLimit(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuantityLimitAmount(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantityLimitAmount(); ok {
		_spec.AddField(formularyentry.FieldQuantityLimitAmount, field.TypeFloat64, value)
	}
	if _u.mutation.QuantityLimitAmountCleared() {
		_spec.ClearField(formularyentry.FieldQuantityLimitAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QuantityLimitDays(); ok {
		_spec.SetField(formularyentry.FieldQuantityLimitDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantityLimitDays(); ok {
		_spec.AddField(formularyentry.FieldQuantityLimitDays, field.TypeInt, value)
	}
	if _u.mutation.QuantityLimitDaysCleared() {
		_spec.ClearField(formularyentry.FieldQuantityLimitDays, field.TypeInt)
	}
	if value, ok := _u.mutation.CopayAmount(); ok {
		_spec.SetField(formularyentry.FieldCopayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCopayAmount(); ok {
		_spec.AddField(formularyentry.FieldCopayAmount, field.TypeFloat64, value)
	}
	if _u.mutation.CopayAmountCleared() {
		_spec.ClearField(formularyentry.FieldCopayAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CoinsurancePct(); ok {
		_spec.SetField(formularyentry.FieldCoinsurancePct, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCoinsurancePct(); ok {
		_spec.AddField(formularyentry.FieldCoinsurancePct, field.TypeFloat64, value)
	}
	if _u.mutation.CoinsurancePctCleared() {
		_spec.ClearField(formularyentry.FieldCoinsurancePct, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(formularyentry.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceDate(); ok {
		_spec.SetField(formularyentry.FieldSourceDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsCurrent(); ok {
		_spec.SetField(formularyentry.FieldIsCurrent, field.TypeBool, value)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.PlanTable,
			Columns: []string{formularyentry.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.PlanTable,
			Columns: []string{formularyentry.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DrugCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.DrugTable,
			Columns: []string{formularyentry.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   formularyentry.DrugTable,
			Columns: []string{formularyentry.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drug.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FormularyEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{formularyentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
