// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/plan"
)

// FormularyEntry is the model entity for the FormularyEntry schema.
type FormularyEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TierLevel holds the value of the "tier_level" field.
	TierLevel int `json:"tier_level,omitempty"`
	// TierName holds the value of the "tier_name" field.
	TierName string `json:"tier_name,omitempty"`
	// PriorAuthRequired holds the value of the "prior_auth_required" field.
	PriorAuthRequired bool `json:"prior_auth_required,omitempty"`
	// StepTherapy holds the value of the "step_therapy" field.
	StepTherapy bool `json:"step_therapy,omitempty"`
	// QuantityLimit holds the value of the "quantity_limit" field.
	QuantityLimit bool `json:"quantity_limit,omitempty"`
	// QuantityLimitAmount holds the value of the "quantity_limit_amount" field.
	QuantityLimitAmount *float64 `json:"quantity_limit_amount,omitempty"`
	// QuantityLimitDays holds the value of the "quantity_limit_days" field.
	QuantityLimitDays *int `json:"quantity_limit_days,omitempty"`
	// CopayAmount holds the value of the "copay_amount" field.
	CopayAmount *float64 `json:"copay_amount,omitempty"`
	// CoinsurancePct holds the value of the "coinsurance_pct" field.
	CoinsurancePct *float64 `json:"coinsurance_pct,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceDate holds the value of the "source_date" field.
	SourceDate time.Time `json:"source_date,omitempty"`
	// IsCurrent holds the value of the "is_current" field.
	IsCurrent bool `json:"is_current,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FormularyEntryQuery when eager-loading is set.
	Edges                  FormularyEntryEdges `json:"edges"`
	drug_formulary_entries *int
	plan_formulary_entries *int
	selectValues           sql.SelectValues
}

// FormularyEntryEdges holds the relations/edges for other nodes in the graph.
type FormularyEntryEdges struct {
	// Plan holds the value of the plan edge.
	Plan *Plan `json:"plan,omitempty"`
	// Drug holds the value of the drug edge.
	Drug *Drug `json:"drug,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FormularyEntryEdges) PlanOrErr() (*Plan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// DrugOrErr returns the Drug value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FormularyEntryEdges) DrugOrErr() (*Drug, error) {
	if e.Drug != nil {
		return e.Drug, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: drug.Label}
	}
	return nil, &NotLoadedError{edge: "drug"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FormularyEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case formularyentry.FieldPriorAuthRequired, formularyentry.FieldStepTherapy, formularyentry.FieldQuantityLimit, formularyentry.FieldIsCurrent:
			values[i] = new(sql.NullBool)
		case formularyentry.FieldQuantityLimitAmount, formularyentry.FieldCopayAmount, formularyentry.FieldCoinsurancePct:
			values[i] = new(sql.NullFloat64)
		case formularyentry.FieldID, formularyentry.FieldTierLevel, formularyentry.FieldQuantityLimitDays:
			values[i] = new(sql.NullInt64)
		case formularyentry.FieldTierName, formularyentry.FieldSourceType:
			values[i] = new(sql.NullString)
		case formularyentry.FieldSourceDate, formularyentry.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case formularyentry.ForeignKeys[0]: // drug_formulary_entries
			values[i] = new(sql.NullInt64)
		case formularyentry.ForeignKeys[1]: // plan_formulary_entries
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FormularyEntry fields.
func (_m *FormularyEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case formularyentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case formularyentry.FieldTierLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tier_level", values[i])
			} else if value.Valid {
				_m.TierLevel = int(value.Int64)
			}
		case formularyentry.FieldTierName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier_name", values[i])
			} else if value.Valid {
				_m.TierName = value.String
			}
		case formularyentry.FieldPriorAuthRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field prior_auth_required", values[i])
			} else if value.Valid {
				_m.PriorAuthRequired = value.Bool
			}
		case formularyentry.FieldStepTherapy:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field step_therapy", values[i])
			} else if value.Valid {
				_m.StepTherapy = value.Bool
			}
		case formularyentry.FieldQuantityLimit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field quantity_limit", values[i])
			} else if value.Valid {
				_m.QuantityLimit = value.Bool
			}
		case formularyentry.FieldQuantityLimitAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity_limit_amount", values[i])
			} else if value.Valid {
				_m.QuantityLimitAmount = new(float64)
				*_m.QuantityLimitAmount = value.Float64
			}
		case formularyentry.FieldQuantityLimitDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity_limit_days", values[i])
			} else if value.Valid {
				_m.QuantityLimitDays = new(int)
				*_m.QuantityLimitDays = int(value.Int64)
			}
		case formularyentry.FieldCopayAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field copay_amount", values[i])
			} else if value.Valid {
				_m.CopayAmount = new(float64)
				*_m.CopayAmount = value.Float64
			}
		case formularyentry.FieldCoinsurancePct:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field coinsurance_pct", values[i])
			} else if value.Valid {
				_m.CoinsurancePct = new(float64)
				*_m.CoinsurancePct = value.Float64
			}
		case formularyentry.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case formularyentry.FieldSourceDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field source_date", values[i])
			} else if value.Valid {
				_m.SourceDate = value.Time
			}
		case formularyentry.FieldIsCurrent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_current", values[i])
			} else if value.Valid {
				_m.IsCurrent = value.Bool
			}
		case formularyentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case formularyentry.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field drug_formulary_entries", value)
			} else if value.Valid {
				_m.drug_formulary_entries = new(int)
				*_m.drug_formulary_entries = int(value.Int64)
			}
		case formularyentry.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field plan_formulary_entries", value)
			} else if value.Valid {
				_m.plan_formulary_entries = new(int)
				*_m.plan_formulary_entries = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FormularyEntry.
// This includes values selected through modifiers, order, etc.
func (_m *FormularyEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the FormularyEntry entity.
func (_m *FormularyEntry) QueryPlan() *PlanQuery {
	return NewFormularyEntryClient(_m.config).QueryPlan(_m)
}

// QueryDrug queries the "drug" edge of the FormularyEntry entity.
func (_m *FormularyEntry) QueryDrug() *DrugQuery {
	return NewFormularyEntryClient(_m.config).QueryDrug(_m)
}

// Update returns a builder for updating this FormularyEntry.
// Note that you need to call FormularyEntry.Unwrap() before calling this method if this FormularyEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FormularyEntry) Update() *FormularyEntryUpdateOne {
	return NewFormularyEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FormularyEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FormularyEntry) Unwrap() *FormularyEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FormularyEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FormularyEntry) String() string {
	var builder strings.Builder
	builder.WriteString("FormularyEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tier_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.TierLevel))
	builder.WriteString(", ")
	builder.WriteString("tier_name=")
	builder.WriteString(_m.TierName)
	builder.WriteString(", ")
	builder.WriteString("prior_auth_required=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriorAuthRequired))
	builder.WriteString(", ")
	builder.WriteString("step_therapy=")
	builder.WriteString(fmt.Sprintf("%v", _m.StepTherapy))
	builder.WriteString(", ")
	builder.WriteString("quantity_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuantityLimit))
	builder.WriteString(", ")
	if v := _m.QuantityLimitAmount; v != nil {
		builder.WriteString("quantity_limit_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.QuantityLimitDays; v != nil {
		builder.WriteString("quantity_limit_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CopayAmount; v != nil {
		builder.WriteString("copay_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CoinsurancePct; v != nil {
		builder.WriteString("coinsurance_pct=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_date=")
	builder.WriteString(_m.SourceDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_current=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCurrent))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FormularyEntries is a parsable slice of FormularyEntry.
type FormularyEntries []*FormularyEntry
