// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/plan"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// PlanUpdate is the builder for updating Plan entities.
type PlanUpdate struct {
	config
	hooks    []Hook
	mutation *PlanMutation
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdate) Where(ps ...predicate.Plan) *PlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContractID sets the "contract_id" field.
func (_u *PlanUpdate) SetContractID(v string) *PlanUpdate {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableContractID(v *string) *PlanUpdate {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PlanUpdate) SetPlanID(v string) *PlanUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PlanUpdate) SetNillablePlanID(v *string) *PlanUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetSegmentID sets the "segment_id" field.
func (_u *PlanUpdate) SetSegmentID(v string) *PlanUpdate {
	_u.mutation.SetSegmentID(v)
	return _u
}

// SetNillableSegmentID sets the "segment_id" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableSegmentID(v *string) *PlanUpdate {
	if v != nil {
		_u.SetSegmentID(*v)
	}
	return _u
}

// SetContractName sets the "contract_name" field.
func (_u *PlanUpdate) SetContractName(v string) *PlanUpdate {
	_u.mutation.SetContractName(v)
	return _u
}

// SetNillableContractName sets the "contract_name" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableContractName(v *string) *PlanUpdate {
	if v != nil {
		_u.SetContractName(*v)
	}
	return _u
}

// ClearContractName clears the value of the "contract_name" field.
func (_u *PlanUpdate) ClearContractName() *PlanUpdate {
	_u.mutation.ClearContractName()
	return _u
}

// SetPlanName sets the "plan_name" field.
func (_u *PlanUpdate) SetPlanName(v string) *PlanUpdate {
	_u.mutation.SetPlanName(v)
	return _u
}

// SetNillablePlanName sets the "plan_name" field if the given value is not nil.
func (_u *PlanUpdate) SetNillablePlanName(v *string) *PlanUpdate {
	if v != nil {
		_u.SetPlanName(*v)
	}
	return _u
}

// ClearPlanName clears the value of the "plan_name" field.
func (_u *PlanUpdate) ClearPlanName() *PlanUpdate {
	_u.mutation.ClearPlanName()
	return _u
}

// SetFormularyID sets the "formulary_id" field.
func (_u *PlanUpdate) SetFormularyID(v string) *PlanUpdate {
	_u.mutation.SetFormularyID(v)
	return _u
}

// SetNillableFormularyID sets the "formulary_id" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableFormularyID(v *string) *PlanUpdate {
	if v != nil {
		_u.SetFormularyID(*v)
	}
	return _u
}

// SetPlanType sets the "plan_type" field.
func (_u *PlanUpdate) SetPlanType(v string) *PlanUpdate {
	_u.mutation.SetPlanType(v)
	return _u
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_u *PlanUpdate) SetNillablePlanType(v *string) *PlanUpdate {
	if v != nil {
		_u.SetPlanType(*v)
	}
	return _u
}

// ClearPlanType clears the value of the "plan_type" field.
func (_u *PlanUpdate) ClearPlanType() *PlanUpdate {
	_u.mutation.ClearPlanType()
	return _u
}

// SetSnpType sets the "snp_type" field.
func (_u *PlanUpdate) SetSnpType(v string) *PlanUpdate {
	_u.mutation.SetSnpType(v)
	return _u
}

// SetNillableSnpType sets the "snp_type" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableSnpType(v *string) *PlanUpdate {
	if v != nil {
		_u.SetSnpType(*v)
	}
	return _u
}

// ClearSnpType clears the value of the "snp_type" field.
func (_u *PlanUpdate) ClearSnpType() *PlanUpdate {
	_u.mutation.ClearSnpType()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlanUpdate) SetUpdatedAt(v time.Time) *PlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddFormularyEntryIDs adds the "formulary_entries" edge to the FormularyEntry entity by IDs.
func (_u *PlanUpdate) AddFormularyEntryIDs(ids ...int) *PlanUpdate {
	_u.mutation.AddFormularyEntryIDs(ids...)
	return _u
}

// AddFormularyEntries adds the "formulary_entries" edges to the FormularyEntry entity.
func (_u *PlanUpdate) AddFormularyEntries(v ...*FormularyEntry) *PlanUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFormularyEntryIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdate) Mutation() *PlanMutation {
	return _u.mutation
}

// ClearFormularyEntries clears all "formulary_entries" edges to the FormularyEntry entity.
func (_u *PlanUpdate) ClearFormularyEntries() *PlanUpdate {
	_u.mutation.ClearFormularyEntries()
	return _u
}

// RemoveFormularyEntryIDs removes the "formulary_entries" edge to FormularyEntry entities by IDs.
func (_u *PlanUpdate) RemoveFormularyEntryIDs(ids ...int) *PlanUpdate {
	_u.mutation.RemoveFormularyEntryIDs(ids...)
	return _u
}

// RemoveFormularyEntries removes "formulary_entries" edges to FormularyEntry entities.
func (_u *PlanUpdate) RemoveFormularyEntries(v ...*FormularyEntry) *PlanUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFormularyEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdate) check() error {
	if v, ok := _u.mutation.ContractID(); ok {
		if err := plan.ContractIDValidator(v); err != nil {
			return &ValidationError{Name: "contract_id", err: fmt.Errorf(`ent: validator failed for field "Plan.contract_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanID(); ok {
		if err := plan.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "Plan.plan_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SegmentID(); ok {
		if err := plan.SegmentIDValidator(v); err != nil {
			return &ValidationError{Name: "segment_id", err: fmt.Errorf(`ent: validator failed for field "Plan.segment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FormularyID(); ok {
		if err := plan.FormularyIDValidator(v); err != nil {
			return &ValidationError{Name: "formulary_id", err: fmt.Errorf(`ent: validator failed for field "Plan.formulary_id": %w`, err)}
		}
	}
	return nil
}

func (_u *PlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(plan.FieldContractID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(plan.FieldPlanID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SegmentID(); ok {
		_spec.SetField(plan.FieldSegmentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractName(); ok {
		_spec.SetField(plan.FieldContractName, field.TypeString, value)
	}
	if _u.mutation.ContractNameCleared() {
		_spec.ClearField(plan.FieldContractName, field.TypeString)
	}
	if value, ok := _u.mutation.PlanName(); ok {
		_spec.SetField(plan.FieldPlanName, field.TypeString, value)
	}
	if _u.mutation.PlanNameCleared() {
		_spec.ClearField(plan.FieldPlanName, field.TypeString)
	}
	if value, ok := _u.mutation.FormularyID(); ok {
		_spec.SetField(plan.FieldFormularyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlanType(); ok {
		_spec.SetField(plan.FieldPlanType, field.TypeString, value)
	}
	if _u.mutation.PlanTypeCleared() {
		_spec.ClearField(plan.FieldPlanType, field.TypeString)
	}
	if value, ok := _u.mutation.SnpType(); ok {
		_spec.SetField(plan.FieldSnpType, field.TypeString, value)
	}
	if _u.mutation.SnpTypeCleared() {
		_spec.ClearField(plan.FieldSnpType, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FormularyEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.FormularyEntriesTable,
			Columns: []string{plan.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFormularyEntriesIDs(); len(nodes) > 0 && !_u.mutation.FormularyEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.FormularyEntriesTable,
			Columns: []string{plan.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FormularyEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.FormularyEntriesTable,
			Columns: []string{plan.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlanUpdateOne is the builder for updating a single Plan entity.
type PlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlanMutation
}

// SetContractID sets the "contract_id" field.
func (_u *PlanUpdateOne) SetContractID(v string) *PlanUpdateOne {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableContractID(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PlanUpdateOne) SetPlanID(v string) *PlanUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillablePlanID(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetSegmentID sets the "segment_id" field.
func (_u *PlanUpdateOne) SetSegmentID(v string) *PlanUpdateOne {
	_u.mutation.SetSegmentID(v)
	return _u
}

// SetNillableSegmentID sets the "segment_id" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableSegmentID(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetSegmentID(*v)
	}
	return _u
}

// SetContractName sets the "contract_name" field.
func (_u *PlanUpdateOne) SetContractName(v string) *PlanUpdateOne {
	_u.mutation.SetContractName(v)
	return _u
}

// SetNillableContractName sets the "contract_name" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableContractName(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetContractName(*v)
	}
	return _u
}

// ClearContractName clears the value of the "contract_name" field.
func (_u *PlanUpdateOne) ClearContractName() *PlanUpdateOne {
	_u.mutation.ClearContractName()
	return _u
}

// SetPlanName sets the "plan_name" field.
func (_u *PlanUpdateOne) SetPlanName(v string) *PlanUpdateOne {
	_u.mutation.SetPlanName(v)
	return _u
}

// SetNillablePlanName sets the "plan_name" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillablePlanName(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetPlanName(*v)
	}
	return _u
}

// ClearPlanName clears the value of the "plan_name" field.
func (_u *PlanUpdateOne) ClearPlanName() *PlanUpdateOne {
	_u.mutation.ClearPlanName()
	return _u
}

// SetFormularyID sets the "formulary_id" field.
func (_u *PlanUpdateOne) SetFormularyID(v string) *PlanUpdateOne {
	_u.mutation.SetFormularyID(v)
	return _u
}

// SetNillableFormularyID sets the "formulary_id" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableFormularyID(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetFormularyID(*v)
	}
	return _u
}

// SetPlanType sets the "plan_type" field.
func (_u *PlanUpdateOne) SetPlanType(v string) *PlanUpdateOne {
	_u.mutation.SetPlanType(v)
	return _u
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillablePlanType(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetPlanType(*v)
	}
	return _u
}

// ClearPlanType clears the value of the "plan_type" field.
func (_u *PlanUpdateOne) ClearPlanType() *PlanUpdateOne {
	_u.mutation.ClearPlanType()
	return _u
}

// SetSnpType sets the "snp_type" field.
func (_u *PlanUpdateOne) SetSnpType(v string) *PlanUpdateOne {
	_u.mutation.SetSnpType(v)
	return _u
}

// SetNillableSnpType sets the "snp_type" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableSnpType(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetSnpType(*v)
	}
	return _u
}

// ClearSnpType clears the value of the "snp_type" field.
func (_u *PlanUpdateOne) ClearSnpType() *PlanUpdateOne {
	_u.mutation.ClearSnpType()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlanUpdateOne) SetUpdatedAt(v time.Time) *PlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddFormularyEntryIDs adds the "formulary_entries" edge to the FormularyEntry entity by IDs.
func (_u *PlanUpdateOne) AddFormularyEntryIDs(ids ...int) *PlanUpdateOne {
	_u.mutation.AddFormularyEntryIDs(ids...)
	return _u
}

// AddFormularyEntries adds the "formulary_entries" edges to the FormularyEntry entity.
func (_u *PlanUpdateOne) AddFormularyEntries(v ...*FormularyEntry) *PlanUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFormularyEntryIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdateOne) Mutation() *PlanMutation {
	return _u.mutation
}

// ClearFormularyEntries clears all "formulary_entries" edges to the FormularyEntry entity.
func (_u *PlanUpdateOne) ClearFormularyEntries() *PlanUpdateOne {
	_u.mutation.ClearFormularyEntries()
	return _u
}

// RemoveFormularyEntryIDs removes the "formulary_entries" edge to FormularyEntry entities by IDs.
func (_u *PlanUpdateOne) RemoveFormularyEntryIDs(ids ...int) *PlanUpdateOne {
	_u.mutation.RemoveFormularyEntryIDs(ids...)
	return _u
}

// RemoveFormularyEntries removes "formulary_entries" edges to FormularyEntry entities.
func (_u *PlanUpdateOne) RemoveFormularyEntries(v ...*FormularyEntry) *PlanUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFormularyEntryIDs(ids...)
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdateOne) Where(ps ...predicate.Plan) *PlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlanUpdateOne) Select(field string, fields ...string) *PlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Plan entity.
func (_u *PlanUpdateOne) Save(ctx context.Context) (*Plan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdateOne) SaveX(ctx context.Context) *Plan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdateOne) check() error {
	if v, ok := _u.mutation.ContractID(); ok {
		if err := plan.ContractIDValidator(v); err != nil {
			return &ValidationError{Name: "contract_id", err: fmt.Errorf(`ent: validator failed for field "Plan.contract_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanID(); ok {
		if err := plan.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "Plan.plan_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SegmentID(); ok {
		if err := plan.SegmentIDValidator(v); err != nil {
			return &ValidationError{Name: "segment_id", err: fmt.Errorf(`ent: validator failed for field "Plan.segment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FormularyID(); ok {
		if err := plan.FormularyIDValidator(v); err != nil {
			return &ValidationError{Name: "formulary_id", err: fmt.Errorf(`ent: validator failed for field "Plan.formulary_id": %w`, err)}
		}
	}
	return nil
}

func (_u *PlanUpdateOne) sqlSave(ctx context.Context) (_node *Plan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plan.FieldID)
		for _, f := range fields {
			if !plan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(plan.FieldContractID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(plan.FieldPlanID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SegmentID(); ok {
		_spec.SetField(plan.FieldSegmentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractName(); ok {
		_spec.SetField(plan.FieldContractName, field.TypeString, value)
	}
	if _u.mutation.ContractNameCleared() {
		_spec.ClearField(plan.FieldContractName, field.TypeString)
	}
	if value, ok := _u.mutation.PlanName(); ok {
		_spec.SetField(plan.FieldPlanName, field.TypeString, value)
	}
	if _u.mutation.PlanNameCleared() {
		_spec.ClearField(plan.FieldPlanName, field.TypeString)
	}
	if value, ok := _u.mutation.FormularyID(); ok {
		_spec.SetField(plan.FieldFormularyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlanType(); ok {
		_spec.SetField(plan.FieldPlanType, field.TypeString, value)
	}
	if _u.mutation.PlanTypeCleared() {
		_spec.ClearField(plan.FieldPlanType, field.TypeString)
	}
	if value, ok := _u.mutation.SnpType(); ok {
		_spec.SetField(plan.FieldSnpType, field.TypeString, value)
	}
	if _u.mutation.SnpTypeCleared() {
		_spec.ClearField(plan.FieldSnpType, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FormularyEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.FormularyEntriesTable,
			Columns: []string{plan.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFormularyEntriesIDs(); len(nodes) > 0 && !_u.mutation.FormularyEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.FormularyEntriesTable,
			Columns: []string{plan.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FormularyEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.FormularyEntriesTable,
			Columns: []string{plan.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Plan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
