// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/plan"
)

// PlanCreate is the builder for creating a Plan entity.
type PlanCreate struct {
	config
	mutation *PlanMutation
	hooks    []Hook
}

// SetContractID sets the "contract_id" field.
func (_c *PlanCreate) SetContractID(v string) *PlanCreate {
	_c.mutation.SetContractID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *PlanCreate) SetPlanID(v string) *PlanCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetSegmentID sets the "segment_id" field.
func (_c *PlanCreate) SetSegmentID(v string) *PlanCreate {
	_c.mutation.SetSegmentID(v)
	return _c
}

// SetContractName sets the "contract_name" field.
func (_c *PlanCreate) SetContractName(v string) *PlanCreate {
	_c.mutation.SetContractName(v)
	return _c
}

// SetNillableContractName sets the "contract_name" field if the given value is not nil.
func (_c *PlanCreate) SetNillableContractName(v *string) *PlanCreate {
	if v != nil {
		_c.SetContractName(*v)
	}
	return _c
}

// SetPlanName sets the "plan_name" field.
func (_c *PlanCreate) SetPlanName(v string) *PlanCreate {
	_c.mutation.SetPlanName(v)
	return _c
}

// SetNillablePlanName sets the "plan_name" field if the given value is not nil.
func (_c *PlanCreate) SetNillablePlanName(v *string) *PlanCreate {
	if v != nil {
		_c.SetPlanName(*v)
	}
	return _c
}

// SetFormularyID sets the "formulary_id" field.
func (_c *PlanCreate) SetFormularyID(v string) *PlanCreate {
	_c.mutation.SetFormularyID(v)
	return _c
}

// SetPlanType sets the "plan_type" field.
func (_c *PlanCreate) SetPlanType(v string) *PlanCreate {
	_c.mutation.SetPlanType(v)
	return _c
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_c *PlanCreate) SetNillablePlanType(v *string) *PlanCreate {
	if v != nil {
		_c.SetPlanType(*v)
	}
	return _c
}

// SetSnpType sets the "snp_type" field.
func (_c *PlanCreate) SetSnpType(v string) *PlanCreate {
	_c.mutation.SetSnpType(v)
	return _c
}

// SetNillableSnpType sets the "snp_type" field if the given value is not nil.
func (_c *PlanCreate) SetNillableSnpType(v *string) *PlanCreate {
	if v != nil {
		_c.SetSnpType(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlanCreate) SetCreatedAt(v time.Time) *PlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableCreatedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlanCreate) SetUpdatedAt(v time.Time) *PlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableUpdatedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddFormularyEntryIDs adds the "formulary_entries" edge to the FormularyEntry entity by IDs.
func (_c *PlanCreate) AddFormularyEntryIDs(ids ...int) *PlanCreate {
	_c.mutation.AddFormularyEntryIDs(ids...)
	return _c
}

// AddFormularyEntries adds the "formulary_entries" edges to the FormularyEntry entity.
func (_c *PlanCreate) AddFormularyEntries(v ...*FormularyEntry) *PlanCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFormularyEntryIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_c *PlanCreate) Mutation() *PlanMutation {
	return _c.mutation
}

// Save creates the Plan in the database.
func (_c *PlanCreate) Save(ctx context.Context) (*Plan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlanCreate) SaveX(ctx context.Context) *Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlanCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := plan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := plan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlanCreate) check() error {
	if _, ok := _c.mutation.ContractID(); !ok {
		return &ValidationError{Name: "contract_id", err: errors.New(`ent: missing required field "Plan.contract_id"`)}
	}
	if v, ok := _c.mutation.ContractID(); ok {
		if err := plan.ContractIDValidator(v); err != nil {
			return &ValidationError{Name: "contract_id", err: fmt.Errorf(`ent: validator failed for field "Plan.contract_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "Plan.plan_id"`)}
	}
	if v, ok := _c.mutation.PlanID(); ok {
		if err := plan.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "Plan.plan_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SegmentID(); !ok {
		return &ValidationError{Name: "segment_id", err: errors.New(`ent: missing required field "Plan.segment_id"`)}
	}
	if v, ok := _c.mutation.SegmentID(); ok {
		if err := plan.SegmentIDValidator(v); err != nil {
			return &ValidationError{Name: "segment_id", err: fmt.Errorf(`ent: validator failed for field "Plan.segment_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FormularyID(); !ok {
		return &ValidationError{Name: "formulary_id", err: errors.New(`ent: missing required field "Plan.formulary_id"`)}
	}
	if v, ok := _c.mutation.FormularyID(); ok {
		if err := plan.FormularyIDValidator(v); err != nil {
			return &ValidationError{Name: "formulary_id", err: fmt.Errorf(`ent: validator failed for field "Plan.formulary_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Plan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Plan.updated_at"`)}
	}
	return nil
}

func (_c *PlanCreate) sqlSave(ctx context.Context) (*Plan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlanCreate) createSpec() (*Plan, *sqlgraph.CreateSpec) {
	var (
		_node = &Plan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plan.Table, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ContractID(); ok {
		_spec.SetField(plan.FieldContractID, field.TypeString, value)
		_node.ContractID = value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(plan.FieldPlanID, field.TypeString, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.SegmentID(); ok {
		_spec.SetField(plan.FieldSegmentID, field.TypeString, value)
		_node.SegmentID = value
	}
	if value, ok := _c.mutation.ContractName(); ok {
		_spec.SetField(plan.FieldContractName, field.TypeString, value)
		_node.ContractName = value
	}
	if value, ok := _c.mutation.PlanName(); ok {
		_spec.SetField(plan.FieldPlanName, field.TypeString, value)
		_node.PlanName = value
	}
	if value, ok := _c.mutation.FormularyID(); ok {
		_spec.SetField(plan.FieldFormularyID, field.TypeString, value)
		_node.FormularyID = value
	}
	if value, ok := _c.mutation.PlanType(); ok {
		_spec.SetField(plan.FieldPlanType, field.TypeString, value)
		_node.PlanType = value
	}
	if value, ok := _c.mutation.SnpType(); ok {
		_spec.SetField(plan.FieldSnpType, field.TypeString, value)
		_node.SnpType = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(plan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.FormularyEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.FormularyEntriesTable,
			Columns: []string{plan.FormularyEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(formularyentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlanCreateBulk is the builder for creating many Plan entities in bulk.
type PlanCreateBulk struct {
	config
	err      error
	builders []*PlanCreate
}

// Save creates the Plan entities in the database.
func (_c *PlanCreateBulk) Save(ctx context.Context) ([]*Plan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlanCreateBulk) SaveX(ctx context.Context) []*Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
