// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kyanaman/formularycheck/ent/plan"
)

// Plan is the model entity for the Plan schema.
type Plan struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ContractID holds the value of the "contract_id" field.
	ContractID string `json:"contract_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID string `json:"plan_id,omitempty"`
	// SegmentID holds the value of the "segment_id" field.
	SegmentID string `json:"segment_id,omitempty"`
	// ContractName holds the value of the "contract_name" field.
	ContractName string `json:"contract_name,omitempty"`
	// PlanName holds the value of the "plan_name" field.
	PlanName string `json:"plan_name,omitempty"`
	// FormularyID holds the value of the "formulary_id" field.
	FormularyID string `json:"formulary_id,omitempty"`
	// PlanType holds the value of the "plan_type" field.
	PlanType string `json:"plan_type,omitempty"`
	// SnpType holds the value of the "snp_type" field.
	SnpType string `json:"snp_type,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlanQuery when eager-loading is set.
	Edges        PlanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlanEdges holds the relations/edges for other nodes in the graph.
type PlanEdges struct {
	// FormularyEntries holds the value of the formulary_entries edge.
	FormularyEntries []*FormularyEntry `json:"formulary_entries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FormularyEntriesOrErr returns the FormularyEntries value or an error if the edge
// was not loaded in eager-loading.
func (e PlanEdges) FormularyEntriesOrErr() ([]*FormularyEntry, error) {
	if e.loadedTypes[0] {
		return e.FormularyEntries, nil
	}
	return nil, &NotLoadedError{edge: "formulary_entries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Plan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plan.FieldID:
			values[i] = new(sql.NullInt64)
		case plan.FieldContractID, plan.FieldPlanID, plan.FieldSegmentID, plan.FieldContractName, plan.FieldPlanName, plan.FieldFormularyID, plan.FieldPlanType, plan.FieldSnpType:
			values[i] = new(sql.NullString)
		case plan.FieldCreatedAt, plan.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Plan fields.
func (_m *Plan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case plan.FieldContractID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contract_id", values[i])
			} else if value.Valid {
				_m.ContractID = value.String
			}
		case plan.FieldPlanID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.String
			}
		case plan.FieldSegmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field segment_id", values[i])
			} else if value.Valid {
				_m.SegmentID = value.String
			}
		case plan.FieldContractName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contract_name", values[i])
			} else if value.Valid {
				_m.ContractName = value.String
			}
		case plan.FieldPlanName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_name", values[i])
			} else if value.Valid {
				_m.PlanName = value.String
			}
		case plan.FieldFormularyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field formulary_id", values[i])
			} else if value.Valid {
				_m.FormularyID = value.String
			}
		case plan.FieldPlanType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_type", values[i])
			} else if value.Valid {
				_m.PlanType = value.String
			}
		case plan.FieldSnpType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field snp_type", values[i])
			} else if value.Valid {
				_m.SnpType = value.String
			}
		case plan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case plan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Plan.
// This includes values selected through modifiers, order, etc.
func (_m *Plan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFormularyEntries queries the "formulary_entries" edge of the Plan entity.
func (_m *Plan) QueryFormularyEntries() *FormularyEntryQuery {
	return NewPlanClient(_m.config).QueryFormularyEntries(_m)
}

// Update returns a builder for updating this Plan.
// Note that you need to call Plan.Unwrap() before calling this method if this Plan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Plan) Update() *PlanUpdateOne {
	return NewPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Plan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Plan) Unwrap() *Plan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Plan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Plan) String() string {
	var builder strings.Builder
	builder.WriteString("Plan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("contract_id=")
	builder.WriteString(_m.ContractID)
	builder.WriteString(", ")
	builder.WriteString("plan_id=")
	builder.WriteString(_m.PlanID)
	builder.WriteString(", ")
	builder.WriteString("segment_id=")
	builder.WriteString(_m.SegmentID)
	builder.WriteString(", ")
	builder.WriteString("contract_name=")
	builder.WriteString(_m.ContractName)
	builder.WriteString(", ")
	builder.WriteString("plan_name=")
	builder.WriteString(_m.PlanName)
	builder.WriteString(", ")
	builder.WriteString("formulary_id=")
	builder.WriteString(_m.FormularyID)
	builder.WriteString(", ")
	builder.WriteString("plan_type=")
	builder.WriteString(_m.PlanType)
	builder.WriteString(", ")
	builder.WriteString("snp_type=")
	builder.WriteString(_m.SnpType)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Plans is a parsable slice of Plan.
type Plans []*Plan
