// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/kyanaman/formularycheck/ent/drug"
	"github.com/kyanaman/formularycheck/ent/drugndcmap"
	"github.com/kyanaman/formularycheck/ent/formularyentry"
	"github.com/kyanaman/formularycheck/ent/plan"
	"github.com/kyanaman/formularycheck/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	drugFields := schema.Drug{}.Fields()
	_ = drugFields
	// drugDescRxcui is the schema descriptor for rxcui field.
	drugDescRxcui := drugFields[0].Descriptor()
	// drug.RxcuiValidator is a validator for the "rxcui" field. It is called by the builders before save.
	drug.RxcuiValidator = drugDescRxcui.Validators[0].(func(string) error)
	// drugDescDrugName is the schema descriptor for drug_name field.
	drugDescDrugName := drugFields[1].Descriptor()
	// drug.DrugNameValidator is a validator for the "drug_name" field. It is called by the builders before save.
	drug.DrugNameValidator = drugDescDrugName.Validators[0].(func(string) error)
	// drugDescIsSpecialty is the schema descriptor for is_specialty field.
	drugDescIsSpecialty := drugFields[8].Descriptor()
	// drug.DefaultIsSpecialty holds the default value on creation for the is_specialty field.
	drug.DefaultIsSpecialty = drugDescIsSpecialty.Default.(bool)
	// drugDescIsControlled is the schema descriptor for is_controlled field.
	drugDescIsControlled := drugFields[9].Descriptor()
	// drug.DefaultIsControlled holds the default value on creation for the is_controlled field.
	drug.DefaultIsControlled = drugDescIsControlled.Default.(bool)
	// drugDescLastRxnormSync is the schema descriptor for last_rxnorm_sync field.
	drugDescLastRxnormSync := drugFields[11].Descriptor()
	// drug.DefaultLastRxnormSync holds the default value on creation for the last_rxnorm_sync field.
	drug.DefaultLastRxnormSync = drugDescLastRxnormSync.Default.(func() time.Time)
	// drugDescCreatedAt is the schema descriptor for created_at field.
	drugDescCreatedAt := drugFields[12].Descriptor()
	// drug.DefaultCreatedAt holds the default value on creation for the created_at field.
	drug.DefaultCreatedAt = drugDescCreatedAt.Default.(func() time.Time)
	// drugDescUpdatedAt is the schema descriptor for updated_at field.
	drugDescUpdatedAt := drugFields[13].Descriptor()
	// drug.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	drug.DefaultUpdatedAt = drugDescUpdatedAt.Default.(func() time.Time)
	// drug.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	drug.UpdateDefaultUpdatedAt = drugDescUpdatedAt.UpdateDefault.(func() time.Time)
	drugndcmapFields := schema.DrugNdcMap{}.Fields()
	_ = drugndcmapFields
	// drugndcmapDescNdc is the schema descriptor for ndc field.
	drugndcmapDescNdc := drugndcmapFields[0].Descriptor()
	// drugndcmap.NdcValidator is a validator for the "ndc" field. It is called by the builders before save.
	drugndcmap.NdcValidator = drugndcmapDescNdc.Validators[0].(func(string) error)
	// drugndcmapDescNdcStatus is the schema descriptor for ndc_status field.
	drugndcmapDescNdcStatus := drugndcmapFields[1].Descriptor()
	// drugndcmap.NdcStatusValidator is a validator for the "ndc_status" field. It is called by the builders before save.
	drugndcmap.NdcStatusValidator = drugndcmapDescNdcStatus.Validators[0].(func(string) error)
	// drugndcmapDescCreatedAt is the schema descriptor for created_at field.
	drugndcmapDescCreatedAt := drugndcmapFields[6].Descriptor()
	// drugndcmap.DefaultCreatedAt holds the default value on creation for the created_at field.
	drugndcmap.DefaultCreatedAt = drugndcmapDescCreatedAt.Default.(func() time.Time)
	formularyentryFields := schema.FormularyEntry{}.Fields()
	_ = formularyentryFields
	// formularyentryDescPriorAuthRequired is the schema descriptor for prior_auth_required field.
	formularyentryDescPriorAuthRequired := formularyentryFields[2].Descriptor()
	// formularyentry.DefaultPriorAuthRequired holds the default value on creation for the prior_auth_required field.
	formularyentry.DefaultPriorAuthRequired = formularyentryDescPriorAuthRequired.Default.(bool)
	// formularyentryDescStepTherapy is the schema descriptor for step_therapy field.
	formularyentryDescStepTherapy := formularyentryFields[3].Descriptor()
	// formularyentry.DefaultStepTherapy holds the default value on creation for the step_therapy field.
	formularyentry.DefaultStepTherapy = formularyentryDescStepTherapy.Default.(bool)
	// formularyentryDescQuantityLimit is the schema descriptor for quantity_limit field.
	formularyentryDescQuantityLimit := formularyentryFields[4].Descriptor()
	// formularyentry.DefaultQuantityLimit holds the default value on creation for the quantity_limit field.
	formularyentry.DefaultQuantityLimit = formularyentryDescQuantityLimit.Default.(bool)
	// formularyentryDescSourceType is the schema descriptor for source_type field.
	formularyentryDescSourceType := formularyentryFields[9].Descriptor()
	// formularyentry.SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	formularyentry.SourceTypeValidator = formularyentryDescSourceType.Validators[0].(func(string) error)
	// formularyentryDescIsCurrent is the schema descriptor for is_current field.
	formularyentryDescIsCurrent := formularyentryFields[11].Descriptor()
	// formularyentry.DefaultIsCurrent holds the default value on creation for the is_current field.
	formularyentry.DefaultIsCurrent = formularyentryDescIsCurrent.Default.(bool)
	// formularyentryDescCreatedAt is the schema descriptor for created_at field.
	formularyentryDescCreatedAt := formularyentryFields[12].Descriptor()
	// formularyentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	formularyentry.DefaultCreatedAt = formularyentryDescCreatedAt.Default.(func() time.Time)
	planFields := schema.Plan{}.Fields()
	_ = planFields
	// planDescContractID is the schema descriptor for contract_id field.
	planDescContractID := planFields[0].Descriptor()
	// plan.ContractIDValidator is a validator for the "contract_id" field. It is called by the builders before save.
	plan.ContractIDValidator = planDescContractID.Validators[0].(func(string) error)
	// planDescPlanID is the schema descriptor for plan_id field.
	planDescPlanID := planFields[1].Descriptor()
	// plan.PlanIDValidator is a validator for the "plan_id" field. It is called by the builders before save.
	plan.PlanIDValidator = planDescPlanID.Validators[0].(func(string) error)
	// planDescSegmentID is the schema descriptor for segment_id field.
	planDescSegmentID := planFields[2].Descriptor()
	// plan.SegmentIDValidator is a validator for the "segment_id" field. It is called by the builders before save.
	plan.SegmentIDValidator = planDescSegmentID.Validators[0].(func(string) error)
	// planDescFormularyID is the schema descriptor for formulary_id field.
	planDescFormularyID := planFields[5].Descriptor()
	// plan.FormularyIDValidator is a validator for the "formulary_id" field. It is called by the builders before save.
	plan.FormularyIDValidator = planDescFormularyID.Validators[0].(func(string) error)
	// planDescCreatedAt is the schema descriptor for created_at field.
	planDescCreatedAt := planFields[8].Descriptor()
	// plan.DefaultCreatedAt holds the default value on creation for the created_at field.
	plan.DefaultCreatedAt = planDescCreatedAt.Default.(func() time.Time)
	// planDescUpdatedAt is the schema descriptor for updated_at field.
	planDescUpdatedAt := planFields[9].Descriptor()
	// plan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plan.DefaultUpdatedAt = planDescUpdatedAt.Default.(func() time.Time)
	// plan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plan.UpdateDefaultUpdatedAt = planDescUpdatedAt.UpdateDefault.(func() time.Time)
}
