// Code generated by ent, DO NOT EDIT.

package formularyentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the formularyentry type in the database.
	Label = "formulary_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTierLevel holds the string denoting the tier_level field in the database.
	FieldTierLevel = "tier_level"
	// FieldTierName holds the string denoting the tier_name field in the database.
	FieldTierName = "tier_name"
	// FieldPriorAuthRequired holds the string denoting the prior_auth_required field in the database.
	FieldPriorAuthRequired = "prior_auth_required"
	// FieldStepTherapy holds the string denoting the step_therapy field in the database.
	FieldStepTherapy = "step_therapy"
	// FieldQuantityLimit holds the string denoting the quantity_limit field in the database.
	FieldQuantityLimit = "quantity_limit"
	// FieldQuantityLimitAmount holds the string denoting the quantity_limit_amount field in the database.
	FieldQuantityLimitAmount = "quantity_limit_amount"
	// FieldQuantityLimitDays holds the string denoting the quantity_limit_days field in the database.
	FieldQuantityLimitDays = "quantity_limit_days"
	// FieldCopayAmount holds the string denoting the copay_amount field in the database.
	FieldCopayAmount = "copay_amount"
	// FieldCoinsurancePct holds the string denoting the coinsurance_pct field in the database.
	FieldCoinsurancePct = "coinsurance_pct"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceDate holds the string denoting the source_date field in the database.
	FieldSourceDate = "source_date"
	// FieldIsCurrent holds the string denoting the is_current field in the database.
	FieldIsCurrent = "is_current"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgePlan holds the string denoting the plan edge name in mutations.
	EdgePlan = "plan"
	// EdgeDrug holds the string denoting the drug edge name in mutations.
	EdgeDrug = "drug"
	// Table holds the table name of the formularyentry in the database.
	Table = "formulary_entries"
	// PlanTable is the table that holds the plan relation/edge.
	PlanTable = "formulary_entries"
	// PlanInverseTable is the table name for the Plan entity.
	// It exists in this package in order to avoid circular dependency with the "plan" package.
	PlanInverseTable = "plans"
	// PlanColumn is the table column denoting the plan relation/edge.
	PlanColumn = "plan_formulary_entries"
	// DrugTable is the table that holds the drug relation/edge.
	DrugTable = "formulary_entries"
	// DrugInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugInverseTable = "drugs"
	// DrugColumn is the table column denoting the drug relation/edge.
	DrugColumn = "drug_formulary_entries"
)

// Columns holds all SQL columns for formularyentry fields.
var Columns = []string{
	FieldID,
	FieldTierLevel,
	FieldTierName,
	FieldPriorAuthRequired,
	FieldStepTherapy,
	FieldQuantityLimit,
	FieldQuantityLimitAmount,
	FieldQuantityLimitDays,
	FieldCopayAmount,
	FieldCoinsurancePct,
	FieldSourceType,
	FieldSourceDate,
	FieldIsCurrent,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "formulary_entries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"drug_formulary_entries",
	"plan_formulary_entries",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPriorAuthRequired holds the default value on creation for the "prior_auth_required" field.
	DefaultPriorAuthRequired bool
	// DefaultStepTherapy holds the default value on creation for the "step_therapy" field.
	DefaultStepTherapy bool
	// DefaultQuantityLimit holds the default value on creation for the "quantity_limit" field.
	DefaultQuantityLimit bool
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// DefaultIsCurrent holds the default value on creation for the "is_current" field.
	DefaultIsCurrent bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the FormularyEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTierLevel orders the results by the tier_level field.
func ByTierLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierLevel, opts...).ToFunc()
}

// ByTierName orders the results by the tier_name field.
func ByTierName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierName, opts...).ToFunc()
}

// ByPriorAuthRequired orders the results by the prior_auth_required field.
func ByPriorAuthRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriorAuthRequired, opts...).ToFunc()
}

// ByStepTherapy orders the results by the step_therapy field.
func ByStepTherapy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepTherapy, opts...).ToFunc()
}

// ByQuantityLimit orders the results by the quantity_limit field.
func ByQuantityLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantityLimit, opts...).ToFunc()
}

// ByQuantityLimitAmount orders the results by the quantity_limit_amount field.
func ByQuantityLimitAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantityLimitAmount, opts...).ToFunc()
}

// ByQuantityLimitDays orders the results by the quantity_limit_days field.
func ByQuantityLimitDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantityLimitDays, opts...).ToFunc()
}

// ByCopayAmount orders the results by the copay_amount field.
func ByCopayAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCopayAmount, opts...).ToFunc()
}

// ByCoinsurancePct orders the results by the coinsurance_pct field.
func ByCoinsurancePct(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoinsurancePct, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceDate orders the results by the source_date field.
func BySourceDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceDate, opts...).ToFunc()
}

// ByIsCurrent orders the results by the is_current field.
func ByIsCurrent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCurrent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPlanField orders the results by plan field.
func ByPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlanStep(), sql.OrderByField(field, opts...))
	}
}

// ByDrugField orders the results by drug field.
func ByDrugField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDrugStep(), sql.OrderByField(field, opts...))
	}
}
func newPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
	)
}
func newDrugStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DrugInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DrugTable, DrugColumn),
	)
}
