// Code generated by ent, DO NOT EDIT.

package formularyentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldID, id))
}

// TierLevel applies equality check predicate on the "tier_level" field. It's identical to TierLevelEQ.
func TierLevel(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldTierLevel, v))
}

// TierName applies equality check predicate on the "tier_name" field. It's identical to TierNameEQ.
func TierName(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldTierName, v))
}

// PriorAuthRequired applies equality check predicate on the "prior_auth_required" field. It's identical to PriorAuthRequiredEQ.
func PriorAuthRequired(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldPriorAuthRequired, v))
}

// StepTherapy applies equality check predicate on the "step_therapy" field. It's identical to StepTherapyEQ.
func StepTherapy(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldStepTherapy, v))
}

// QuantityLimit applies equality check predicate on the "quantity_limit" field. It's identical to QuantityLimitEQ.
func QuantityLimit(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldQuantityLimit, v))
}

// QuantityLimitAmount applies equality check predicate on the "quantity_limit_amount" field. It's identical to QuantityLimitAmountEQ.
func QuantityLimitAmount(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldQuantityLimitAmount, v))
}

// QuantityLimitDays applies equality check predicate on the "quantity_limit_days" field. It's identical to QuantityLimitDaysEQ.
func QuantityLimitDays(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldQuantityLimitDays, v))
}

// CopayAmount applies equality check predicate on the "copay_amount" field. It's identical to CopayAmountEQ.
func CopayAmount(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldCopayAmount, v))
}

// CoinsurancePct applies equality check predicate on the "coinsurance_pct" field. It's identical to CoinsurancePctEQ.
func CoinsurancePct(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldCoinsurancePct, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldSourceType, v))
}

// SourceDate applies equality check predicate on the "source_date" field. It's identical to SourceDateEQ.
func SourceDate(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldSourceDate, v))
}

// IsCurrent applies equality check predicate on the "is_current" field. It's identical to IsCurrentEQ.
func IsCurrent(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldIsCurrent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// TierLevelEQ applies the EQ predicate on the "tier_level" field.
func TierLevelEQ(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldTierLevel, v))
}

// TierLevelNEQ applies the NEQ predicate on the "tier_level" field.
func TierLevelNEQ(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldTierLevel, v))
}

// TierLevelIn applies the In predicate on the "tier_level" field.
func TierLevelIn(vs ...int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldTierLevel, vs...))
}

// TierLevelNotIn applies the NotIn predicate on the "tier_level" field.
func TierLevelNotIn(vs ...int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldTierLevel, vs...))
}

// TierLevelGT applies the GT predicate on the "tier_level" field.
func TierLevelGT(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldTierLevel, v))
}

// TierLevelGTE applies the GTE predicate on the "tier_level" field.
func TierLevelGTE(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldTierLevel, v))
}

// TierLevelLT applies the LT predicate on the "tier_level" field.
func TierLevelLT(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldTierLevel, v))
}

// TierLevelLTE applies the LTE predicate on the "tier_level" field.
func TierLevelLTE(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldTierLevel, v))
}

// TierLevelIsNil applies the IsNil predicate on the "tier_level" field.
func TierLevelIsNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIsNull(FieldTierLevel))
}

// TierLevelNotNil applies the NotNil predicate on the "tier_level" field.
func TierLevelNotNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotNull(FieldTierLevel))
}

// TierNameEQ applies the EQ predicate on the "tier_name" field.
func TierNameEQ(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldTierName, v))
}

// TierNameNEQ applies the NEQ predicate on the "tier_name" field.
func TierNameNEQ(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldTierName, v))
}

// TierNameIn applies the In predicate on the "tier_name" field.
func TierNameIn(vs ...string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldTierName, vs...))
}

// TierNameNotIn applies the NotIn predicate on the "tier_name" field.
func TierNameNotIn(vs ...string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldTierName, vs...))
}

// TierNameGT applies the GT predicate on the "tier_name" field.
func TierNameGT(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldTierName, v))
}

// TierNameGTE applies the GTE predicate on the "tier_name" field.
func TierNameGTE(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldTierName, v))
}

// TierNameLT applies the LT predicate on the "tier_name" field.
func TierNameLT(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldTierName, v))
}

// TierNameLTE applies the LTE predicate on the "tier_name" field.
func TierNameLTE(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldTierName, v))
}

// TierNameContains applies the Contains predicate on the "tier_name" field.
func TierNameContains(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldContains(FieldTierName, v))
}

// TierNameHasPrefix applies the HasPrefix predicate on the "tier_name" field.
func TierNameHasPrefix(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldHasPrefix(FieldTierName, v))
}

// TierNameHasSuffix applies the HasSuffix predicate on the "tier_name" field.
func TierNameHasSuffix(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldHasSuffix(FieldTierName, v))
}

// TierNameIsNil applies the IsNil predicate on the "tier_name" field.
func TierNameIsNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIsNull(FieldTierName))
}

// TierNameNotNil applies the NotNil predicate on the "tier_name" field.
func TierNameNotNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotNull(FieldTierName))
}

// TierNameEqualFold applies the EqualFold predicate on the "tier_name" field.
func TierNameEqualFold(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEqualFold(FieldTierName, v))
}

// TierNameContainsFold applies the ContainsFold predicate on the "tier_name" field.
func TierNameContainsFold(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldContainsFold(FieldTierName, v))
}

// PriorAuthRequiredEQ applies the EQ predicate on the "prior_auth_required" field.
func PriorAuthRequiredEQ(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldPriorAuthRequired, v))
}

// PriorAuthRequiredNEQ applies the NEQ predicate on the "prior_auth_required" field.
func PriorAuthRequiredNEQ(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldPriorAuthRequired, v))
}

// StepTherapyEQ applies the EQ predicate on the "step_therapy" field.
func StepTherapyEQ(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldStepTherapy, v))
}

// StepTherapyNEQ applies the NEQ predicate on the "step_therapy" field.
func StepTherapyNEQ(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldStepTherapy, v))
}

// QuantityLimitEQ applies the EQ predicate on the "quantity_limit" field.
func QuantityLimitEQ(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldQuantityLimit, v))
}

// QuantityLimitNEQ applies the NEQ predicate on the "quantity_limit" field.
func QuantityLimitNEQ(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldQuantityLimit, v))
}

// QuantityLimitAmountEQ applies the EQ predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountEQ(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldQuantityLimitAmount, v))
}

// QuantityLimitAmountNEQ applies the NEQ predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountNEQ(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldQuantityLimitAmount, v))
}

// QuantityLimitAmountIn applies the In predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountIn(vs ...float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldQuantityLimitAmount, vs...))
}

// QuantityLimitAmountNotIn applies the NotIn predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountNotIn(vs ...float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldQuantityLimitAmount, vs...))
}

// QuantityLimitAmountGT applies the GT predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountGT(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldQuantityLimitAmount, v))
}

// QuantityLimitAmountGTE applies the GTE predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountGTE(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldQuantityLimitAmount, v))
}

// QuantityLimitAmountLT applies the LT predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountLT(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldQuantityLimitAmount, v))
}

// QuantityLimitAmountLTE applies the LTE predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountLTE(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldQuantityLimitAmount, v))
}

// QuantityLimitAmountIsNil applies the IsNil predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountIsNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIsNull(FieldQuantityLimitAmount))
}

// QuantityLimitAmountNotNil applies the NotNil predicate on the "quantity_limit_amount" field.
func QuantityLimitAmountNotNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotNull(FieldQuantityLimitAmount))
}

// QuantityLimitDaysEQ applies the EQ predicate on the "quantity_limit_days" field.
func QuantityLimitDaysEQ(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldQuantityLimitDays, v))
}

// QuantityLimitDaysNEQ applies the NEQ predicate on the "quantity_limit_days" field.
func QuantityLimitDaysNEQ(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldQuantityLimitDays, v))
}

// QuantityLimitDaysIn applies the In predicate on the "quantity_limit_days" field.
func QuantityLimitDaysIn(vs ...int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldQuantityLimitDays, vs...))
}

// QuantityLimitDaysNotIn applies the NotIn predicate on the "quantity_limit_days" field.
func QuantityLimitDaysNotIn(vs ...int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldQuantityLimitDays, vs...))
}

// QuantityLimitDaysGT applies the GT predicate on the "quantity_limit_days" field.
func QuantityLimitDaysGT(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldQuantityLimitDays, v))
}

// QuantityLimitDaysGTE applies the GTE predicate on the "quantity_limit_days" field.
func QuantityLimitDaysGTE(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldQuantityLimitDays, v))
}

// QuantityLimitDaysLT applies the LT predicate on the "quantity_limit_days" field.
func QuantityLimitDaysLT(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldQuantityLimitDays, v))
}

// QuantityLimitDaysLTE applies the LTE predicate on the "quantity_limit_days" field.
func QuantityLimitDaysLTE(v int) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldQuantityLimitDays, v))
}

// QuantityLimitDaysIsNil applies the IsNil predicate on the "quantity_limit_days" field.
func QuantityLimitDaysIsNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIsNull(FieldQuantityLimitDays))
}

// QuantityLimitDaysNotNil applies the NotNil predicate on the "quantity_limit_days" field.
func QuantityLimitDaysNotNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotNull(FieldQuantityLimitDays))
}

// CopayAmountEQ applies the EQ predicate on the "copay_amount" field.
func CopayAmountEQ(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldCopayAmount, v))
}

// CopayAmountNEQ applies the NEQ predicate on the "copay_amount" field.
func CopayAmountNEQ(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldCopayAmount, v))
}

// CopayAmountIn applies the In predicate on the "copay_amount" field.
func CopayAmountIn(vs ...float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldCopayAmount, vs...))
}

// CopayAmountNotIn applies the NotIn predicate on the "copay_amount" field.
func CopayAmountNotIn(vs ...float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldCopayAmount, vs...))
}

// CopayAmountGT applies the GT predicate on the "copay_amount" field.
func CopayAmountGT(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldCopayAmount, v))
}

// CopayAmountGTE applies the GTE predicate on the "copay_amount" field.
func CopayAmountGTE(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldCopayAmount, v))
}

// CopayAmountLT applies the LT predicate on the "copay_amount" field.
func CopayAmountLT(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldCopayAmount, v))
}

// CopayAmountLTE applies the LTE predicate on the "copay_amount" field.
func CopayAmountLTE(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldCopayAmount, v))
}

// CopayAmountIsNil applies the IsNil predicate on the "copay_amount" field.
func CopayAmountIsNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIsNull(FieldCopayAmount))
}

// CopayAmountNotNil applies the NotNil predicate on the "copay_amount" field.
func CopayAmountNotNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotNull(FieldCopayAmount))
}

// CoinsurancePctEQ applies the EQ predicate on the "coinsurance_pct" field.
func CoinsurancePctEQ(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldCoinsurancePct, v))
}

// CoinsurancePctNEQ applies the NEQ predicate on the "coinsurance_pct" field.
func CoinsurancePctNEQ(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldCoinsurancePct, v))
}

// CoinsurancePctIn applies the In predicate on the "coinsurance_pct" field.
func CoinsurancePctIn(vs ...float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldCoinsurancePct, vs...))
}

// CoinsurancePctNotIn applies the NotIn predicate on the "coinsurance_pct" field.
func CoinsurancePctNotIn(vs ...float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldCoinsurancePct, vs...))
}

// CoinsurancePctGT applies the GT predicate on the "coinsurance_pct" field.
func CoinsurancePctGT(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldCoinsurancePct, v))
}

// CoinsurancePctGTE applies the GTE predicate on the "coinsurance_pct" field.
func CoinsurancePctGTE(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldCoinsurancePct, v))
}

// CoinsurancePctLT applies the LT predicate on the "coinsurance_pct" field.
func CoinsurancePctLT(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldCoinsurancePct, v))
}

// CoinsurancePctLTE applies the LTE predicate on the "coinsurance_pct" field.
func CoinsurancePctLTE(v float64) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldCoinsurancePct, v))
}

// CoinsurancePctIsNil applies the IsNil predicate on the "coinsurance_pct" field.
func CoinsurancePctIsNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIsNull(FieldCoinsurancePct))
}

// CoinsurancePctNotNil applies the NotNil predicate on the "coinsurance_pct" field.
func CoinsurancePctNotNil() predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotNull(FieldCoinsurancePct))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceDateEQ applies the EQ predicate on the "source_date" field.
func SourceDateEQ(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldSourceDate, v))
}

// SourceDateNEQ applies the NEQ predicate on the "source_date" field.
func SourceDateNEQ(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldSourceDate, v))
}

// SourceDateIn applies the In predicate on the "source_date" field.
func SourceDateIn(vs ...time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldSourceDate, vs...))
}

// SourceDateNotIn applies the NotIn predicate on the "source_date" field.
func SourceDateNotIn(vs ...time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldSourceDate, vs...))
}

// SourceDateGT applies the GT predicate on the "source_date" field.
func SourceDateGT(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldSourceDate, v))
}

// SourceDateGTE applies the GTE predicate on the "source_date" field.
func SourceDateGTE(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldSourceDate, v))
}

// SourceDateLT applies the LT predicate on the "source_date" field.
func SourceDateLT(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldSourceDate, v))
}

// SourceDateLTE applies the LTE predicate on the "source_date" field.
func SourceDateLTE(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldSourceDate, v))
}

// IsCurrentEQ applies the EQ predicate on the "is_current" field.
func IsCurrentEQ(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldIsCurrent, v))
}

// IsCurrentNEQ applies the NEQ predicate on the "is_current" field.
func IsCurrentNEQ(v bool) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldIsCurrent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.FormularyEntry {
	return predicate.FormularyEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.Plan) predicate.FormularyEntry {
	return predicate.FormularyEntry(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDrug applies the HasEdge predicate on the "drug" edge.
func HasDrug() predicate.FormularyEntry {
	return predicate.FormularyEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DrugTable, DrugColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDrugWith applies the HasEdge predicate on the "drug" edge with a given conditions (other predicates).
func HasDrugWith(preds ...predicate.Drug) predicate.FormularyEntry {
	return predicate.FormularyEntry(func(s *sql.Selector) {
		step := newDrugStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FormularyEntry) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FormularyEntry) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FormularyEntry) predicate.FormularyEntry {
	return predicate.FormularyEntry(sql.NotPredicates(p))
}
