// Code generated by ent, DO NOT EDIT.

package plan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the plan type in the database.
	Label = "plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContractID holds the string denoting the contract_id field in the database.
	FieldContractID = "contract_id"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldSegmentID holds the string denoting the segment_id field in the database.
	FieldSegmentID = "segment_id"
	// FieldContractName holds the string denoting the contract_name field in the database.
	FieldContractName = "contract_name"
	// FieldPlanName holds the string denoting the plan_name field in the database.
	FieldPlanName = "plan_name"
	// FieldFormularyID holds the string denoting the formulary_id field in the database.
	FieldFormularyID = "formulary_id"
	// FieldPlanType holds the string denoting the plan_type field in the database.
	FieldPlanType = "plan_type"
	// FieldSnpType holds the string denoting the snp_type field in the database.
	FieldSnpType = "snp_type"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeFormularyEntries holds the string denoting the formulary_entries edge name in mutations.
	EdgeFormularyEntries = "formulary_entries"
	// Table holds the table name of the plan in the database.
	Table = "plans"
	// FormularyEntriesTable is the table that holds the formulary_entries relation/edge.
	FormularyEntriesTable = "formulary_entries"
	// FormularyEntriesInverseTable is the table name for the FormularyEntry entity.
	// It exists in this package in order to avoid circular dependency with the "formularyentry" package.
	FormularyEntriesInverseTable = "formulary_entries"
	// FormularyEntriesColumn is the table column denoting the formulary_entries relation/edge.
	FormularyEntriesColumn = "plan_formulary_entries"
)

// Columns holds all SQL columns for plan fields.
var Columns = []string{
	FieldID,
	FieldContractID,
	FieldPlanID,
	FieldSegmentID,
	FieldContractName,
	FieldPlanName,
	FieldFormularyID,
	FieldPlanType,
	FieldSnpType,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ContractIDValidator is a validator for the "contract_id" field. It is called by the builders before save.
	ContractIDValidator func(string) error
	// PlanIDValidator is a validator for the "plan_id" field. It is called by the builders before save.
	PlanIDValidator func(string) error
	// SegmentIDValidator is a validator for the "segment_id" field. It is called by the builders before save.
	SegmentIDValidator func(string) error
	// FormularyIDValidator is a validator for the "formulary_id" field. It is called by the builders before save.
	FormularyIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Plan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByContractID orders the results by the contract_id field.
func ByContractID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContractID, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// BySegmentID orders the results by the segment_id field.
func BySegmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSegmentID, opts...).ToFunc()
}

// ByContractName orders the results by the contract_name field.
func ByContractName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContractName, opts...).ToFunc()
}

// ByPlanName orders the results by the plan_name field.
func ByPlanName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanName, opts...).ToFunc()
}

// ByFormularyID orders the results by the formulary_id field.
func ByFormularyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormularyID, opts...).ToFunc()
}

// ByPlanType orders the results by the plan_type field.
func ByPlanType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanType, opts...).ToFunc()
}

// BySnpType orders the results by the snp_type field.
func BySnpType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnpType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByFormularyEntriesCount orders the results by formulary_entries count.
func ByFormularyEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFormularyEntriesStep(), opts...)
	}
}

// ByFormularyEntries orders the results by formulary_entries terms.
func ByFormularyEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFormularyEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFormularyEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FormularyEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FormularyEntriesTable, FormularyEntriesColumn),
	)
}
