// Code generated by ent, DO NOT EDIT.

package plan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kyanaman/formularycheck/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldID, id))
}

// ContractID applies equality check predicate on the "contract_id" field. It's identical to ContractIDEQ.
func ContractID(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldContractID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPlanID, v))
}

// SegmentID applies equality check predicate on the "segment_id" field. It's identical to SegmentIDEQ.
func SegmentID(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSegmentID, v))
}

// ContractName applies equality check predicate on the "contract_name" field. It's identical to ContractNameEQ.
func ContractName(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldContractName, v))
}

// PlanName applies equality check predicate on the "plan_name" field. It's identical to PlanNameEQ.
func PlanName(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPlanName, v))
}

// FormularyID applies equality check predicate on the "formulary_id" field. It's identical to FormularyIDEQ.
func FormularyID(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldFormularyID, v))
}

// PlanType applies equality check predicate on the "plan_type" field. It's identical to PlanTypeEQ.
func PlanType(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPlanType, v))
}

// SnpType applies equality check predicate on the "snp_type" field. It's identical to SnpTypeEQ.
func SnpType(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSnpType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUpdatedAt, v))
}

// ContractIDEQ applies the EQ predicate on the "contract_id" field.
func ContractIDEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldContractID, v))
}

// ContractIDNEQ applies the NEQ predicate on the "contract_id" field.
func ContractIDNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldContractID, v))
}

// ContractIDIn applies the In predicate on the "contract_id" field.
func ContractIDIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldContractID, vs...))
}

// ContractIDNotIn applies the NotIn predicate on the "contract_id" field.
func ContractIDNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldContractID, vs...))
}

// ContractIDGT applies the GT predicate on the "contract_id" field.
func ContractIDGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldContractID, v))
}

// ContractIDGTE applies the GTE predicate on the "contract_id" field.
func ContractIDGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldContractID, v))
}

// ContractIDLT applies the LT predicate on the "contract_id" field.
func ContractIDLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldContractID, v))
}

// ContractIDLTE applies the LTE predicate on the "contract_id" field.
func ContractIDLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldContractID, v))
}

// ContractIDContains applies the Contains predicate on the "contract_id" field.
func ContractIDContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldContractID, v))
}

// ContractIDHasPrefix applies the HasPrefix predicate on the "contract_id" field.
func ContractIDHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldContractID, v))
}

// ContractIDHasSuffix applies the HasSuffix predicate on the "contract_id" field.
func ContractIDHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldContractID, v))
}

// ContractIDEqualFold applies the EqualFold predicate on the "contract_id" field.
func ContractIDEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldContractID, v))
}

// ContractIDContainsFold applies the ContainsFold predicate on the "contract_id" field.
func ContractIDContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldContractID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPlanID, v))
}

// PlanIDContains applies the Contains predicate on the "plan_id" field.
func PlanIDContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldPlanID, v))
}

// PlanIDHasPrefix applies the HasPrefix predicate on the "plan_id" field.
func PlanIDHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldPlanID, v))
}

// PlanIDHasSuffix applies the HasSuffix predicate on the "plan_id" field.
func PlanIDHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldPlanID, v))
}

// PlanIDEqualFold applies the EqualFold predicate on the "plan_id" field.
func PlanIDEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldPlanID, v))
}

// PlanIDContainsFold applies the ContainsFold predicate on the "plan_id" field.
func PlanIDContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldPlanID, v))
}

// SegmentIDEQ applies the EQ predicate on the "segment_id" field.
func SegmentIDEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSegmentID, v))
}

// SegmentIDNEQ applies the NEQ predicate on the "segment_id" field.
func SegmentIDNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldSegmentID, v))
}

// SegmentIDIn applies the In predicate on the "segment_id" field.
func SegmentIDIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldSegmentID, vs...))
}

// SegmentIDNotIn applies the NotIn predicate on the "segment_id" field.
func SegmentIDNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldSegmentID, vs...))
}

// SegmentIDGT applies the GT predicate on the "segment_id" field.
func SegmentIDGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldSegmentID, v))
}

// SegmentIDGTE applies the GTE predicate on the "segment_id" field.
func SegmentIDGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldSegmentID, v))
}

// SegmentIDLT applies the LT predicate on the "segment_id" field.
func SegmentIDLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldSegmentID, v))
}

// SegmentIDLTE applies the LTE predicate on the "segment_id" field.
func SegmentIDLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldSegmentID, v))
}

// SegmentIDContains applies the Contains predicate on the "segment_id" field.
func SegmentIDContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldSegmentID, v))
}

// SegmentIDHasPrefix applies the HasPrefix predicate on the "segment_id" field.
func SegmentIDHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldSegmentID, v))
}

// SegmentIDHasSuffix applies the HasSuffix predicate on the "segment_id" field.
func SegmentIDHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldSegmentID, v))
}

// SegmentIDEqualFold applies the EqualFold predicate on the "segment_id" field.
func SegmentIDEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldSegmentID, v))
}

// SegmentIDContainsFold applies the ContainsFold predicate on the "segment_id" field.
func SegmentIDContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldSegmentID, v))
}

// ContractNameEQ applies the EQ predicate on the "contract_name" field.
func ContractNameEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldContractName, v))
}

// ContractNameNEQ applies the NEQ predicate on the "contract_name" field.
func ContractNameNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldContractName, v))
}

// ContractNameIn applies the In predicate on the "contract_name" field.
func ContractNameIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldContractName, vs...))
}

// ContractNameNotIn applies the NotIn predicate on the "contract_name" field.
func ContractNameNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldContractName, vs...))
}

// ContractNameGT applies the GT predicate on the "contract_name" field.
func ContractNameGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldContractName, v))
}

// ContractNameGTE applies the GTE predicate on the "contract_name" field.
func ContractNameGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldContractName, v))
}

// ContractNameLT applies the LT predicate on the "contract_name" field.
func ContractNameLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldContractName, v))
}

// ContractNameLTE applies the LTE predicate on the "contract_name" field.
func ContractNameLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldContractName, v))
}

// ContractNameContains applies the Contains predicate on the "contract_name" field.
func ContractNameContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldContractName, v))
}

// ContractNameHasPrefix applies the HasPrefix predicate on the "contract_name" field.
func ContractNameHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldContractName, v))
}

// ContractNameHasSuffix applies the HasSuffix predicate on the "contract_name" field.
func ContractNameHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldContractName, v))
}

// ContractNameIsNil applies the IsNil predicate on the "contract_name" field.
func ContractNameIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldContractName))
}

// ContractNameNotNil applies the NotNil predicate on the "contract_name" field.
func ContractNameNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldContractName))
}

// ContractNameEqualFold applies the EqualFold predicate on the "contract_name" field.
func ContractNameEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldContractName, v))
}

// ContractNameContainsFold applies the ContainsFold predicate on the "contract_name" field.
func ContractNameContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldContractName, v))
}

// PlanNameEQ applies the EQ predicate on the "plan_name" field.
func PlanNameEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPlanName, v))
}

// PlanNameNEQ applies the NEQ predicate on the "plan_name" field.
func PlanNameNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPlanName, v))
}

// PlanNameIn applies the In predicate on the "plan_name" field.
func PlanNameIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPlanName, vs...))
}

// PlanNameNotIn applies the NotIn predicate on the "plan_name" field.
func PlanNameNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPlanName, vs...))
}

// PlanNameGT applies the GT predicate on the "plan_name" field.
func PlanNameGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPlanName, v))
}

// PlanNameGTE applies the GTE predicate on the "plan_name" field.
func PlanNameGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPlanName, v))
}

// PlanNameLT applies the LT predicate on the "plan_name" field.
func PlanNameLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPlanName, v))
}

// PlanNameLTE applies the LTE predicate on the "plan_name" field.
func PlanNameLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPlanName, v))
}

// PlanNameContains applies the Contains predicate on the "plan_name" field.
func PlanNameContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldPlanName, v))
}

// PlanNameHasPrefix applies the HasPrefix predicate on the "plan_name" field.
func PlanNameHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldPlanName, v))
}

// PlanNameHasSuffix applies the HasSuffix predicate on the "plan_name" field.
func PlanNameHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldPlanName, v))
}

// PlanNameIsNil applies the IsNil predicate on the "plan_name" field.
func PlanNameIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldPlanName))
}

// PlanNameNotNil applies the NotNil predicate on the "plan_name" field.
func PlanNameNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldPlanName))
}

// PlanNameEqualFold applies the EqualFold predicate on the "plan_name" field.
func PlanNameEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldPlanName, v))
}

// PlanNameContainsFold applies the ContainsFold predicate on the "plan_name" field.
func PlanNameContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldPlanName, v))
}

// FormularyIDEQ applies the EQ predicate on the "formulary_id" field.
func FormularyIDEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldFormularyID, v))
}

// FormularyIDNEQ applies the NEQ predicate on the "formulary_id" field.
func FormularyIDNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldFormularyID, v))
}

// FormularyIDIn applies the In predicate on the "formulary_id" field.
func FormularyIDIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldFormularyID, vs...))
}

// FormularyIDNotIn applies the NotIn predicate on the "formulary_id" field.
func FormularyIDNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldFormularyID, vs...))
}

// FormularyIDGT applies the GT predicate on the "formulary_id" field.
func FormularyIDGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldFormularyID, v))
}

// FormularyIDGTE applies the GTE predicate on the "formulary_id" field.
func FormularyIDGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldFormularyID, v))
}

// FormularyIDLT applies the LT predicate on the "formulary_id" field.
func FormularyIDLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldFormularyID, v))
}

// FormularyIDLTE applies the LTE predicate on the "formulary_id" field.
func FormularyIDLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldFormularyID, v))
}

// FormularyIDContains applies the Contains predicate on the "formulary_id" field.
func FormularyIDContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldFormularyID, v))
}

// FormularyIDHasPrefix applies the HasPrefix predicate on the "formulary_id" field.
func FormularyIDHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldFormularyID, v))
}

// FormularyIDHasSuffix applies the HasSuffix predicate on the "formulary_id" field.
func FormularyIDHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldFormularyID, v))
}

// FormularyIDEqualFold applies the EqualFold predicate on the "formulary_id" field.
func FormularyIDEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldFormularyID, v))
}

// FormularyIDContainsFold applies the ContainsFold predicate on the "formulary_id" field.
func FormularyIDContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldFormularyID, v))
}

// PlanTypeEQ applies the EQ predicate on the "plan_type" field.
func PlanTypeEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPlanType, v))
}

// PlanTypeNEQ applies the NEQ predicate on the "plan_type" field.
func PlanTypeNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPlanType, v))
}

// PlanTypeIn applies the In predicate on the "plan_type" field.
func PlanTypeIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPlanType, vs...))
}

// PlanTypeNotIn applies the NotIn predicate on the "plan_type" field.
func PlanTypeNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPlanType, vs...))
}

// PlanTypeGT applies the GT predicate on the "plan_type" field.
func PlanTypeGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPlanType, v))
}

// PlanTypeGTE applies the GTE predicate on the "plan_type" field.
func PlanTypeGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPlanType, v))
}

// PlanTypeLT applies the LT predicate on the "plan_type" field.
func PlanTypeLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPlanType, v))
}

// PlanTypeLTE applies the LTE predicate on the "plan_type" field.
func PlanTypeLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPlanType, v))
}

// PlanTypeContains applies the Contains predicate on the "plan_type" field.
func PlanTypeContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldPlanType, v))
}

// PlanTypeHasPrefix applies the HasPrefix predicate on the "plan_type" field.
func PlanTypeHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldPlanType, v))
}

// PlanTypeHasSuffix applies the HasSuffix predicate on the "plan_type" field.
func PlanTypeHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldPlanType, v))
}

// PlanTypeIsNil applies the IsNil predicate on the "plan_type" field.
func PlanTypeIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldPlanType))
}

// PlanTypeNotNil applies the NotNil predicate on the "plan_type" field.
func PlanTypeNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldPlanType))
}

// PlanTypeEqualFold applies the EqualFold predicate on the "plan_type" field.
func PlanTypeEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldPlanType, v))
}

// PlanTypeContainsFold applies the ContainsFold predicate on the "plan_type" field.
func PlanTypeContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldPlanType, v))
}

// SnpTypeEQ applies the EQ predicate on the "snp_type" field.
func SnpTypeEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSnpType, v))
}

// SnpTypeNEQ applies the NEQ predicate on the "snp_type" field.
func SnpTypeNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldSnpType, v))
}

// SnpTypeIn applies the In predicate on the "snp_type" field.
func SnpTypeIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldSnpType, vs...))
}

// SnpTypeNotIn applies the NotIn predicate on the "snp_type" field.
func SnpTypeNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldSnpType, vs...))
}

// SnpTypeGT applies the GT predicate on the "snp_type" field.
func SnpTypeGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldSnpType, v))
}

// SnpTypeGTE applies the GTE predicate on the "snp_type" field.
func SnpTypeGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldSnpType, v))
}

// SnpTypeLT applies the LT predicate on the "snp_type" field.
func SnpTypeLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldSnpType, v))
}

// SnpTypeLTE applies the LTE predicate on the "snp_type" field.
func SnpTypeLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldSnpType, v))
}

// SnpTypeContains applies the Contains predicate on the "snp_type" field.
func SnpTypeContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldSnpType, v))
}

// SnpTypeHasPrefix applies the HasPrefix predicate on the "snp_type" field.
func SnpTypeHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldSnpType, v))
}

// SnpTypeHasSuffix applies the HasSuffix predicate on the "snp_type" field.
func SnpTypeHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldSnpType, v))
}

// SnpTypeIsNil applies the IsNil predicate on the "snp_type" field.
func SnpTypeIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldSnpType))
}

// SnpTypeNotNil applies the NotNil predicate on the "snp_type" field.
func SnpTypeNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldSnpType))
}

// SnpTypeEqualFold applies the EqualFold predicate on the "snp_type" field.
func SnpTypeEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldSnpType, v))
}

// SnpTypeContainsFold applies the ContainsFold predicate on the "snp_type" field.
func SnpTypeContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldSnpType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasFormularyEntries applies the HasEdge predicate on the "formulary_entries" edge.
func HasFormularyEntries() predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FormularyEntriesTable, FormularyEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFormularyEntriesWith applies the HasEdge predicate on the "formulary_entries" edge with a given conditions (other predicates).
func HasFormularyEntriesWith(preds ...predicate.FormularyEntry) predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := newFormularyEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.NotPredicates(p))
}
