// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Drug is the predicate function for drug builders.
type Drug func(*sql.Selector)

// DrugNdcMap is the predicate function for drugndcmap builders.
type DrugNdcMap func(*sql.Selector)

// FormularyEntry is the predicate function for formularyentry builders.
type FormularyEntry func(*sql.Selector)

// Plan is the predicate function for plan builders.
type Plan func(*sql.Selector)
